### ISSUE TITLE
RDKit hangs while computing MCS for certain ligand pairs.

### ISSUE THREAD

**Issue by lohedges** [michellab/BioSimSpace#100]
This appears to be a bug with RDKit rather than BioSImSpace, but I'm not sure how we should best handle it. For certain ligand pairs the `Chem.rdFMCS.FindMCS` routine seems to hang indefinitely, completely ignoring the timeout that is passed to the function. Cathepsin ligands appear to be particularly problematic, e.g. those used for the D3R2018 run:

The following example assumes you are located in [this](https://github.com/michellab/D3R2018/tree/master/CatS_Simmerling/mol/aligned/parameterised) directory.

```python
import BioSimSpace as BSS

# Load the ligands.
m0 = BSS.IO.readMolecules(BSS.IO.glob("CatS_4.*")).getMolecules()[0]
m1 = BSS.IO.readMolecules(BSS.IO.glob("CatS_9.*")).getMolecules()[0]

# Generate a mapping with a really short time out.
mapping = BSS.Align.matchAtoms(m0, m1, timeout=0.5*BSS.Units.Time.second)

# We get a mapping, but it's rubbish.
print(mapping)
{1: 1, 0: 0, 4: 4, 2: 2, 9: 9}

# Now try one whole second!
mapping = BSS.Align.matchAtoms(m0, m1, timeout=1*BSS.Units.Time.second)

# Hangs indefinitely...
```

Let's see what happens if I enable verbose mode in RDKit.

```
mapping = BSS.Align.matchAtoms(m0, m1, timeout=1*BSS.Units.Time.second)
Query [H]C1C([H])C(C(SC([H])([H])C([H])([H])[N+]2([H])C([H])([H])C([H])([H])C([H])(C(F)(F)F)C([H])([H])C2([H])[H])C([H])C1C1NN(C2C1C([H])([H])N(C([H])([H])C2([H])[H])S(O)(O)C([H])([H])[H])C([H])([H])C([H])([H])C([H])([H])[N+]1([H])C([H])([H])C([H])([H])C([H])(N2C(O)C([H])([H])C([H])([H])C2([H])[H])C([H])([H])C1([H])[H])C(F)(F)F 99(99) atoms, 104(104) bonds
1 Seeds:105 MCS 5 atoms, 4 bonds for 0.0016 seconds. bond[0]=0
2 Seeds:106 MCS 10 atoms, 10 bonds for 0.0016 seconds. bond[0]=0
3 Seeds:107 MCS 21 atoms, 21 bonds for 0.0017 seconds. bond[0]=0
4 Seeds:108 MCS 31 atoms, 33 bonds for 0.0017 seconds. bond[0]=0
5 Seeds:109 MCS 41 atoms, 43 bonds for 0.0018 seconds. bond[0]=0
6 Seeds:110 MCS 53 atoms, 55 bonds for 0.0019 seconds. bond[0]=0
7 Seeds:111 MCS 62 atoms, 64 bonds for 0.0019 seconds. bond[0]=0
8 Seeds:112 MCS 70 atoms, 73 bonds for 0.0020 seconds. bond[0]=0
9 Seeds:113 MCS 78 atoms, 81 bonds for 0.0021 seconds. bond[0]=0
10 Seeds:114 MCS 85 atoms, 89 bonds for 0.0022 seconds. bond[0]=0
11 Seeds:115 MCS 92 atoms, 96 bonds for 0.0023 seconds. bond[0]=0
```

It just hangs after this with no more progress. 92 atoms seems like a fine match for this system (`m0` has 99 atoms, `m1` has 102), so I've no idea why it won't return.

How are we meant to deal with this? It won't even exit with CTRL+C and I manually have to kill the process. I guess I should also post a bug report on the RDKit page.

**Comment by lohedges** [comment]
I've tried adjusting all of the options that we pass to `Chem.rdFMCS.FindMCS` and nothing makes a difference, it still hangs.

**Comment by lohedges** [comment]
Actually, RDKit only accepts integers for the timeout, so the 0.5 second one above was basically 0 timeout.

**Comment by lohedges** [comment]
It seems that RDKit has a hard-coded lower bound on the number of steps for their MCS routine, which means that the timeout is never triggered until you reach this limit. This is problematic for big systems where the search space is large. I've fixed this on a local fork and am awaiting comment from the RDKit development team.

**Comment by lohedges** [comment]
This is now approved for merging in RDKit and will hopefully be available in their next Conda release. I'll leave this issue open until then for ease of searching in case any users are experiencing the same problem.

**Comment by lohedges** [comment]
A new RDKit patch release should be available some time next week, so this will be fixed then.

**Comment by lohedges** [comment]
Actually might be a little longer, since the `conda-forge` package trails the main release on the `rdkit` channel. (We can always switch back to using the `rdkit` one temporarily.)

**Comment by lohedges** [comment]
Closing since [RDKit 2019.03.4](https://github.com/rdkit/rdkit/releases/tag/Release_2019_03_4) is now out and is already available in the `conda-forge` [channel](https://anaconda.org/conda-forge/rdkit/files).

**Comment by kexul** [comment]
Hi @lohedges , same behavior here using RDKit 2020.09.3 from `conda-forge` channel, here is the input files and code I've used: 

```
ligand2 = BSS.IO.readPDB('29_30_30~29_aligned.pdb').getMolecules()[0]
ligand1 = BSS.IO.readPDB('30_ref_30~29_aligned.pdb').getMolecules()[0]
mapping = BSS.Align.matchAtoms(ligand1, ligand2)
```
[30_ref_30~29_aligned.zip](https://github.com/michellab/BioSimSpace/files/7036240/30_ref_30.29_aligned.zip)

**Comment by lohedges** [comment]
Hi there. The following works (mapping in either direction):

```python
import rdkit.Chem as Chem
import rdkit.Chem.rdFMCS as rdFMCS

# Load the ligands.
mols = [Chem.MolFromPDBFile("9_30_30~29_aligned.pdb", False, False, 0),
        Chem.MolFromPDBFile("30_ref_30~29_aligned.pdb", False, False, 0)]

# Run a very short MCS. (One second)
mcs = rdFMCS.FindMCS(mols, atomCompare=rdFMCS.AtomCompare.CompareAny,
    bondCompare=rdFMCS.BondCompare.CompareAny, completeRingsOnly=True,
    ringMatchesRingOnly=True, matchChiralTag=False, matchValences=False,
    maximizeBonds=False, timeout=1, verbose=True)
```

I'll try to work out where it's hanging in BioSimSpace. It could possibly be during the MCS scoring, which comes after the step above.

**Comment by kexul** [comment]
> It could possibly be during the MCS scoring, which comes after the step above.
Yes, I've stepped into the code and found it hanging during scoring.

**Comment by lohedges** [comment]
Yes, it's hanging when scoring the mappings. For this ligand pair it looks like RDKit returns 1000 possible mappings. These seem to be quite slow to score, i.e. order seconds each. I'll let it run and see if it gets to completion, or if there is some memory issue that makes it slow down as it progresses.

There might be a way of limiting the number of matches returned by RDKit in the first place, which might help in situations like this. However, that might not guarantee that you get the one with the best score.

**Comment by lohedges** [comment]
The code is here:

```python
    ...

    # Get the set of matching substructures in each molecule. For some reason
    # setting uniquify to True removes valid matches, in some cases even the
    # best match! As such, we set uniquify to False and account ignore duplicate
    # mappings in the code below.
    matches0 = rdkit_molecule0.GetSubstructMatches(mcs_smarts, uniquify=False, maxMatches=1000, useChirality=False)
    matches1 = rdkit_molecule1.GetSubstructMatches(mcs_smarts, uniquify=False, maxMatches=1000, useChirality=False)

    # Swap the order of the matches.
    if len(matches0) < len(matches1):
        matches0, matches1 = matches1, matches0
        is_swapped = True
    else:
        is_swapped = False

    # Initialise a list to hold the mappings.
    mappings = []

    # Initialise a list of to hold the score for each mapping.
    scores = []

    # Loop over all matches from mol0.
    for x in range(len(matches0)):
        match0 = matches0[x]

        # Loop over all matches from mol1.
        for y in range(len(matches1)):
            match1 = matches1[y]

    ...
```

In this case it looks like both `len(matches0)` and `len(matches1)` are the maximum value of 1000, so the double loop is quite slow.

I'll check what the number of matches is in a typical case to see if I need to set a more sane default value. (I think I did this when choosing it originally, though.) It might be possible to allow the user to specify the upper limit, just in case the search space is large, which seems to be the case here.

**Comment by lohedges** [comment]
I think the issue is largely due to working around the problem with RDKit's uniquify, which removed the best mapping in many cases. For certain ligand pairs this leads to a proliferation of possible substructures, which are later rejected as duplicates by the scoring code. I'm not sure whether it's best to just reduce the default `maxMatches` to say, 100, or to give the user the option to tweak this. (The former would mean that we might not return the best mapping in all cases.)

**Comment by kexul** [comment]
Hi @lohedges, how about using a prematch generated by another tool, for example, the `fkcombu` you suggested [here ](https://github.com/michellab/BioSimSpace/issues/30). 

I used `fkcombu` to get the following MCS, then I passed it as the prematch, the `matchAtoms()` function end in a reasonable time but it warned: `RDKit mapping didn't include prematch. Using Sire MCS.`

```
mcs = {1: 3, 3: 5, 2: 4, 4: 6, 27: 29, 26: 28, 7: 9, 8: 10, 9: 11, 10: 12, 11: 13, 12: 14, 13: 15, 14: 16, 15: 21, 16: 20, 17: 19, 18: 18, 19: 17, 20: 22, 21: 23, 22: 24, 23: 25, 24: 26, 25: 27, 6: 8, 5: 7}
```
I've manually checked the MCS generated by `fkcombu`, it should be right.

**Comment by lohedges** [comment]
That would work too. In this case it's quick since the it doesn't go into the scoring function part since the pre-match isn't found.

I've just added a `max_scoring_matches` option for the `matchAtoms` function. This has a default of 1000, but can be lowered for problematic ligand pairs. In this case, using something like 100 returns a mapping in a reasonable time.

I'll run some more checks then push in a bit.

**Comment by lohedges** [comment]
Pushed.

**Comment by kexul** [comment]
Thank you~
