### ISSUE TITLE
Cannot view more than 3 molecules

### ISSUE THREAD

**Issue by chryswoods** [michellab/BioSimSpace#12]
viewing molecules fails when more than 3 molecules are added to the list

**Comment by lohedges** [comment]
This is very strange. It works fine on my local machine but seems to intermittently occur for people running on the remote server. Will have to think of a way to debug this.

**Comment by lohedges** [comment]
Closing since this appears to be an issue with NGLView itself (or possibly Jupyter). Will re-open if it becomes a persistent problem.
