### ISSUE TITLE
Potential dataset for best practices hydration free energy node

### ISSUE THREAD

**Issue by jmichel80** [michellab/BioSimSpace#13]
The SOMD, GROMACS, CHARMM, AMBER inputs stored here 
https://github.com/halx/relative-solvation-inputs

could be used to test the mapping of 'best practices' protocols for alchemical relative/absolute hydration free energy calculations to various MD codes. 

This would be a good milestone working towards a binding free energy workflow.

tagging @ppxasjsm to bring that up when discussing next steps for free energy workflows.

**Comment by ppxasjsm** [comment]
Is this the input data used in the reproducibility project? And yes this seems like a useful dataset.
