### ISSUE TITLE
How to cite BioSimSpace

### ISSUE THREAD

**Issue by miroslav351** [michellab/BioSimSpace#135]
Hello,

I have mentioned BioSimSpace in a publication I will be submitting soon. As I am seeing that the BioSimSpace paper is under review, what is the suggested way to cite it?

Many thanks.

**Comment by ppxasjsm** [comment]
It looks like it already has a DOI, take a look at the proof here.: https://github.com/openjournals/joss-papers/blob/joss.01831/joss.01831/10.21105.joss.01831.pdf

I would also assume that the review process should be finished fairly soon. 

I hope this helps.

**Comment by miroslav351** [comment]
That's very helpful, just what I needed! Thanks a lot.

**Comment by lohedges** [comment]
Hi there,

Yes, our paper is currently under review. Hopefully the process will be
finished off soon (within a week), after which we'll have a DOI. Once
published, I'll update our website and the GitHub README with citation
instructions.

Hopefully this time frame works for you.

Cheers.

**Comment by lohedges** [comment]
Our paper is now published, [this](https://doi.org/10.21105/joss.01831) is the DOI. Note that there is also a software archive, which has it's [own](https://doi.org/10.5281/zenodo.3551030) DOI. This specifically refers to the 2019.3.0 release of BioSimSpace, which was used in the paper. If you want to cite _any_ version of the software, then you can use [this](https://doi.org/10.5281/zenodo.3551029) DOI instead.

Cheers.

**Comment by miroslav351** [comment]
Thanks Lester, it seems that the paper got published just when I needed!
