### ISSUE TITLE
namespace convention

### ISSUE THREAD

**Issue by jmichel80** [michellab/BioSimSpace#14]
It would be good to discuss conventions for exposing methods. 
For instance why MolWithResName or readMolecules() have been brought to the top level layer of BSS in BioSimSpace/python/BioSimSpace/__init__.py 
This is important to clarify before other developers contribute code to the library.

**Comment by lohedges** [comment]
Definitely. A lot of the top-level namespace functions were added by Christopher for the purposes of demoing in the kickoff week. As you suggest, these should probably be moved to appropriate sub-packages as-and-when they are developed, e.g. maybe `BioSimSpace.IO` for `readMolecules`, which could also wrap around other `Sire.IO` functionality.

**Comment by jmichel80** [comment]
We should think over the coming 2weeks in which namespace the existing API should end up as otherwise there is a risk we will have to update a growing number of scripts to keep them compatible with API changes.

**Comment by lohedges** [comment]
Yes, that's a good point. I imagine that in the early stages it might be necessary for us to modify some scripts in the library if API changes are needed. Perhaps we can develop some kind of linter as things evolve, e.g. to automatically highlight deprecated API calls.

Thanks for all your useful suggestions. Good to have a log of everything in one place.

**Comment by ppxasjsm** [comment]
I agree and sounds very similar to a concern both Lester and I have discussed in the past.

**Comment by chryswoods** [comment]
I agree. The lack of namespaces before was just for demonstration purposes. I've discussed with Lester and we will move things into, e.g. BSS.IO etc.

I also think that an automatic linter would be great if it could be implemented easily.

**Comment by lohedges** [comment]
Closing this for now since we're all aware of the issue and are working towards a consistent, robust API.
