### ISSUE TITLE
Clearer equilibration protocol options.

### ISSUE THREAD

**Issue by lohedges** [michellab/BioSimSpace#15]
At present, `BSS.Protocol.Equilibration` can run equilibration at fixed temperature, or perform heating / cooling by setting the `temperature_start` and `temperature_end` keyword arguments. To run at constant temperature, the user can omit the `temperature_end` argument, or set it to the same value as `temperature_start`.

Perhaps it would be better to have another keyword, `temperature`, that takes precedence over the other two, i.e. a fixed temperature equilibration will be performed if this argument is set (the others can be omitted, or will be ignored if they are set, perhaps with a warning given).

**Comment by chryswoods** [comment]
The two options are:

1. Have another keyword `temperature` that takes precedence over the other two, if set, or
2. Create a new `BSS.Protocol.Heating` that inherits from `BSS.Protocol.Equilibration` and that can be used for heating.

The benefit of 1 is simplicity, but at the cost that some chemists complained at the workshop that heating is not really equilibration, and so we shouldn't have two different temperatures in this protocol.
