### ISSUE TITLE
[FEATURE] Wrapping pdb4amber

### ISSUE THREAD

**Issue by lohedges** [michellab/BioSimSpace#158]
This thread is to discuss the addition of functionality to wrap [pdb4amber](https://github.com/Amber-MD/pdb4amber). This command-line utility is provided as part of the AmberTools suite and can be used to pre-process PDB files so that they are in a format that is compatible with `tLEap`. Some things that it can do:

* Renumbers residues.
* Renames histidine residues (HIS) based on the rules described [here](http://ambermd.org/Questions/HIS.html).
* Renames cysteine residues (CYS). The residue name used by for regular protonated cysteine residues is CYS, for deprotonated (-ve charge) and/or bound to metal atoms it is CYM and for cysteine residues involved in disulphide bridges and other bonds it is CYX.
* Separates out non-Amber approved residues. Allowed residues are given [here](https://github.com/Amber-MD/pdb4amber/blob/master/pdb4amber/residue.py).
* Add's TER information if missing.

In terms of handling the above, there should be no issue using the existing `makeCompatible` functionality within Sire/BioSimSpace. This can match atoms between two molecules based on various criteria, e.g. name, index, coordinates, substructure, or combinations thereof. It is also (relatively) easy to extend the matching rules if necessary.

Things that we don't deal with are:

* The addition of atoms during parameterisation. (The molecule must have the same number of atoms before and after.)
* A single molecule with multiple chains (PDB representation) being returned as multiple parameterised molecules. See [here](https://github.com/michellab/BioSimSpace/issues/93) for a discussion of this issue.

The first one should be easy enough to deal with, i.e. we match all atoms that we can in the original molecule (keeping naming, numbering, etc.), then add the new ones.

The second one is not so easy, and I'd like to know whether this is going to be a common issue with the proposed use case. @tonka-balonka, is there any way you could comment on this?

This is a fundamental difference in the way that molecular system are represented and it would be good to discuss potential solutions. In the [previous issue thread](https://github.com/michellab/BioSimSpace/issues/9) it was suggested that the user could manually split the PDB into its constituent components, parameterise, then recombine. This puts the emphasis on the user, since they (hopefully) know what they're doing and avoids any issues with misinterpreting the data.

Another approach could be to (optionally) split molecules on chains when reading PDBs, or using the connectivity to sub-divide the system. Using the Sire Python API I've not found a way to extract a chain to create a new molecule. (Extracting a chain and calling `.molecule()` returns the original molecule, as does using `remove()` to delete atoms that are not part of the chain from the molecule. Yes, I've made the molecule editable and commited the changes.) I've also tried using the connectivity to do this, but it is painfully slow. (Perhaps there is a fast way to do this that I'm unaware of.)

If none of the above is possible then it would be good to know precisely how the user wants to cross reference things between the original PDB and whatever system/s that is/are obtained from operations that follow. Is this by atom index, residue index, names, etc? (Again, if @tonka-balonka could comment, that would be great.) If it is something like this then we could allow the user to extract atoms/residues by their global index within the system, rather than on a per-molecule basis. I've already added functionality to do this since it's required when constructing PLUMED input files. (I could adapt it to be able to search by passing the original index, that way you could generate a mapping the first time a system is loaded then use that to reference things throughout.)

Cheers.

**Comment by tonka-balonka** [comment]
The expectation on our side is that users start with molecules that went through the prep process in Maestro, so they wouldn't necessarily have missing atoms, but this might not always be the case. As for the chain ID, I will check with our user base, but I'd imagine that the users do want to retain the chain ID. Linking to the original structure I'd personally use would be residue index + residue name + chain ID, as I rarely rely on atom index. However, I will check with the others and get back to you asap.

**Comment by lohedges** [comment]
Just a quick update. I think the persistent reference to chain IDs is the biggest stumbling block here. Having chatted with @chryswoods it appears that it _should_ be possible to combine molecules within Sire, although there is no functionality to do this exposed to Python at present. (There is C++ code to extract parts from a molecule, which could be inverted to combine information from multiple molecules into a single one.) This would allow us to recombine the two plus molecules that are returned from a parameterisation (corresponding to chains in the original molecule) into a single one.

In addition to this problem, we also need to consider how the chain IDs are preserved along a workflow that could involve several BioSimSpace nodes. While the solution above would work within a node, if the combined molecule was written to a format that doesn't use chain IDs then the reconstructed information would be lost. One workaround could be to save a PDB along with any AMBER RST/PRM files so that the information could be recovered. Perhaps we could instead save a _hidden_ mapping file, or reference PDB, that could be read by a node on startup to set up the initial system. If the file was missing (e.g. if it was the first node in a workflow) then whatever system is loaded from file would be used, otherwise we re-map the system as required.

**Comment by jmichel80** [comment]
Could the second option be implemented via a generic metadata file holder, so we can extend this approach to store various other attributes that cannot be preserved in supported file formats ?

**Comment by lohedges** [comment]
That's a good point. I think it's probably best to do something general and extensible since I imagine that this is a problem that we'll come across again.

**Comment by lohedges** [comment]
So, some good news and bad news. First the good news...

We can now parameterise molecules with chains. This is achieve by mapping all properties from the multi-molecule representation returned by tLEaP back into the original molecule, hence preserving the original PDB topology and chain identifiers. This required some tweaks to the `Sire.Mol.ResIdxAtomCoordMatcher` code to allow a `ResIdx` offset to be passed so the examples shown below require the latest devel build of Sire. The major bottleneck was the reconstruction of the _intrascale_ matrix for non-bonded interactions. It is prohibitively slow to build this on-the-fly, but thankfully the `Sire.IO.GroTop` parser can reconstruct it for you assuming all other potential related properties are present in a system. Working from the `feature_pdb4amber` branch we can now do:

```python
# Load the original PDB file. In this representation the system contains
# a single molecule with two chains. We parse with pdb4amber to ensure
# that the file can be parsed with tLEaP.
system = BSS.IO.readPDB("test/io/molecules/1jr5.pdb", pdb4amber=True)

# Parameterise with ff14SB and return the molecule. The system that is
# generated by tLEaP contains two molecules, each corresponding to one
# of the chains in the original system. The properties from the new system
# are mapped back into the existing single-molecule format to preserve
# chain information.
molecule = BSS.Parameters.ff14SB(system[0]).getMolecule()

# Load in the two-molecule tLEaP system.
tLEaP_system = BSS.IO.readMolecules(["test/io/molecules/1jr5.crd",
                                                                  "test/io/molecules/1jr5.top"])
# Now perform single-point energy calculations using the two molecular
# representations.

# Create a single-step minimisation protocol.
protocol = BSS.Protocol.Minimisation(steps=1)

# Create a process for the single molecule representation.
process0 = BSS.Process.Amber(molecule.toSystem(), protoco, work_dir="tmp0")

# Create a process for the multi molecule representation.
process1 = BSS.Process.Amber(tLEaP_system, protocol, work_dir="tmp1")

# Run the processes and wait for them to finish.
process0.start()
process0.wait()
process1.start()
process1.wait()

# Compare bond energies. (In kJ / mol)
nrg0 = process0.getBondEnergy().kj_per_mol().magnitude()
nrg1 = process1.getBondEnergy().kj_per_mol().magnitude()
assert nrg0 == pytest.approx(nrg1, rel=1e-2)

# Compare angle energies. (In kJ / mol)
nrg0 = process0.getAngleEnergy().kj_per_mol().magnitude()
nrg1 = process1.getAngleEnergy().kj_per_mol().magnitude()
assert nrg0 == pytest.approx(nrg1, rel=1e-2)

# Compare dihedral energies. (In kJ / mol)
nrg0 = process0.getDihedralEnergy().kj_per_mol().magnitude()
nrg1 = process1.getDihedralEnergy().kj_per_mol().magnitude()
assert nrg0 == pytest.approx(nrg1, rel=1e-2)
```

Now for the bad news...

Firstly, when using the Sire/BioSimSpace AMBER parsers to write the parameterised single-molecule multi-chain representation to disk, it is split back into a two molecule system. (Which makes the single point agreement above less impressive.) I'm not sure if this a requirement for AMBER, or if it's just something that the parser does (perhaps splitting on connectivity). We could possibly handle this by mapping coordinates back using an approach similar to what I've just done for `_makeCompatibleWith`, although I think this might be impossible to do in a general way. (Imagine dealing with multiple molecules with chains loaded from file, etc.)

```python
# Write the parametrised single-molecule multi-chain system to AMBER format.
BSS.IO.saveMolecules("amber", molecule, ["prm7", "rst7"])

# Read the files back.
amber_system = BSS.IO.readMolecules(["amber,prm7", "amber.rst7"])

# Print the number of molecules in the system.
print(amber_system.nMolecules())
2
```

Secondly, in contrast to what was discussed earlier in the week, saving to GROMACS format does not preserve any chain information. This means that we currently can't preserve chain identifiers in a multi-node workflow.

```python
# Write the parametrised single-molecule multi-chain system to GROMACS format.
BSS.IO.saveMolecules("gromacs", molecule, ["grotop", "gro87"])

# Read the files back.
gromacs_system = BSS.IO.readMolecules(["gromacs,grotop", "gromacs.gro87"])

# Print the number of molecules in the system. We have preserved the single-molecule
# representation.
print(gromacs_system.nMolecules())
1

# Print the number of chains. We have lost the chain information.
print(gromacs_system.nChains())
0
```

Since @chryswoods wrote the AMBER and GROMACS parsers, I'll chat with him to see if these issues can easily be fixed.

**Comment by chryswoods** [comment]
The Amber PRM format is a pain as it doesn't really have a concept of molecules. It just has atoms, and then infers the molecules based on the bonds. The only information that exists that is "molecule" related is `ATOMS_PER_MOLECULE`, which is a list of the number of atoms in each molecule in the file. This list (under the flag `ATOMS_PER_MOLECULE`) does not always exist in the file. If it doesn't exist, then it is rebuilt by scanning the list of bonds, working out how atoms divide into molecules, and then counting up the number of atoms per molecule.

The key code that detects is `ATOMS_PER_MOLECULE` is missing and rebuilds the list [is here](https://github.com/michellab/Sire/blob/5e964bd61729057e10192daa237e94ffd4b2bbd0/corelib/src/libs/SireIO/amberprm.cpp#L999).

My guess is that `ATOMS_PER_MOLECULE` is not being written by AmberPrm. This means it doesn't exist in the file, and so on reading, the bond information is read and so the molecule is split into two again. I can see that there is code to write this data, [e.g. here](https://github.com/michellab/Sire/blob/5e964bd61729057e10192daa237e94ffd4b2bbd0/corelib/src/libs/SireIO/amberprm.cpp#L3279), so I am surprised if this is the case. Could you take a look at the output `amber.prm7` file and see if the data in the `ATOMS_PER_MOLECULE` field is correct?

Regarding GroTop, yes, you're right that the GroTop topology file format doesn't have chain identifiers (and Gro87 is so minimal it also doesn't have them). However, you could write the file to [GroTop, PDB], and the chain information would be preserved. This would lose a little bit of precision from the coordinates (PDBs only hold coords to 3 decimal places). If the precision was important, then you could add some extra functionality to the PDB2 parser to enable it to read and write PDB files with more decimal places. This is a feature of the Gro87 format, and you can see in the Gro87 class how the precision can be set, and also detected at load time [here](https://github.com/michellab/Sire/blob/5e964bd61729057e10192daa237e94ffd4b2bbd0/corelib/src/libs/SireIO/gro87.cpp#L192).

There's also some useful information about gromacs chains [here](http://www.gromacs.org/Documentation_of_outdated_versions/How-tos/Multiple_Chains).

**Comment by lohedges** [comment]
Thanks, that's helpful. Regarding the `ATOMS_PER_MOLECULE` flag: I can't find it in any of the prm7 files, even the one generated by `tLEaP` during parameterisation. This is making me think that it was never an issue with `AmberTools`, rather `Sire.IO.AmberPrm` splitting the molecule based on bonding if that flag is missing. Might have been easier to modify the `AmberPrm` parser rather than making painful `_makeCompatibleWith` modifications. Oh well :-)

If I add the missing information to the prm7 file, then I get the following error from the parser:

```sh
Disagreement over the number of atoms in molecule 1. Looking at bonding implies the number of atoms is 1495, while the file itself claims the number is 2.
```

This makes sense, since the parser doesn't realise that the molecule is actually composed of chains and it is generally a valid check. I think we need to add an option, e.g. `has_chains`, that we can pass to the parser. This would be easy when using `AmberPrm` directly, but a bit more fiddly if people want to use the general `BioSimSpace.IO.readMolecules` function, since we'd need to call the `AmberPrm` parser twice, i.e. `has_chains=true/false`. I'll have a think if there's an easier way of doing it.

**Comment by lohedges** [comment]
Alternatively, we could remove the check above and just rely on the file containing the correct number of atoms. I'll try doing this and see what happens. (I'm not sure what other consequences there might be.)

**Comment by chryswoods** [comment]
You can't remove the flag or else all of the solvent molecules will be merged into the protein. If ATOMS_PER_MOLECULE is not written, then we do have to infer it.

**Comment by chryswoods** [comment]
(or, you can set a flag the can optionally assume the file contains a single molecule if we *know* it contains a single molecule, e.g. as when parameterising using tleap)

**Comment by lohedges** [comment]
Sorry, I wasn't suggesting removing the flag, just the requirement that the number of atoms per molecule (as inferred from bonding) matches what is set with the `ATOMS_PER_MOLECULE` flag. If there is a mismatch, then (as long as there are the correct number of atoms) we assume that the molecule contains multiple chains. As you say, we still need to split solvent molecules. It's simple enough to deal with single molecules with the `makeCompatibleWith` functionality that I've written (although it's not the quickest), it's just more complicated when handling solvated systems loaded from restart files during dynamics, or perhaps files / systems containing multiple molecules that has been combined by a user. In those cases we can't just flag that the file contains a single molecule and we need some logic to work out which molecules (based on bonding) are actually chains. I imagine that this might be complicated to do in a general way.

I'll take a look at the `AmberPrm` code today to see if I can think of a workaround.  It would probably be a whole lot easier if PDBs had reliable bonding information. That way we could just split the loaded PDB file but add chain identifiers to each molecule.

**Comment by lohedges** [comment]
Interestingly, `AmberPrm` only splits when loading a single molecule from file. If I first solvate the system (which uses `gmx solvate` behind the scenes) then, after converting to AMBER format and reading back in, it keeps the protein as a single molecule, even though `ATOMS_PER_MOLECULE` disagrees with what is implied from the bond information. There must be some inconsistency somewhere. I'll try to track it down. (This is good news at least, since we now know that it can retain the single molecule representation.)

This shows what's going on:

```python
import BioSimSpace as BSS

# Load the original PDB representation of the molecule, passing through pdb4amber.
molecule = BSS.IO.readPDB("test/io/molecules/1jr5.pdb", pdb4amber=True)[0]

# This returns the parameterised molecule, mapped back into the two-chain
# single molecule representation of the PDB file.
par_molecule = BSS.Parameters.ff14SB(molecule).getMolecule()

# Print the molecule to show the number of atoms/residues.
print(par_molecule)
<BioSimSpace.Molecule: nAtoms=2990, nResidues=90>

# Write the parametrised single-molecule multi-chain system to AMBER format.
BSS.IO.saveMolecules("amber", par_molecule, ["prm7", "rst7"])

# Read the files back.
amber_system = BSS.IO.readMolecules(["amber.prm7", "amber.rst7"])

# Print the number of molecules in the system. The molecule has been split in two.
print(amber_system.nMolecules())
2

# Print the number of atoms in the first molecule. This is half the number of atoms
# and residues as in the original molecule (which has two chains of the same size).
print(amber_system[0])
<BioSimSpace.Molecule: nAtoms=1495, nResidues=90>

# Now solvate the parameterised system.
solvated = BSS.Solvent.tip3p(molecule=par_molecule, box=3*[10*BSS.Units.Length.nanometer])

# Save the solvated system to AMBER format.
BSS.IO.saveMolecules("solvated", solvated, ["prm7", "rst7"])

# Read the system back in.
amber_system2 = BSS.IO.readMolecules(["solvated.prm7", "solvated.rst7"])

# Print the first molecule. It matches the original representation!
print(amber_system2[0])
<BioSimSpace.Molecule: nAtoms=2990, nResidues=90>

# As a sanity check we save the first molecule from the solvated system to AMBER
# format and read back in. (Same if using solvated or amber_system2.)
BSS.IO.saveMolecules("amber2", solvated[0], ["prm7", "rst7"])
amber_system3 = BSS.IO.readMolecules(["amber2.prm7", "amber2.rst7"])

# Hmmm, it's been split again!
print(amber_system3.nMolecules())
2

print(amber_system3[0])
<BioSimSpace.Molecule: nAtoms=1495, nResidues=90>
```

This is the first line of the `ATOMS_PER_MOLECULE` flag in `solvated.prm7`:

```
%FLAG ATOMS_PER_MOLECULE
%FORMAT(10I8)
    2990       3       3       3       3       3       3       3       3       3
```

The correct number of atoms for the single non-water molecule is written (2990) and is respected on read, even when this disagrees with the bonding. In contrast, the single molecule AMBER files, e.g. `amber.prm7, amber2.prm7`, contain no `ATOMS_PER_MOLECULE` flag. Adding an entry for the single molecule throws the error shown above, i.e.:

```
Disagreement over the number of atoms in molecule 1. Looking at bonding implies the number of atoms is 1495, while the file itself claims the number is 29.
Thrown from FILE: /home/lester/Code/Sire/corelib/src/libs/SireIO/amberprm.cpp, LINE: 679, FUNCTION: void SireIO::AmberPrm::rebuildMolNumToAtomNums()
```

**Comment by lohedges** [comment]
Aaaargh! Flipping Sire file caching! It turns out that adding the `ATOMS_PER_MOLECULE` section to the single molecule files does work, however Sire was reading a cached file, hence the error. I guess it should be simple enough to write this extra information to file in the case of single molecules with chains. This is something that can probably done in BioSImSpace, rather than in the `Sire.IO.AmberPrm` code. This might make all of the `makeCompatibleWith` edits redundant. I'll experiment and write some more tests.

**Comment by lohedges** [comment]
Yep, it was as easy as updating the `BioSimSpace.IO.readMolecules` function to add a `ATOMS_PER_MOLECULE` flag if `PRM7` format is selected and the system contains a single molecule with more than one chain. (Perhaps we need to be more flexible than this, but it should be okay for current use cases.) I'll leave in my now completely pointless `makeCompatibleWith` edits in case the are useful for something in future, e.g. if we come across a single molecule file where this record is missing.

I can't believe that this was effectively a three line edit, rather than almost 500 lines and a lot of head scratching.

**Comment by lohedges** [comment]
Just a quick note on retaining information, e.g. chain identifiers, between nodes....

I've now made `BioSimSpace._SireWrappers.Molecule.makeCompatibleWith` public, which allows the user to make a molecule loaded from, e.g., AMBER/GROMACS format files compatible with a reference topology loaded from a PDB file. I've also added a `BioSimSpace._SireWappers.System.updateMolecule` function that allows the user to replace the molecule in a system, i.e. update with the one that has chain identifiers.

A workflow could look like:

```python
import BioSimSpace as BSS

# Load the original PDB representation of the molecule, passing through pdb4amber.
molecule = BSS.IO.readPDB("test/io/molecules/1jr5.pdb", pdb4amber=True)[0]

# This returns the parameterised molecule, mapped back into the two-chain
# single molecule representation of the PDB file.
par_molecule = BSS.Parameters.ff14SB(molecule).getMolecule()

# Now solvate the parameterised system.
solvated = BSS.Solvent.tip3p(molecule=par_molecule, box=3*[10*BSS.Units.Length.nanometer])

# Save the solvated system to AMBER format.
BSS.IO.saveMolecules("solvated", solvated, ["prm7", "rst7"])

# Read the system back in.
amber_system = BSS.IO.readMolecules(["solvated.prm7", "solvated.rst7"])

# How many chains does the first (only) molecule have?
print(amber_system[0]))
0

# Map the amber_molecule to the topology of the original PDB.
molecule.makeCompatibleWith(amber_system[0])

# Replace the first molecule in the AMBER system.
amber_system.updateMolecule(0, molecule)

# How many chains does it have now?
print(amber_system[0]))
2
```

(Obviously the re-loading, making compatible, and updating stages would be done in a second node.)

**Comment by jmichel80** [comment]
excellent work @lohedges  !

**Comment by lohedges** [comment]
Actually, it appears that my single-point energy unit test is now no longer working. Bah. Will need to debug and fix.

**Comment by lohedges** [comment]
It turns out that there was an issue for the original `makeCompatibleWith` function that handled comparisons with single molecules, rather than with systems of molecules. This is now fixed and the energies agree as before. I'm not yet sure if this has caused problems with any existing calculations with molecules parameterised via BioSimSpace. (The existing tests were okay, this only caused issues with the multi-chain molecule that was tested here.)
