### ISSUE TITLE
[FEATURE] Funnel metadynamics

### ISSUE THREAD

**Issue by lohedges** [michellab/BioSimSpace#163]
This thread is to discuss the implementation of "funnel" metadynamics within BioSimSpace. Ultimately we hope to support AMBER/GROMACS via PLUMED, as well as a custom OpenMM implementation using the OpenMM python API. (We bundle OpenMM along with Sire so can always fall back on OpenMM if other MD engines aren't installed.)

A rough list of things that are needed:

- [x] Add an OpenMM process driver, i.e. `BioSimSpace.Process.OpenMM`. This will be able to write Python scripts to support most of our existing protocols, and can take a custom script (or list of strings) as an argument to support more complicated protocols, such as funnel metadynamics. This looks easy enough to add within the existing framework and will also provide a useful fallback MD driver along with SOMD. (But with access to more thermodynamic information than SOMD.)

- [x] Add `BioSimSpace.Metadynamics.CollectiveVariable.Funnel` class. This requires a few tweaks to the existing framework since the funnel collective variable (CV) has two components, whereas all existing CVs have one. (Should just need to add an attribute that stores how many components the CV has, then update in all appropriate places.) The class should set up the required projection vector using the approach used in `funnel_maker`. This is currently done using `MDAnalysis`, but it should be possible to do natively within BioSImSpace. 

- [x] Implement code to write PLUMED file for GROMACS/AMBER.

- [x] Write custom Python script for OpenMM.

- [x] Translate OpenMM output into the format that is expected by the PLUMED analysis tools. That way we can use a single set of analysis routines to, e.g., compute free energy surfaces. Will need to check what information is accessible from OpenMM, perhaps supporting limited functionality if certain information cannot easily be obtained or reconstructed.

**Comment by dlukauskis** [comment]
Hi Lester, I've open an issue [github/openmm#2933](https://github.com/openmm/openmm/issues/2933) to address No. 4 on your list. I hope what I wrote makes sense. 

I've been working on HelloFunnel test set and I'm nearly done with simulations for a simple guest-host system, will send the results over when its ready.

**Comment by lohedges** [comment]
That sounds great, thanks for that.
