### ISSUE TITLE
[FEATURE] Parameterisation in the presence of structural ions

### ISSUE THREAD

**Issue by lohedges** [michellab/BioSimSpace#168]
BioSimSpace is written assuming that parameterisation and solvation can be decoupled. We already know that this isn't possible using `tLEaP`, e.g. [here](#20), since you must also parameterise when solvating. When solvating after parameterising we would then need to re-parameterise the molecules in the system. This would be computationally expensive and require detection of the force field with which each molecule was parameterised the first time. Because of this, we use `gmx solvate` for our solvation.

A collaborator has a protein containing a Zn ion that they would like to parameterise. This fails with our parameterisation setup since `tLEaP` requires that such a system is solvated at the same time, i.e. you can only do this with a combined parameterisation and solvatation.

I'm not sure how to we get around this? Do we detect the presence of ions when parameterising a protein, then parameterise with solvent and throw away the solvent on read? Would this cause issues if we were then to solvate again with `gmx solvate`. Even if this were possible it would involve duplicating functionality and wasting CPU. Perhaps you don't need to fully solvate the system, only make the solvent forcefield parameters visible to `tLEaP` when parameterising with ions?

**Comment by jmichel80** [comment]
The CPU aspects do not worry me in practice if it's just a matter of looking up precomputed parameters. It's not elegant but if needed you could go through similar operations twice for the sake of handling the input. 
Whether gmx solvate handles well a system that already contains ions needs testing, but I suspect this isn't going to be a massive issue. An issue may be that you have to deal with structural ions (those that are present in the PDB to begin with) and ions added at a later stage to achieve a desired ionic strength (typically Na+ or Cl-)

**Comment by lohedges** [comment]
I'm hoping that it's just a case of detecting strucural ions in the PDB and adding the solvent parameters to the `tLEaP` script, rather than actually needing to solvate with `tLEaP`. Just running into so other issues so can't test at the moment. Whether this then causes further issues with `gmx genion` is unknown, but I think that would be okay.

**Comment by lohedges** [comment]
Just had a discussion with collaborators. It seems that you can just include the ion parameter file, which is pulled in by the solvent parameters. The only issue is that we would need to be able to choose the water model that is used for the ion parameters, then make sure that we check for consistency when actually solvatiing with `gmx solvate`.

Perhaps there is not too much difference between the ion parameters for different water models? If not, then it might be possible to just go with a "best guess" that works for the majority of the time, while allowing the user to specify the exact ion model if required. I don't have much experience or intuition here, so let me know your thoughts.

**Comment by jmichel80** [comment]
I suggest to go with the 'recommended' default parameter set from AmberTools 20 with TIP3P (see page 55 of https://ambermd.org/doc12/Amber20.pdf)

**Comment by lohedges** [comment]
Just to note that if you add ion parameters, then `tLEaP` returns the ions as separate molecules, even if they are structural. I'm hoping that this will still work using my multi-molecule `makeCompatibleWith`, but I'm not sure. To be safe, it looks like we will need to solvate, i.e. include solvent parameters, not just the ions, then remove any water molecules. This is because a water `leaprc` file includes many ion `frcmod` files and they are slightly different between versions. It seems safer to just include the top-level file and let that deal with the subsequent includes. (It also looks like it's the water file that actually defines the atom types, whereas the ion files just contain the actual parameters.)

**Comment by lohedges** [comment]
It's the Lennard-Jones parameters that vary between water models, e.g.:

```python
# spce
m._sire_object.property("LJ")
AtomProperty<SireMM::LJParameter>( [ LJ( sigma = 2.27357 A, epsilon = 0.00354287 kcal mol-1 ) ] )

# tip3p
m._sire_object.property("LJ")
AtomProperty<SireMM::LJParameter>( [ LJ( sigma = 2.26466 A, epsilon = 0.00330286 kcal mol-1 ) ] )
```

I would _hope_ that these would be consistent with those used by `gmx solvate` for the same water model. I guess I could try to store the LJ parameters from AMBER/GROMACS for all models then swap them during the solvation stage? If this is a valid approach then we shouldn't need to care about what water model is used during the parameterisation, i.e. you just source something so that the ion atom types are found. Prior to solvation we then swap the LJ terms for any ions with those used by the appropriate GROMACS water model. (I guess it could be a pain to do this for all possible ions.)

**Comment by lohedges** [comment]
I've implemented an initial workaround for this issue. The user can now pass the option `water_model` to any of the parameterisation functions that, when supported, will load the appropriate water model for the required ion parameters. If working within a BioSimSpace node, this could be one of the options returned by `BioSimSpace.Solvent.waterModels()`.

I've also added checks into the `BioSimSpace.Solvent` package to warn the user if a water model used to parameterise the ions doesn't match the water model chosen to solvate. This allows you to do things in a self-consistent way when doing a full parameterisation --> solvation pipleine within BioSimSpace. However, this won't help us with systems loaded from file, or if we decouple the steps into separate nodes. For the latter, we'd need a way of passing the additional water model information between the nodes.

I'm currently working on the [feature_structural_ions](https://github.com/michellab/BioSimSpace/tree/feature_structural_ions) branch, but can merge across to `devel` for testing purposes.

**Comment by lohedges** [comment]
Here is an example node that reads a PDB, parameterises with a chosen force field, then writes the output to AMBER format files. An (optional) water model is used to obtain parameters for any ions, and is set to a default of `tip3p`:

```python
import BioSimSpace as BSS

# Initialise the node.
node = BSS.Gateway.Node("Load a PDB file, parameterise, and save to AMBER format.")

# Set metadata.
node.addAuthor(name="Lester Hedges", email="lester.hedges@bristol.ac.uk", affiliation="University of Bristol")
node.setLicense("GPLv3")

# Add inputs.
node.addInput("pdb",
              BSS.Gateway.File(help="A PDB input file."))
node.addInput("pdb4amber",
               BSS.Gateway.Boolean(help="Whether to pre-process the PDB using pdb4amber.",
                                   default=False))
node.addInput("force_field",
              BSS.Gateway.String(help="The force field to parameterise with.",
              allowed=BSS.Parameters.forceFields()))
node.addInput("water_model",
              BSS.Gateway.String(help="The water model used to parameterise any structural ions.",
                                 allowed=BSS.Solvent.waterModels(),
                                 default="tip3p"))

# Add outputs.
node.addOutput("parameterised", BSS.Gateway.FileSet(help="The parameterised molecular system."))

# Load the PDB file and extract the molecule.
molecule = BSS.IO.readPDB(node.getInput("pdb"), pdb4amber=node.getInput("pdb4amber"))[0]

# Parameterise the molecule.
molecule = BSS.Parameters.parameterise(molecule,
                                       node.getInput("force_field"),
                                       water_model=node.getInput("water_model")).getMolecule()


# Write the molecular system to AMBER format files.
node.setOutput("parameterised",
    BSS.IO.saveMolecules("parameterised", molecule.toSystem(), ["prm7", "rst7"]))

# Validate the node.
node.validate()
```

(This assumes a sane single molecule PDB file.)

You can then parameterise by doing, e.g.:

```bash
python parameterise.py --pdb 4V2Y_A_fixed.pdb --force_field ff14SB
```

If you want to change the water model used for the ion parameters, then do, e.g.:

```bash
python parameterise.py --pdb 4V2Y_A_fixed.pdb --force_field ff14SB --water_model spce
```

This uses the [following](https://github.com/michellab/BioSimSpace/files/5886981/4V2Y_A_fixed.pdb.txt) PDB, modified from [this](http://ambermd.org/tutorials/advanced/tutorial20/12_6.htm) tutorial. (I modified the `TER` record to conform to the PDB standard.)
