### ISSUE TITLE
Atom naming for backbone restraints

### ISSUE THREAD

**Issue by lohedges** [michellab/BioSimSpace#177]
The `restrain_backbone` option in `BioSimSpace.Protocol.Equilibration` currently relies on exact atom naming to be able to locate the atoms to restrain. If the user doesn't pass a system with a standard naming convention, then this will not work. How should we handle this? Possible options:

* Match names against a template. If none of the names are present, then raise an exception.
* Allow the user to pass a list of backbone atom names.
* Allow the user to pass a list of backbone atom indices.
* Something else.

**Comment by jmichel80** [comment]
1>2>3 with templates just covering proteins and nucleic acids with default names used with PDB ff  or Amber style ? Raise explicit message to user if other names detected.  Won’t cover everything but hard to cover thoroughly.

**Comment by lohedges** [comment]
Closing since this is dealt with in the new restraint handling code.
