### ISSUE TITLE
BioSimSpace install script

### ISSUE THREAD

**Issue by jmichel80** [michellab/BioSimSpace#18]
Hi @lohedges , 

I tried to install BSS from the install.sh script

julien@ubuntu:~/software/devel/BioSimSpace$ ./install.sh --branch=devel
Where would you like to install BioSimSpace? [/home/julien/BioSimSpace.app]: 
Installing into directory: /home/julien/BioSimSpace.app
  --> Downloading Sire binary
chmod: cannot access '/home/julien/BioSimSpace.app/sire.run': No such file or directory
  --> Installing Sire application
rm: cannot remove '/home/julien/BioSimSpace.app/sire.run': No such file or directory
  --> Downloading BioSimSpace
unzip:  cannot find or open devel.zip, devel.zip.zip or devel.zip.ZIP.
unzip:  cannot find or open tests.zip, tests.zip.zip or tests.zip.ZIP.
rm: cannot remove 'devel.zip': No such file or directory
rm: cannot remove 'tests.zip': No such file or directory
./install.sh: line 154: cd: BioSimSpace-devel/python: No such file or directory

Not sure why....I am downloading the sire binary now and will try to install BSS manually.

**Comment by lohedges** [comment]
Strange. It should only require basic command-line utilities that come as standard on the Linux and macOS systems on which I've tested? Does your Ubuntu box not come with curl? In any case, I should put it some more checks to ensure that the required utilities are available and catch errors when things go wrong.

**Comment by lohedges** [comment]
From a quick look, it looks like curl isn't installed by default on your version of Ubuntu. I'll add a check for this in the installer.

A `sudo apt-get install curl` should hopefully fix your problem.

**Comment by jmichel80** [comment]
weird curl is on the command line but does nothing....I used wget. 

julien@ubuntu:/tmp$ /usr/bin/curl http://siremol.org/largefiles/sire_releases/download.php?name=sire_2018_1_1_linux.run
julien@ubuntu:/tmp$ curl http://siremol.org/largefiles/sire_releases/download.php?name=sire_2018_1_1_linux.run
julien@ubuntu:/tmp$ 
julien@ubuntu:/tmp$ wget http://siremol.org/largefiles/sire_releases/download.php?name=sire_2018_1_1_linux.run
--2018-05-14 13:48:35--  http://siremol.org/largefiles/sire_releases/download.php?name=sire_2018_1_1_linux.run
Resolving siremol.org (siremol.org)... 5.153.219.41, 5.153.219.41
Connecting to siremol.org (siremol.org)|5.153.219.41|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://sire.blob.core.windows.net/releases/sire_2018_1_1_linux.run [following]
--2018-05-14 13:48:35--  https://sire.blob.core.windows.net/releases/sire_2018_1_1_linux.run
Resolving sire.blob.core.windows.net (sire.blob.core.windows.net)... 52.239.141.36
Connecting to sire.blob.core.windows.net (sire.blob.core.windows.net)|52.239.141.36|:443... connected.
HTTP request sent, awaiting response... ^C

julien@ubuntu:/tmp$ sudo apt-get install curl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.47.0-1ubuntu2.7).
curl set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 40 not upgraded.
