### ISSUE TITLE
More conda issues

### ISSUE THREAD

**Issue by lohedges** [michellab/BioSimSpace#185]
Despite having succesfully run three times this morning, the [Linux build](https://dev.azure.com/michellab/BioSimSpace/_build/results?buildId=1123&view=logs&j=9bec107b-9b63-5845-480f-545c2906090a&t=f7245a56-5f80-5a7b-a0f9-b9351d5f2cac) of BioSimSpace is now failing with the following error:

```
ImportError: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /home/sireuser/sire.app/lib/python3.7/site-packages/MDAnalysis/lib/../../../../libgomp.so.1)
```

[MDAnalysis](https://anaconda.org/conda-forge/mdanalysis) was last updated 8 days ago, so that can't be the problem. I can only assume that they haven't pinned the version of glibc, which has then been updated by one of the other dependencies. Now to work out what package _has_ updated since this morning. The stuff of nightmares. Sigh.

**Comment by lohedges** [comment]
> Now to work out what package has updated since this morning.

No top-level dependencies have updated, so it must be a dependency of a dependency, or a dependency of a dependency of a dependency, or a ...

Giving up for the day.

**Comment by ppxasjsm** [comment]
I had an issue with biopython earlier today. Not sure if this is related.

**Comment by lohedges** [comment]
And now it [works again](https://dev.azure.com/michellab/BioSimSpace/_build/results?buildId=1126&view=logs&j=d7f7f03a-4c7a-5512-c777-d009571f6dc9). Why do I even waste my time on this stuff?
