### ISSUE TITLE
BSS.BOX

### ISSUE THREAD

**Issue by aniketsh** [michellab/BioSimSpace#187]
OS: Mac
version 2020.1.0
AttributeError: module 'BioSimSpace' has no attribute 'Box'

while trying to put the molecule in the triclinic box, I get the following error, after looking into ~/anaconda3/pkgs/biosimspace-2020.1.0-py37h1de35cc_0/lib/python3.7/site-packages/BioSimSpace
there is no "Box" folder, am I missing something with installation?

**Comment by ppxasjsm** [comment]
You are using the 2020.1 release which was built in July. Triclinic Box support was only added in September. You'll have to work with the dev version.

**Comment by aniketsh** [comment]
Thanks, that worked! :)
