### ISSUE TITLE
BSS.FreeEnergy.Binding and ignore_warnings with GROMACS

### ISSUE THREAD

**Issue by aniketsh** [michellab/BioSimSpace#188]
While setting up a free energy system as following:

protocol = BSS.Protocol.FreeEnergy(timestep=4*BSS.Units.Time.femtosecond,
                       runtime=4*BSS.Units.Time.nanosecond,
                       num_lam=11)
BSS.FreeEnergy.Binding(protocol=protocol,work_dir="a-b",system=solvated,engine='GROMACS')

Output: Use 'ignore_warnings' to ignore warnings.

Question: How can I ignore this warning, as BSS.Protocol.FreeEnergy has no "ignore_warnings' attribute?

**Comment by lohedges** [comment]
Hello, thanks for reporting this. We have recently made some changes that means that GROMACS warnings are no longer silently ignored since it lead to some unexpected behaviour. Instead, the warnings can be printed and the user can then choose to ignore them by passing `ignore_warnings=True` to the `BioSimSpace.Process.Gromacs` constructor. At present, this option isn't available in any of the higher-level drivers, such as those in `BioSimSpace.FreeEnergy`.

I'll figure out the best way of passing the option through and let you know when I have a solution. In the mean time you could manually edit the following file (the exact path will depend upon your installation method):

```
~/sire.app/lib/python3.7/site-packages/BioSimSpace/Process/_gromacs.py
```

or

```
~/.conda/envs/ENV_NAME/lib/python3.7/site-packages/BioSimSpace/Process/_gromacs.py
```

You would need to change the constructor on lines 60-61 to:

```python
    def __init__(self, system, protocol, exe=None, name="gromacs",
            work_dir=None, seed=None, property_map={}, ignore_warnings=True, show_errors=True):
```

Cheers.

**Comment by aniketsh** [comment]
Thank you for this answer. I have another question related to this. In the current scenario, I am getting this warning due to the following: 
"State B has a non-zero charge of 0.002".

However, when I write out merged.grotop, and topol.grotop (for protein and merged ligand) and sum the columns (all of the digits after decimal), the sum is 0. I also repeated this for protein, and it also has an integer charge, which is neutralized by adding ions. I can compile files and send them across if needed. The ligand topology files were generated independently with openff, and not from BSS.

**Comment by lohedges** [comment]
Hi again, I'd be happy to look if you upload the files.

What does BioSimSpace report if you load the ligands in BioSimSpace, then print their charge using the `.charge()` method on the molecule? There is also a private `._fixCharge()` method which will adjust the charges such that the molecule is integer charged. Do you see the same thing if you parameterise within BioSimSpace? (BioSimSpace now supports parameterisation with OpenFF natively.)

From the error message, it looks like the charge in the lambda = 1 end state is incorrect.  Could you extract the molecules from each end state within BioSimSpace and check their charge independently?

```python
mol0 = merged._toRegularMolecule()
print(mol0.charge())

mol1 = merged._toRegularMolecule(is_lambda1=True)
print(mol1.charge())
```

If both charges are zero, then it seems like the merge is okay and something most have gone awry when writing the GROMACS topology.

**Comment by aniketsh** [comment]
Thank you for your answer. Here is the output! I am attaching ligand files as well.

mol0 = merged._toRegularMolecule()
print(mol0.charge())
-9.9329e-07 |e|

mol1 = merged._toRegularMolecule(is_lambda1=True)
print(mol1.charge())
0.0030 |e| 

I am attaching output from merged file - > merged.grotop, where charge sum is 0 in both states. 

On the generating openff topology natively, I tried to provide ligand pdb file as an input (is there a way to give mol2 or sdf?, this is what I use to generate topology independently) and encounter the following error:

ParameterisationError: Parameterisation failed! Last error: 'Unable to make OFFMol from RDMol: Unable to make OFFMol from RDMol: RDMol has unspecified stereochemistry. RDMol name: Undefined chiral centers are:

 - Atom C (index 1)
 - Atom C (index 2)
 - Atom C (index 3)
 - Atom C (index 5)
 - Atom C (index 6)
 - Atom C (index 7)
 - Atom C (index 12)
 - Atom C (index 16)
'

[files.zip](https://github.com/michellab/BioSimSpace/files/5981163/files.zip)

**Comment by lohedges** [comment]
Here's the section relating to the merged molecule in the topology file:

```
[ atoms ]
;   nr   type0  resnr residue  atom   cgnr    charge0        mass0   type1    charge1        mass1
     1      C1      1     LIG     C      1  -0.070000    12.010780      C1  -0.073000    12.010780
     2      C1      1     LIG     C      2  -0.089500    10.018727      C1  -0.089000    10.018727
     3      C1      1     LIG     C      3  -0.136500    10.018727      C1  -0.135500    10.018727
     4      C1      1     LIG     C      4   0.705200    12.010780      C1   0.519200    10.018727
     5      C1      1     LIG     C      5  -0.109000    10.018727      C1  -0.107000    10.018727
     6      C1      1     LIG     C      6  -0.136500    10.018727      C1  -0.135500    10.018727
     7      C1      1     LIG     C      7  -0.089500    10.018727      C1  -0.089000    10.018727
     8      C1      1     LIG     C      8   0.418500    12.010780      C1   0.393500    12.010780
     9      N1      1     LIG     N      9  -0.637000    14.006720      N1  -0.623000    14.006720
    10      N1      1     LIG     N     10  -0.393300    14.006720      N1  -0.354300    14.006720
    11      C1      1     LIG     C     11   0.118700    12.010780      C1   0.115700    12.010780
    12      N1      1     LIG     N     12  -0.850800    10.022614      H3   0.081800     3.000000
    13      C1      1     LIG     C     13   0.469600    12.010780      C1   0.465600    12.010780
    14      C2      1     LIG     C     14  -0.157400     6.034621      C2  -0.158400     6.034621
    15      N1      1     LIG     N     15  -0.628100    14.006720      N1  -0.574100    14.006720
    16      N1      1     LIG     N     16   0.025200    14.006720      N1   0.014200    14.006720
    17      C1      1     LIG     C     17  -0.324300    10.018727      C1  -0.310300    10.018727
    18      H1      1     LIG     H     18   0.146000     3.000000      H1   0.145000     3.000000
    19      H1      1     LIG     H     19   0.138000     3.000000      H1   0.139000     3.000000
    20      H1      1     LIG     H     20   0.136000     3.000000      H1   0.137000     3.000000
    21      H1      1     LIG     H     21   0.138000     3.000000      H1   0.139000     3.000000
    22      H1      1     LIG     H     22   0.146000     3.000000      H1   0.145000     3.000000
    23      H2      1     LIG     H     23   0.413800     3.000000   H2_du   0.000000     3.000000
    24      H2      1     LIG     H     24   0.413800     3.000000   H2_du   0.000000     3.000000
    25      H3      1     LIG     H     25   0.063033     3.000000      H2   0.064033     3.000000
    26      H3      1     LIG     H     26   0.063033     3.000000      H2   0.064033     3.000000
    27      H3      1     LIG     H     27   0.063033     3.000000      H2   0.064033     3.000000
    28      H1      1     LIG     H     28   0.164000     3.000000      H1   0.165000     3.000000
```

Saving this to file `tmp.txt`, we can do:

_lambda = 0 state_
```sh
awk 'NR>2{s+=$7}END{print s}' tmp.txt
-1e-06
```

_lambda = 1 state_
```sh
awk 'NR>2{s+=$10}END{print s}' tmp.txt
0.002999
```

Hence the charge in the lambda = 1 state agrees with what BioSimSpace is reporting, and is non-zero.

Could you try calling `_fixCharge()` on ligand2 before peforming the merge, since that should zero the net charge for you.

```python
ligand1._fixCharge()
```

We don't have an SDF parser, I'm afraid, so bare molecules should be in PDB or Mol2 format. We do go via an intermediate SDF when doing OpenFF parameterisation (using RDKit), but our starting point is a PDB or Mol2 so it must be properly formatted for the parameterisation to work.

**Comment by aniketsh** [comment]
Thanks, that worked! 

Regarding correct mol2 file format, is generated by antechamber ok? 
Can you please include an example?

**Comment by lohedges** [comment]
The output of Antechamber should be okay. I think the main issue is that your carbon atoms don't have unique names (they are all named `C`) and the residues are unlabelled (`UNL`) so tools like `pdb4amber` (which we wrap) have no templates to match to. Once the naming is correct, I imagine that things will work.

**Comment by lohedges** [comment]
Hell again. I've now updated the code so that the `ignore_warnings` and `show_errors` keyword arguments are exposed the the `BioSimSpace.FreeEnergy` objects. These are ignored when the engine isn't GROMACS, so you can safely use them in a script and it will still work interoperably.

Feel free to close the issue when you're happy with the solution.

Cheers.

**Comment by aniketsh** [comment]
Thanks @lohedges. 

On the non-integer charge issue generated by openff, I have reported it, and they are aware of it and working on solution. In case you want to follow the issue its at:
https://github.com/openforcefield/openff-toolkit/issues/456

**Comment by aniketsh** [comment]
Thanks @lohedges. 

On the non-integer charge issue generated by openff, I have reported it, and they are aware of it and working on solution. In case you want to follow the issue its at:
https://github.com/openforcefield/openff-toolkit/issues/456

**Comment by lohedges** [comment]
Thanks for keeping me in the loop regarding the OpenFF issue. This is something that we could possibly handle internally with our parameterisation engine, i.e. running `._fixCharge()` on the paremeterised molecule before returning it. However, as indicated in the linked issue thread, it's not an easy thing to do in general so it's best to leave this to the tools themselves. (`._fixCharge()` is much less clever than the approach that they suggest and is only used internally to make any formal charges integral before passing to `antechamber` prior to paremeterisation with `gaff/gaff2`.)
