### ISSUE TITLE
Conda saga continues

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#189]
I am trying to get a reliable installation that combines:

- biosimsoace
- https://github.com/oess/openmm_orion

Conda does not seem to be able to do this and I get this lovely output file and I have no idea what to do with it. 

[conda_dump.txt](https://github.com/michellab/BioSimSpace/files/6035214/conda_dump.txt)

**Comment by lohedges** [comment]
This works for me:

```
conda create -n bss-orion python=3.7
conda activate bss-orion
conda install -c openeye/label/Orion -c conda-forge -c omnia -c michellab/label/dev oeommtools biosimspace=2020.1.0 
``` 

If I don't specify the BioSimSpace version, then I end up with 2019.3.0.

**Comment by ppxasjsm** [comment]
I suppose I tried to use the dev version....fascinating.

**Comment by lohedges** [comment]
I am using the dev version of BioSimSpace, or do you mean the dev version of OEOMMTools?

Your issue might have been installing in two stages, i.e. first `oeommtools`, then `biosimspace`, or the other way around. The way in which conda resolves dependencies means that you won't end up with the same environment depending on the order of installation. If you install _all_ packages in one go, then it resolves _all_ dependencies at the same time.

**Comment by lohedges** [comment]
Did this work for you? If so, I'll close the issue.

Hopefully things like this will be far easier once we have a conda-forge package. (Fingers crossed!)
