### ISSUE TITLE
Reading in Solvated system in amber format doesn't work

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#195]
This may not be an issue anymore, but I am trying to read in a solvated system in AMBER file format, but get an error that it can't read the system, but nothing more specific. 

```python


In [7]: mol = BSS.IO.readMolecules(['../../productions/ejm_31/solvated_complex.inpcrd', '../../productions/ejm_31/solvated_complex.prmtop'])
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-7-afdfa163464c> in <module>
----> 1 mol = BSS.IO.readMolecules(['../../productions/ejm_31/solvated_complex.inpcrd', '../../productions/ejm_31/solvated_complex.prmtop'])

~/miniconda3/envs/BSS/lib/python3.7/site-packages/BioSimSpace/IO/_io.py in readMolecules(files, property_map)
    308                     raise IOError(msg) from e
    309                 else:
--> 310                     raise IOError(msg) from None
    311 
    312     return _System(system)

```

BSS version may be too old?

```
In [12]: BSS.__version__
Out[12]: '2020.1.0'
```

File are:
[solvated_complex.top.txt](https://github.com/michellab/BioSimSpace/files/6143851/solvated_complex.top.txt)
[solvated_complex.crd.txt](https://github.com/michellab/BioSimSpace/files/6143853/solvated_complex.crd.txt)

**Comment by lohedges** [comment]
Yes, works fine for me with the most recent versions of Sire and BioSimSpace:

```python
import BioSimSpace as BSS
BSS.__version__
'2020.1.0+237.g07579c3'

import Sire
Sire.__version__
'2021.1.0'

system = BSS.IO.readMolecules(BSS.IO.glob("solvated_complex.*"))
print(system)
<BioSimSpace.System: nMolecules=13103>
```

Without knowing anything else, I imagine that whatever issue has been resolved with one of the recent fixes to the `Sire.IO.AmberPrm` parser.

To get full error messages from Sire, remember to turn on _verbose_ error messages:

```python
import BioSimSpace as BSS
BSS.setVerbose(True)
```

(By default the messages are gobbled and only summarised when the information is meaningful.)
