### ISSUE TITLE
Problems with amber and gfortran

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#2]
Process hangs, when amber is not executed correctly in the amber.py demo script. 

The issue I had was that I didn't have gfortran installed and therefore my amber installation was actually broken after an update of OSX.

An error file was written when executing `amber.py`, but BioSimSpace did not register the error. 
Output:
```
/Users/toni_brain/Software/FESetup1.1/amber14/bin/sander -O -i minimise.amber -p
 minimise.prm7 -c minimise.rst7 -o stdout -r minimise.restart.crd -inf minimise.nrg
dyld: Library not loaded: /opt/local/lib/libgcc/libgfortran.3.dylib
  Referenced from: /Users/toni_brain/Software/FESetup1.1/amber14/bin/sander
  Reason: image not found
Abort trap: 6```

The problem was solved by installing gfortran and the amber16

**Comment by lohedges** [comment]
From speaking with Charlie, this seems to be a problem with AMBER, i.e. it doesn't always abort or return a useful error code when it fails. In their work, they seem to use some kind of wrapper around AMBER that checks to see if something has gone wrong, e.g. no output being written for a while, then aborting the process if needed.

I'll look into this. It would be very annoying for the code to just hang with no info given to the user.
