### ISSUE TITLE
workshops/advanced/alchemistry/alchemical_setup.ipynb gives error at 5.4 solvation step

### ISSUE THREAD

**Issue by fengmudong** [michellab/BioSimSpace#200]
# Expected Behavior

I expect the line `solvated = BSS.Solvent.tip3p(molecule=system, box=3*[60*BSS.Units.Length.angstrom])` to produce a solvated system containing lysozyme and two merged ligands, without popping error 

# Current Behavior

Executing the code cell gives error msg below:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-28-8589c3c96819> in <module>
      1 # Solvate in a 60 angstrom box of TIP3P water.
----> 2 solvated = BSS.Solvent.tip3p(molecule=system, box=3*[60*BSS.Units.Length.angstrom])
      3 
      4 # Create the free energy protocol.
      5 protocol = BSS.Protocol.FreeEnergy(runtime=4*BSS.Units.Time.nanosecond, num_lam=9)

/opt/conda/lib/python3.7/site-packages/BioSimSpace/Solvent/_solvent.py in tip3p(molecule, box, angles, shell, ion_conc, is_neutral, work_dir, property_map)
    281     # Validate arguments.
    282     molecule, box, angles, shell, work_dir, property_map = \
--> 283         _validate_input("tip3p", molecule, box, angles, shell, ion_conc, is_neutral, work_dir, property_map)
    284 
    285     # Create the solvated system.

/opt/conda/lib/python3.7/site-packages/BioSimSpace/Solvent/_solvent.py in _validate_input(model, molecule, box, angles, shell, ion_conc, is_neutral, work_dir, property_map)
    489                     break
    490         else:
--> 491             ion_water_model = molecule._ion_water_model
    492             if ion_water_model is not None and ion_water_model != model:
    493                 _warnings.warn( "Mismatch with water model used to parameterise "

AttributeError: 'Molecules' object has no attribute '_ion_water_model'
```

# Failure Information

## Steps to Reproduce

Open the notebook server `notebook.biosimspace.org`, open the notebook `workshops/advanced/alchemistry/alchemical_setup.ipynb`, execute all cells in order, skip the Exercise cells of solvation free energy part.

## Context

I also conda installed biosimspace (Build py37h9bf148f_266) on my local Linux computer, and downloaded the notebook `alchemical_setup.ipynb` to execute locally, which gave the same error.

**Comment by lohedges** [comment]
Thanks very much for reporting, and for the clear explanation of the problem. This should now be fixed in the latest commit. A new conda package will be available shortly and I'll update the notebook server tomorrow.

**Comment by fengmudong** [comment]
Thank you for the quick fix. I just installed the newest version via conda, and the error is gone!

**Comment by lohedges** [comment]
Just to say that the notebook server is now updated so it should work there too. We also have a script that can be run on the server (from a terminal) in order to update to the latest version of BioSimSpace, `update_biosimspace`. If you run this before opening any notebooks then it will clone the latest version of the code from GitHub so that things are up-to-date. This can be helpful when you come across issues since the notebook server isn't re-built that often. (We use this script to update the server if we find bugs/issues when running a workshop.) Note that the changes aren't persistent, so you'd need to run it every time you restarted your server instance.
