### ISSUE TITLE
Ring breaking 

### ISSUE THREAD

**Issue by kexul** [michellab/BioSimSpace#208]
Dear BioSimSpace develpoers, I have two molecules used in free energy perturbation job:
![image](https://user-images.githubusercontent.com/5920217/115892504-cb1bbe80-a489-11eb-9c96-aab443ea03be.png)

when I use `BioSimSpace.Align.Merge` with those molecules, It complains:
```
The merge has opened/closed a ring. To allow this perturbation, set the 'allow_ring_breaking' option to 'True'.
```
1. I think that's because the `H` atom was mapped to `C` atom in the ring, am I right? 
2. I would like to drop this `H` to `C` mapping in the result of `matchAtoms`'s result, which I think would solve the ring breaking problem. But I'm not familiar with Sire's API, can anyone provide some example code to find the `HC` pair in the `matchAtoms` result?

Appreciated!

Here is the code and molecule files I've used. 
```
import BioSimSpace as _BSS
mola = _BSS.IO.readMolecules(['inter1_AC.inpcrd', 'inter1_AC.prmtop']).getMolecule(0)
molb = _BSS.IO.readMolecules(['mol411_AC.inpcrd','mol411_AC.prmtop']).getMolecule(0)

match = _BSS.Align.matchAtoms(molb, mola)

new_mol = _BSS.Align.rmsdAlign(molb, mola, mapping=match)
_BSS.Align.merge(new_mol, mola, mapping=match)
```

[git.zip](https://github.com/michellab/BioSimSpace/files/6366430/git.zip)

**Comment by jmichel80** [comment]
You can check the contents of match to verify 1). If that is not the case try using the prematch keyword option when calling matchAtoms to enforce mapping of the H to the thiazole carbon atom. 
See https://biosimspace.org/api/generated/BioSimSpace.Align.matchAtoms.html#BioSimSpace.Align.matchAtoms

This should allow you to grow the entire thiazole from the H atom, possibly via passing allow_ring_breaking at the merge step.

**Comment by lohedges** [comment]
Since the match returns the indices of the atoms in each molecule you can use them to get the atom objects, e.g.

```python
for idx0, idx1 in matches.items():
    print(mola.getAtoms()[idx0], molb.getAtoms()[idx1])
```

This should print their names so you can work out which pair in the match corresponds to the atoms you're interested in.

**Comment by kexul** [comment]
Thanks for your quick reply! @jmichel80 @lohedges . 
I've check the content of `match`  using above code and found it very confusing: The `O` atom was mapped to `H` atom, is that reasonable? Here is my result: 
```
<BioSimSpace.Atom: name='C12', molecule=2 index=16> <BioSimSpace.Atom: name='C1', molecule=1 index=1>
<BioSimSpace.Atom: name='C13', molecule=2 index=17> <BioSimSpace.Atom: name='C', molecule=1 index=0>
<BioSimSpace.Atom: name='H6', molecule=2 index=33> <BioSimSpace.Atom: name='H', molecule=1 index=21>
<BioSimSpace.Atom: name='H7', molecule=2 index=34> <BioSimSpace.Atom: name='H1', molecule=1 index=22>
<BioSimSpace.Atom: name='H8', molecule=2 index=35> <BioSimSpace.Atom: name='H2', molecule=1 index=23>
<BioSimSpace.Atom: name='C14', molecule=2 index=18> <BioSimSpace.Atom: name='O', molecule=1 index=2>
<BioSimSpace.Atom: name='N3', molecule=2 index=19> <BioSimSpace.Atom: name='H4', molecule=1 index=25>
<BioSimSpace.Atom: name='C11', molecule=2 index=15> <BioSimSpace.Atom: name='C2', molecule=1 index=3>
<BioSimSpace.Atom: name='C10', molecule=2 index=14> <BioSimSpace.Atom: name='C3', molecule=1 index=4>
<BioSimSpace.Atom: name='C9', molecule=2 index=13> <BioSimSpace.Atom: name='C4', molecule=1 index=5>
<BioSimSpace.Atom: name='C8', molecule=2 index=12> <BioSimSpace.Atom: name='C5', molecule=1 index=6>
<BioSimSpace.Atom: name='C7', molecule=2 index=10> <BioSimSpace.Atom: name='C6', molecule=1 index=7>
<BioSimSpace.Atom: name='C6', molecule=2 index=9> <BioSimSpace.Atom: name='C7', molecule=1 index=8>
<BioSimSpace.Atom: name='C5', molecule=2 index=8> <BioSimSpace.Atom: name='C8', molecule=1 index=9>
<BioSimSpace.Atom: name='C17', molecule=2 index=24> <BioSimSpace.Atom: name='C15', molecule=1 index=20>
<BioSimSpace.Atom: name='H12', molecule=2 index=39> <BioSimSpace.Atom: name='H13', molecule=1 index=34>
<BioSimSpace.Atom: name='C4', molecule=2 index=7> <BioSimSpace.Atom: name='C9', molecule=1 index=10>
<BioSimSpace.Atom: name='C3', molecule=2 index=6> <BioSimSpace.Atom: name='C10', molecule=1 index=11>
<BioSimSpace.Atom: name='N2', molecule=2 index=5> <BioSimSpace.Atom: name='N', molecule=1 index=12>
<BioSimSpace.Atom: name='C2', molecule=2 index=4> <BioSimSpace.Atom: name='C11', molecule=1 index=13>
<BioSimSpace.Atom: name='C1', molecule=2 index=3> <BioSimSpace.Atom: name='C14', molecule=1 index=19>
<BioSimSpace.Atom: name='N1', molecule=2 index=2> <BioSimSpace.Atom: name='N3', molecule=1 index=18>
<BioSimSpace.Atom: name='C', molecule=2 index=1> <BioSimSpace.Atom: name='C13', molecule=1 index=16>
<BioSimSpace.Atom: name='N4', molecule=2 index=26> <BioSimSpace.Atom: name='N1', molecule=1 index=15>
<BioSimSpace.Atom: name='C18', molecule=2 index=25> <BioSimSpace.Atom: name='C12', molecule=1 index=14>
<BioSimSpace.Atom: name='H13', molecule=2 index=40> <BioSimSpace.Atom: name='H10', molecule=1 index=31>
<BioSimSpace.Atom: name='N', molecule=2 index=0> <BioSimSpace.Atom: name='N2', molecule=1 index=17>
<BioSimSpace.Atom: name='H', molecule=2 index=27> <BioSimSpace.Atom: name='H12', molecule=1 index=33>
<BioSimSpace.Atom: name='H1', molecule=2 index=28> <BioSimSpace.Atom: name='H11', molecule=1 index=32>
<BioSimSpace.Atom: name='H2', molecule=2 index=29> <BioSimSpace.Atom: name='H9', molecule=1 index=30>
<BioSimSpace.Atom: name='H3', molecule=2 index=30> <BioSimSpace.Atom: name='H8', molecule=1 index=29>
<BioSimSpace.Atom: name='H4', molecule=2 index=31> <BioSimSpace.Atom: name='H7', molecule=1 index=28>
<BioSimSpace.Atom: name='F', molecule=2 index=11> <BioSimSpace.Atom: name='H6', molecule=1 index=27>
<BioSimSpace.Atom: name='H5', molecule=2 index=32> <BioSimSpace.Atom: name='H5', molecule=1 index=26>
<BioSimSpace.Atom: name='O', molecule=2 index=23> <BioSimSpace.Atom: name='H3', molecule=1 index=24>
```

**Comment by jmichel80** [comment]
What mapping do you get if you set sanitize=True when calling matchAtoms ?

**Comment by kexul** [comment]
> What mapping do you get if you set sanitize=True when calling matchAtoms ?

Hi @jmichel80 , It seems like that I need to update my BioSimSpace, my current version of `2020.1.0` from conda did not have the `sanitize` parameter.

**Comment by kexul** [comment]
Thanks for your suggestion @jmichel80 , It's really helpful! when set `sanitize=True`, I can get `O` to `O` mapping now. Besides, now the H atom I've mentioned was excluded in the match, which is exactly what I want.

**Comment by lohedges** [comment]
No problem, thanks for reporting. The `sanitize` option is passed to RDKit when loading molecules prior to performing the MCS mapping. Depending on the original input, it can add some help recover some useful stereo-chemistry which improves the accuracy of the MCS. Unfortunately it's not fail-safe so we disable it by default.

Cheers.
