### ISSUE TITLE
Visualization of merged molecule. 

### ISSUE THREAD

**Issue by kexul** [michellab/BioSimSpace#209]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated whether the molecule generated by `BioSimSpace.Align.merge` is correct. That is: 
        1. Is each atom mapping correctly?
        2. Which atoms were perturbated? Were they perturbated as expected? 

**Describe the solution you'd like**
I hope there will be a function that generate an image or an interactive jupyter widget where the initial state and end state are showed together, with the atoms changed during the perturbation highlighted. 

**Describe alternatives you've considered**
Here is my current solution: I saved the merged molecule to `gro` and `top` file. Open the `gro` file by `pymol`, label atoms by `atom name` . Then check the `top` file, find out which atoms would transform during perturbation. 
In the following case, the place pointed by the red arrow should have an `C` atom appear during the perturbation. In fact, all the benzene ring should appear during the perturbation. 
 
![image](https://user-images.githubusercontent.com/5920217/115988212-24e7ca00-a5eb-11eb-99c7-926c5f1e17e5.png)

**Comment by lohedges** [comment]
Thanks for your question. Yes, I agree that it would be great to be able to easily visualise the merged molecule since it would help the user quickly spot potential issues prior to simulation. I had been thinking about using some of the `rdkit.ChemDraw` functionality, like in some of the examples from their cookbook [here](https://www.rdkit.org/docs/Cookbook.html). Essentially I was thinking of drawing side-by-side depictions of each molecule with the MCS highlighted. I don't think it will be too hard so I'll add it to my to-do list.

Cheers.

**Comment by jmichel80** [comment]
@JenkeScheen has written some code to do so as part of his current research. See e.g. 

https://github.com/michellab/dd_networkgen/blob/master/bss_mapping_checks.ipynb

**Comment by JenkeScheen** [comment]
I think this issue might interplay well with #190, potentially.

**Comment by kexul** [comment]
Hi @jmichel80 , thanks for the link, it quite interesting to show the mapping by `atom number`. 

I've come up with similar idea with `rdkit.Chem.Draw`, but with `atom color` to show the atom pairs. Here it is:

![image](https://user-images.githubusercontent.com/5920217/116074244-07d2fa00-a6c4-11eb-9614-b5e76f505f04.png)

I've seen some posters elsewhere, I think this one best describes what's in my mind. 
![image](https://user-images.githubusercontent.com/5920217/116075048-0fdf6980-a6c5-11eb-8e3c-15a5590c5713.png)

Thanks for adding this to your to-do list @lohedges !

**Comment by JenkeScheen** [comment]
I vaguely remember @ppxasjsm having generated such a mapping figure before, the one with the mapping wires. Or perhaps she just showed me one that she found online, in that case sorry for @-ing you..

**Comment by lohedges** [comment]
I've made a first pass at this using some ideas from the [RDkit cookbook](https://www.rdkit.org/docs/Cookbook.html). You can now do the following:

![draw_mapping](https://user-images.githubusercontent.com/648557/116098611-1fe65180-a6a3-11eb-93bc-39788b4d47cf.png)

At present I've made it so you can look at the molecules individually, but it could be combined into a single image with a bit more work.

**Comment by jmichel80** [comment]
Neat ! I wonder if this could make its way eventually in the FEP pipeline @JenkeScheen is writing. At the moment we generate mappings automatically on a cluster after equilibration. It could make sense to generate those per ligand using non-equilibrated inputs, therefore giving the chance to a user to interactivelly adjust mappings before running a bunch of simulations downstream.  If we have generated the mappings once, there should be a way to save them and re-use them once parameterised/equilibrated molecules are available.  

Might be a bit tight to implement this for the coming workshop, but could be done as refinement afterwards.

**Comment by kexul** [comment]
Thank for your works! It's very impressive!

After some digging, I found another nice tool to visualize molecule [xyz2graph](https://github.com/zotko/xyz2graph), it creates an interactive widget to show the molecule.

I've forked it https://github.com/kexul/xyz2graph and create a molecule pair view with some modifications, here it is:  

https://nbviewer.jupyter.org/github/kexul/xyz2graph/blob/33894c15ff6d0e039febc68faf53f067bcce3599/show_mol.ipynb

![newplot](https://user-images.githubusercontent.com/5920217/116214071-f13aaa80-a778-11eb-9643-3b568bbcf64b.png)

**Comment by lohedges** [comment]
Thanks, that looks like a nice tool. While we don't support `xyz` at present the format is so basic that it would be simple to write some temporary files for the purposes of making the plot. It's a shame that this package isn't available via `conda-forge` as we won't be able to support it. (It's dependencies are, though.)

**Comment by JenkeScheen** [comment]
So I finally found out where I'd seen that mapping method before - it's implemented in Flare! When selecting an edge in a perturbation network you can view a 3D rotatable object with the mapping:
![image](https://user-images.githubusercontent.com/43140137/116372154-0dcff480-a804-11eb-85a6-f1f6a497587c.png)

**Comment by lohedges** [comment]
Haha. Closer to home than we thought!
