### ISSUE TITLE
Atom mapping

### ISSUE THREAD

**Issue by kexul** [michellab/BioSimSpace#210]
Hi, I got two molecules:
![image](https://user-images.githubusercontent.com/5920217/117005594-033cc000-ad1a-11eb-8140-1ea679d49f47.png)

I think the `O` atom should match `O` atom. But when I use `matchAtoms()`, It matches `O` atom to `C` atom.  I got the same result when I set `sanitize=True`. 

Here is the code and files I used: 
```
mola = _BSS.IO.readMolecules('mol1.pdb').getMolecule(0)
molb = _BSS.IO.readMolecules('mol2.pdb').getMolecule(0)

match = _BSS.Align.matchAtoms(mola, molb)
for idx0, idx1 in match.items():
    print(mola.getAtoms()[idx0], molb.getAtoms()[idx1])
```
[molecule_files.zip](https://github.com/michellab/BioSimSpace/files/6421161/molecule_files.zip)

Here is part of the mapping result: 
```
<BioSimSpace.Atom: name='C1', molecule=1 index=1> <BioSimSpace.Atom: name='C12', molecule=2 index=15>
<BioSimSpace.Atom: name='C', molecule=1 index=0> <BioSimSpace.Atom: name='C14', molecule=2 index=17>
<BioSimSpace.Atom: name='H', molecule=1 index=21> <BioSimSpace.Atom: name='H10', molecule=2 index=32>
<BioSimSpace.Atom: name='H1', molecule=1 index=22> <BioSimSpace.Atom: name='H11', molecule=2 index=33>
<BioSimSpace.Atom: name='H2', molecule=1 index=23> <BioSimSpace.Atom: name='H12', molecule=2 index=34>
<BioSimSpace.Atom: name='O', molecule=1 index=2> <BioSimSpace.Atom: name='C13', molecule=2 index=16>
<BioSimSpace.Atom: name='H4', molecule=1 index=25> <BioSimSpace.Atom: name='H9', molecule=2 index=31>
<BioSimSpace.Atom: name='C2', molecule=1 index=3> <BioSimSpace.Atom: name='C11', molecule=2 index=14>
<BioSimSpace.Atom: name='C3', molecule=1 index=4> <BioSimSpace.Atom: name='C10', molecule=2 index=13>
<BioSimSpace.Atom: name='C4', molecule=1 index=5> <BioSimSpace.Atom: name='C9', molecule=2 index=12>
```

**Comment by jmichel80** [comment]
Hi @kexul ,
The structure of molecule2 is distorted around the perturbed site. This causes atom mismatch during the RMSD alignment. 

Compare the screenshots below
![pic](https://user-images.githubusercontent.com/11722212/117034592-610ddf80-acfb-11eb-8a51-ed021df2fe9c.jpg)

After cleaning up the internal geometry of mol2 (see attached pdb) I get the expected output

```
<BioSimSpace.Atom: name='C', molecule=1 index=0> <BioSimSpace.Atom: name='C', molecule=2 index=0>
<BioSimSpace.Atom: name='C1', molecule=1 index=1> <BioSimSpace.Atom: name='C1', molecule=2 index=1>
<BioSimSpace.Atom: name='O', molecule=1 index=2> <BioSimSpace.Atom: name='O', molecule=2 index=2>
<BioSimSpace.Atom: name='H4', molecule=1 index=25> <BioSimSpace.Atom: name='H4', molecule=2 index=25>
<BioSimSpace.Atom: name='C2', molecule=1 index=3> <BioSimSpace.Atom: name='C2', molecule=2 index=3>
<BioSimSpace.Atom: name='C3', molecule=1 index=4> <BioSimSpace.Atom: name='C3', molecule=2 index=4>
<BioSimSpace.Atom: name='C4', molecule=1 index=5> <BioSimSpace.Atom: name='C4', molecule=2 index=5>
<BioSimSpace.Atom: name='C5', molecule=1 index=6> <BioSimSpace.Atom: name='C5', molecule=2 index=6>
<BioSimSpace.Atom: name='C6', molecule=1 index=7> <BioSimSpace.Atom: name='C6', molecule=2 index=7>
<BioSimSpace.Atom: name='C7', molecule=1 index=8> <BioSimSpace.Atom: name='C7', molecule=2 index=8>
<BioSimSpace.Atom: name='C8', molecule=1 index=9> <BioSimSpace.Atom: name='C8', molecule=2 index=9>
<BioSimSpace.Atom: name='C15', molecule=1 index=20> <BioSimSpace.Atom: name='C15', molecule=2 index=20>
<BioSimSpace.Atom: name='H13', molecule=1 index=34> <BioSimSpace.Atom: name='H13', molecule=2 index=34>
```
[mol2fix.zip](https://github.com/michellab/BioSimSpace/files/6422457/mol2fix.zip)

**Comment by kexul** [comment]
Thanks so much for your help! @jmichel80

**Comment by kexul** [comment]
Hi @jmichel80 , would you mind elaborate more about how to fix the molecule? I tried adjust the atom position and get a similar structure like yours, but still get a `O` to `C` mapping. 

In the following picture, the left `mol2` was adjusted by myself, the right `mol2f2` was fixed by you. 
![image](https://user-images.githubusercontent.com/5920217/117106555-a214fb00-adb2-11eb-8adc-89943d083d92.png)

Here is the `pdb` file. 
[mol2.zip](https://github.com/michellab/BioSimSpace/files/6425434/mol2.zip)

**Comment by jmichel80** [comment]
Match atoms compute a maximum common substructure to work out mappings. THe MCSS calculation ignores atom types, so there are many solutions with an MCSS of the same size that include O->C or O -> O mappings. The solutions are sorted by RMSD between the molecules after rigid body alignment, the top scored solution was presumably the one with the O closest to O in my case and O to C in yours. 

You can return say 100 matches from matchAtoms and RMSD scores to check if that is the case. 
You can also try the rmsd_flex_align option that may help in some cases.  You can also enforce mapping between O and O with the prematch keyword option. 

See

https://biosimspace.org/api/generated/BioSimSpace.Align.matchAtoms.html#BioSimSpace.Align.matchAtoms

and 

https://github.com/michellab/BioSimSpace/blob/devel/python/BioSimSpace/Align/_align.py

A well thought procedure to generate 3D coordinates before generating mappings is usually sufficient, though I am sure there will be occasional edge cases.

**Comment by kexul** [comment]
Hi @jmichel80 , thanks for your suggestions!

> You can return say 100 matches from matchAtoms and RMSD scores to check if that is the case.

In my experiment, I could not find any O->O mapping in the matching results. 
Here is the code I've used: 
```
mola = _BSS.IO.readMolecules('mol1.pdb').getMolecule(0)
molb = _BSS.IO.readMolecules('mol2.pdb').getMolecule(0)

matches = _BSS.Align.matchAtoms(mola, molb, matches=1000)
# check the idx of O in mola and molb, here is 2 and 3.
for match in matches:
    for idx0, idx1 in match.items():
        print(mola.getAtoms()[idx0], molb.getAtoms()[idx1])
    break
for match in matches:
    for idx0, idx1 in match.items():
        if idx0 == 2 and idx1 == 3:
            print('OK')
```

> You can also try the rmsd_flex_align option that may help in some cases. 

It did not help either, since there were no mapping in the matches. 

> You can also enforce mapping between O and O with the prematch keyword option.

This time I could find an O -> O mapping in the matches. When I step into the `matchAtom()` function, it says rdkit fails to generate a mapping that includes the prematch and using mcs routine from Sire.
