### ISSUE TITLE
BSS unable to detect GROMACS on cluster

### ISSUE THREAD

**Issue by JenkeScheen** [michellab/BioSimSpace#215]
I'm having an issue when trying to setup a GROMACS FEP work_dir on a SLURM cluster, where BSS is unable to find GROMACS. Running `import BioSimSpace as BSS` triggers the intended warning:
```
.. UserWarning: BioSimSpace.IO: Please install GROMACS (http://www.gromacs.org) for GROMACS topology file support ..
```

 And calling `BSS.FreeEnergy.Solvation(system_bound, protocol, engine="GROMACS", work_dir="GROMACS")` of course returns:
```
Traceback (most recent call last):
...
  File "/export/users/jscheen/biosimspace.app/lib/python3.7/site-packages/BioSimSpace-2020.1.0+475.g7582c84-py3.7.egg/BioSimSpace/Process/_gromacs.py", line 761, in _generate_binary_run_file
    raise RuntimeError(exception_string)
RuntimeError: Unable to generate GROMACS binary run input file.
```
With our cluster setup I load GROMACS with `module load gromacs/19.1` at which point everything _should_ be found (e.g., the 'gmx' executable is set, etc) and `$PATH` contains
```
..:/export/users/common/Gromacs19.1/bin
```
... however after loading the gmx module BSS returns the same warning+error. I tried combining with sourcing the GMXRC but nothing seems to change this behaviour.

Is there anything else you would suggest I try? I'm not sure I recall having tested GMX through BSS before so I might be missing a step here. I'm on a recent devel install (through binary): `2020.1.0+475.g7582c84`

**Comment by lohedges** [comment]
Is the name of the executable definitely `gmx`? We currently only search for `gmx` or `gmx_mpi`, but have come across some weird namings on certain clusters. We also support the use of a `GROMACSHOME` environment variable, equivalent to `AMBERHOME`. In your case you could set this to `export/users/common/Gromacs19.1`.

If you load BioSimSpace interactively, could you see what is set for `_gmx_exe`, i.e.

```python
import BioSimSpace as BSS
BSS._gmx_exe
```

If GROMACS wasn't found, this should be `None`.

Just to check, are you loading the GROMACS module then activating the BioSImSpace conda environment? If so, it might be possible that the `PATH` is getting mangled, or overwritten.

**Comment by lohedges** [comment]
(Sorry, just saw that you are installing through the binary.)

**Comment by lohedges** [comment]
Just to note, you should see a `_MissingSoftwareError` if you try to solvate without GROMACS, rather than an error from `gmx grompp`. It looks like it might be finding something for `_gmx_exe`, but it's not working.

**Comment by lohedges** [comment]
Also, the first warning that you see, i.e.:

```
.. UserWarning: BioSimSpace.IO: Please install GROMACS (http://www.gromacs.org) for GROMACS topology file support ..
```

Comes from checking that the `BSS._gromacs_path` environment variable has been set. This is actually extracted from running `gmx` and parsing the output, i.e:

```
...
GROMACS:      gmx, version 2019.6
Executable:   /usr/local/gromacs/bin/gmx
Data prefix:  /usr/local/gromacs
Working dir:  /home/lester/Code/BioSimSpace
```

We set `_gromacs_path` to the "Data prefix".

This is pointing to `_gmx_exe` being detected, but not actually working properly. What happens if you just run `gmx` from the command-line? Do you see the normal help message? I'm wondering whether something has been updated on the cluster so that `gmx` is no longer working, e.g. perhaps it needs to be rebuilt.

**Comment by JenkeScheen** [comment]
ah! looks like there are two separate issues. BSS not 'finding' GROMACS had to do with the fact that was trying to load a gromacs module that was compiled against a CUDA version that was uninstalled recently, running `gmx` turns out to just return:
```
gmx: error while loading shared libraries: libcufft.so.9.2: cannot open shared object file: No such file or directory
``` 
(which I guess could be worth catching?)

Regardless, trying to setup the FEP directory (with pretty standard TYK2 inputs) triggers that `RuntimeError`. Looking at the gmx exception now to see if there's anything of interest there..

**Comment by lohedges** [comment]
Thanks. It's been hard to catch errors from `gmx` since the error codes aren't consistent and default output changes from version to version. Perhaps I can just grep the output for something simple like "GROMACS", which should always be present.

You can pass `show_errors=True` to your `FreeEnergy` constructor to get BioSimSpace to print the `grompp` errors for you. Sometimes it might just be a warning, e.g. a charged system, which you can ignore with `ignore_warnings=True`.

**Comment by JenkeScheen** [comment]
looks like a deprecation issue:
```
.... (normal GMX header)
of the License, or (at your option) any later version.

GROMACS:      gmx grompp, version 2020.4
Executable:   /export/users/common/Gromacs20.4/bin/gmx
Data prefix:  /export/users/common/Gromacs20.4
Working dir:  /export/users/jscheen/projects/BSS_TUT/execution_model
Command line:
  gmx grompp -f /export/users/jscheen/projects/BSS_TUT/execution_model/outputs/GROMACS/ejm_45~ejm_31/vacuum/lambda_0.0000/gromacs.mdp -po /export/users/jscheen/projects/BSS_TUT/execution_model/outputs/GROMACS/ejm_45~ejm_31/vacuum/lambda_0.0000/gromacs.out.mdp -c /export/users/jscheen/projects/BSS_TUT/execution_model/outputs/GROMACS/ejm_45~ejm_31/vacuum/lambda_0.0000/gromacs.gro -p /export/users/jscheen/projects/BSS_TUT/execution_model/outputs/GROMACS/ejm_45~ejm_31/vacuum/lambda_0.0000/gromacs.top -r /export/users/jscheen/projects/BSS_TUT/execution_model/outputs/GROMACS/ejm_45~ejm_31/vacuum/lambda_0.0000/gromacs.gro -o /export/users/jscheen/projects/BSS_TUT/execution_model/outputs/GROMACS/ejm_45~ejm_31/vacuum/lambda_0.0000/gromacs.tpr


-------------------------------------------------------
Program:     gmx grompp, version 2020.4
Source file: src/gromacs/gmxpreprocess/readir.cpp (line 288)

Fatal error:
The group cutoff scheme has been removed since GROMACS 2020. Please use the
Verlet cutoff scheme.

For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors
-------------------------------------------------------
```
this is with loading gromacs 20.4.

**Comment by lohedges** [comment]
Thanks. Previously I needed to use `cutoff-scheme = group` when running in vacuum since `curoff-scheme = Verlet` didn't work with `pbc = no`. I'll try to figure out what I need to change.

This sounds like we will now need to detect the GROMACS version and set the config file appropriately.

**Comment by lohedges** [comment]
Actually, Verlet does work. I'm not sure why I needed to use `group`. I'll try changing it and see what happens.

**Comment by lohedges** [comment]
No, it doesn't. (Made the change in the wrong place.) It gives this error:

```
'gmx grompp' reported the following errors:
ERROR 1 [file /home/lester/Code/BioSimSpace/demo/tmp/gromacs.mdp]:
  With Verlet lists only full pbc or pbc=xy with walls is supported
  ERROR 2 [file /home/lester/Code/BioSimSpace/demo/tmp/gromacs.mdp]:
  With Verlet lists nstlist should be larger than 0
```

Annoyingly we will now need to create a large periodic box for vacuum systems and use that. See [here](https://gromacs.bioexcel.eu/t/minimization-in-vacuum-without-pbc/110) details.

**Comment by lohedges** [comment]
I quickly switched to using `cutoff-scheme = Verlet` by using the approach in [this](https://www.sciencedirect.com/science/article/pii/S1046202317304644?via=ihub) paper, i.e. simulating in a near infinite (999.9 nm) periodic box. This should fix your issue and still works with GROMACS versions prior to 2020.

**Comment by JenkeScheen** [comment]
Thanks @lohedges, it seems like the config change fixed the issue. However, now I get a `RunTimeError` when trying to run `BSS.Solvent.solvate()`; could this be related? If it's not immediately obvious I can provide more details of the input. Exception:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/projects/BSS_TUT/execution_model/scripts/BSSligprep.py in <module>
    113         box, angles = BSS.Box.cubic(max(box_sizes))
    114         lig_p_solvated = BSS.Solvent.solvate(solvent_query, molecule=lig_p,
--> 115                                box=box, angles=angles)
    116 
    117         print("Solvating ligand + protein.")

~/biosimspace.app/lib/python3.7/site-packages/BioSimSpace-2020.1.0+481.g6416dc6-py3.7.egg/BioSimSpace/Solvent/_solvent.py in solvate(model, molecule, box, angles, shell, ion_conc, is_neutral, work_dir, property_map)
    115             raise ValueError("Supported water models are: %s" % waterModels())
    116 
--> 117     return _model_dict[model](molecule, box, angles, shell, ion_conc, is_neutral, work_dir, property_map)
    118 
    119 def spc(molecule=None, box=None, angles=3*[_Angle(90, "degrees")],

~/biosimspace.app/lib/python3.7/site-packages/BioSimSpace-2020.1.0+481.g6416dc6-py3.7.egg/BioSimSpace/Solvent/_solvent.py in tip3p(molecule, box, angles, shell, ion_conc, is_neutral, work_dir, property_map)
    286     # Create the solvated system.
    287     return _solvate(molecule, box, angles, shell, "tip3p", 3, ion_conc,
--> 288             is_neutral, work_dir=work_dir, property_map=property_map)
    289 
    290 def tip4p(molecule=None, box=None, angles=3*[_Angle(90, "degrees")],

~/biosimspace.app/lib/python3.7/site-packages/BioSimSpace-2020.1.0+481.g6416dc6-py3.7.egg/BioSimSpace/Solvent/_solvent.py in _solvate(molecule, box, angles, shell, model, num_point, ion_conc, is_neutral, work_dir, property_map)
    709         # the expected output was generated.
    710         if not _os.path.isfile("box.gro"):
--> 711             raise RuntimeError("'gmx editconf failed to generate required box! " +
    712                                "Check your lattice vectors and angles.")
    713 

RuntimeError: 'gmx editconf failed to generate required box! Check your lattice vectors and angles.
Thu Jun 10 07:35:20 UTC 2021
```

**Comment by JenkeScheen** [comment]
closing this as the above `RunTimeError` was due to GROMACS installation issues on our side.
