### ISSUE TITLE
Load Biosimspace system for free energy calculation 

### ISSUE THREAD

**Issue by kexul** [michellab/BioSimSpace#216]
**Is your feature request related to a problem? Please describe.**
I'd like to load a biosimspace system saved as gromacs file format and perform free energy calculation with it. here is the code I used: 
```
gro_file = 'complex.gro'
top_file = 'complex.top'

system = BSS.IO.readMolecules([gro_file, top_file])
protocol = BSS.Protocol.FreeEnergy()
BSS.FreeEnergy.Binding( system, protocol, engine="SOMD", work_dir='test_case')
```
Biosimspace complained: 
```
ValueError: The system must contain a single perturbable molecule! Use the 'BioSimSpace.Align' 
package to map and merge molecules.
```

**Describe the solution you'd like**
The  `BioSimSpace.IO.fileFormats()` shows: 
```
['Gro87', 'GroTop', 'MOL2', 'PDB', 'PRM7', 'PSF', 'RST', 'RST7']
```
Could one of these formats restore the perturbation information? 
If not, It would be better to have some special file format which could restore all the information of the system object.

**Comment by kexul** [comment]
I've tried `pickle` but it complained: 
```
RuntimeError: Pickling of "Sire.System._System.System" instances is not enabled 
(http://www.boost.org/libs/python/doc/v2/pickle.html)
```

**Comment by lohedges** [comment]
Hi, there. We currently don't support reading files containing perturbable molecules, I'm afraid. This is something that we'd like to add in future.

As you have found, it also isn't easy to pickle some of the underlying objects that the BioSimSpace System and Molecule are built on top of.

At present, if you need to break things into separate scripts / workflows components then you need to reconstruct the merged system.

**Comment by lohedges** [comment]
I've just thought of an easy way to do this by writing the two end states to GroTop separately, then re-loading and combining. This would also serve as a useful test of our GROMACS FEP topology writer.

Not sure if I'll have time to try this today, but shouldn't take too long.

**Comment by kexul** [comment]
Thanks so much! Looking forward to see that.

**Comment by kexul** [comment]
Hi @lohedges , Is the free energy calculation ready for use now?  I've used the following code, some files was generated but no simulation was running, No warning and no error was reported. 
```
protocol = _BSS.Protocol.FreeEnergy()
sys = _BSS.Solvent.tip3p(sys, box=3*[5*_BSS.Units.Length.nanometer], work_dir='test_case')
fep = _BSS.FreeEnergy.Solvation(sys, protocol, engine='SOMD', work_dir='test_case')
fep.run()
```
![image](https://user-images.githubusercontent.com/5920217/123972255-456a4100-d9ed-11eb-87fe-100e978c93ab.png)

Could I run simulation from the folder without reconstruct the `BSS.FreeEnergy` object?

**Comment by lohedges** [comment]
Does the program just exit immediately after doing `fep.run()`? This _should_ run all of the processes for you in serial. However, it's not the most efficient way of doing things and is only set-up to work on the GPU. We normally use BioSimSpace to generate the FEP input, then distribute the individual simulation legs across an HPC resource using some appropriate scripts.

Ss you suggest, you can simply navigate to the individual folders and run each one individually. For SOMD, which it looks like you are using here, you can run each leg with:

```
somd-freenrg -C somd.cfg -t somd.prm7 -c somd.rst7 -m somd.pert -p CUDA
```

Note that this runs on the GPU using appropriate CUDA drivers. If you want to use the CPU (which will be slow) then replace `CUDA` with `CPU`, first removing the `gpu =` section from the `somd.cfg` file.

**Comment by kexul** [comment]
> Does the program just exit immediately after doing fep.run()? 

Yes! The program just exit immediately. I tried step into the code and confirm there were two processes(leg0 and leg1) in _process_runner, but it did not run as expected. 

> somd-freenrg -C somd.cfg -t somd.prm7 -c somd.rst7 -m somd.pert -p CUDA

Thank your so much, now the simulation is running.

**Comment by lohedges** [comment]
> Yes! The program just exit immediately. I tried step into the code and confirm there were two processes(leg0 and leg1) in _process_runner, but it did not run as expected.

That's strange. If you're able to share inputs and a script then I could take a look when I get a chance. The `fep._runner.processes()` should return a list containing process handles for all of the individual simulation legs, i.e. the length of the list should be the number of simulations from leg0 plus leg1. Although not recommended, calling `fep.run()` should run them serially, waiting for each to finish before moving on the next.

Glad to hear that manually running things is working, though.

**Comment by lohedges** [comment]
Looking again, it might be managing the whole thing in a background thread, so you might not see any output initially.

**Comment by kexul** [comment]
> If you're able to share inputs and a script then I could take a look when I get a chance.

Thanks，I'll try separate the code from my project，it may take some time.

**Comment by lohedges** [comment]
No problem. I'll first check with a simple test system since there shouldn't be anything system specific about the runner part.

**Comment by kexul** [comment]
Hi @lohedges , here is the input files and scripts I used:
[inputs_and_scripts.zip](https://github.com/michellab/BioSimSpace/files/6745179/inputs_and_scripts.zip)

```
import BioSimSpace as _BSS
lig1 = ['CHEMBL92812.prmtop', 'CHEMBL92812.inpcrd']
lig2 = ['CHEMBL93461.prmtop', 'CHEMBL93461.inpcrd']
lig1 = _BSS.IO.readMolecules(lig1)[0]
lig2 = _BSS.IO.readMolecules(lig2)[0]
system = _BSS.Align.merge(lig1, lig2)
system = system.toSystem()
protocol = _BSS.Protocol.FreeEnergy()
system = _BSS.Solvent.tip3p(system, box=3*[5*_BSS.Units.Length.nanometer], work_dir='test_case')
fep = _BSS.FreeEnergy.Solvation( system, protocol, engine="SOMD", work_dir='test_case')
fep.run()
```

**Comment by lohedges** [comment]
Ah, I think I see wait the problem is. Since the processes are being run in a background thread you need to add a wait after the `fep.run()` so that the script doesn't exit immediately. At present you need to do this via the `ProcessRunner` itself. I'll expose a `wait` method on the `FreeEnergy` object so that you can do `fep.wait()`.

**Comment by lohedges** [comment]
There is now functionality to read/write systems containing perturbable molecules. When saving, the two end states are written as AMBER format topology files, with the coordinates of the lambda = 0 end state written to an AMBER coordinate file. These can then be re-loaded to reconstruct the system. I've checked that energies agree for single-point calculations using both systems, and also the SOMD pert file is the same in both cases. (Will try to add some unit tests for this.)

To use:

```python
# Here 'system' contains a single perturbable molecule.

# Save the perturbable system to disk.
BSS.IO.savePerturbableSystem("test", system)

# Read it back.
new_system = BSS.IO.readPerturbableSystem("test.rst7", "test0.prm7", "test1.prm7")
```
Here `test0.prm7` and `test1.prm7` are the topologies of the lambda = 0 and lambda = 1 end states and `test.rst7` is the coordinates at `lambda = 0`. While we could write to formats other than AMBER, this makes things slightly easier for reconstructing a simulation that is compatible with SOMD.

**Comment by kexul** [comment]
Thanks, your solution is quick and elegant.

**Comment by lohedges** [comment]
Just to note that I've updated the API so that we read/write both the topology and coordinate files for the two lambda end states, rather than just using the coordinates at lambda=0.

**Comment by kexul** [comment]
> 
> 
> Just to note that I've updated the API so that we read/write both the topology and coordinate files for the two lambda end states, rather than just using the coordinates at lambda=0.

Thanks for the information 🤗, I'll read the updated document carefully!

**Comment by lohedges** [comment]
FYI: You can now stream all of the wrapped Sire objects used by BioSimSpace to and from file, making it far easier to save and load perturbable systems. See [here](https://biosimspace.org/api/index_Stream.html) for details. (The website is currently rebuilding, so the page might take a while to appear.)

**Comment by kexul** [comment]
> FYI: You can now stream all of the wrapped Sire objects used by BioSimSpace to and from file, making it far easier to save and load perturbable systems. See [here](https://biosimspace.org/api/index_Stream.html) for details. (The website is currently rebuilding, so the page might take a while to appear.)

Great! That will enable us to decouple the pipeline furthermore, thanks for the update!

**Comment by lohedges** [comment]
Thanks for spotting. I'll sort that out later.
