### ISSUE TITLE
Proper value of report_interval in Free Energy Protocol

### ISSUE THREAD

**Issue by kexul** [michellab/BioSimSpace#219]
Hi, I've done some free energy calculations with systems prepared by BioSimSpace. I found that the `report_interval` parameter of free energy protocol has strong impact on simulation speed. Here are the GPU usage when `report_interval` was set to 10000 and 100000 respectively, their speed are 48ns/day and 32ns/day with a system contains about 50000 atoms running in Nvidia's V100 GPU. 

`report_interval=10000`: 
![image](https://user-images.githubusercontent.com/5920217/125080308-40954380-e0f7-11eb-8547-d7801d24dd16.png)

`report_interval=100000`:
![image](https://user-images.githubusercontent.com/5920217/125080316-42f79d80-e0f7-11eb-90ef-8adb5bdcbcdf.png)

I've looked the `somd.cfg` generate by BioSimSpace and found that the `report_interval`  will change the `ncycles` parameter when other parameters of the `Protocol` keep fixed. 

I would like to ask: 
1. Would the `report_interval` or `ncycles` parameter affect the final result (i.e. free energy)? If so, is there a preferred value or range?
2. In this [thread](https://groups.google.com/g/sire-users/c/c8xaJRqfUPM/m/ous2EqUKAQAJ), Julien recommend decreasing the number of cycles to gain performance. In what situation would this trick be effective? 

Thanks 😉

**Comment by jmichel80** [comment]
you can safely decrease the number of cycles and increase the number of moves per cycles to achieve the same total trajectory time Everytime a cycle ends the calculation moves back from OpenMM to Sire, and then the context has to be intialised again, hence the drops in GPU usage. As GPUs get faster and faster it can become noticable. I suggest you aim for 10 cycles, the overheads should be fairly small if your trajectory duration is on the order of 5-20 ns per lambda. 

One downside of having fewer cycles in a run is that the restart file is updated less frequently, but it's probably not a big deal for most users.

**Comment by kexul** [comment]
Thanks！😄

**Comment by lohedges** [comment]
Yes, by default we report quite frequently so I'd strongly advise reducing this for long production simulations. It's also a little tricky to map SOMD's _cycle_ behaviour with the reporting schemes used in other engines. This means that the defaults give fairly poor performance for SOMD. (We need the interface to be consistent.)
