### ISSUE TITLE
different behaviour between SOMD/GROMACS FreeEnergy.analyse()

### ISSUE THREAD

**Issue by JenkeScheen** [michellab/BioSimSpace#221]
I'm at a point in the [tutorial](https://github.com/michellab/BioSimSpaceTutorials/blob/main/04_fep/execution_model/scripts/BSSanalyseFEP.sh) where I'm trying to get an automated freenrg calculation of GROMACS directories. The same code in `BSSanalyseFEP.py` for completed simulation folders returns all freenrg values for a SOMD setup, but for a GROMACS setup the `_Exceptions.AnalysisError` is triggered:
```
scripts/BSSanalyseFEP.py jmc_27 jmc_28 GROMACS
./outputs/GROMACS/jmc_27~jmc_28
Traceback (most recent call last):
  File "scripts/BSSanalyseFEP.py", line 59, in <module>
    pmf_0, pmf_1, freenrg, overlap_matrix_bound, overlap_matrix_free = BSS.FreeEnergy.analyse(path_to_dir, "binding")
  File "/export/users/jscheen/biosimspace.app/lib/python3.7/site-packages/BioSimSpace-2020.1.0+481.g6416dc6-py3.7.egg/BioSimSpace/FreeEnergy/_free_energy.py", line 942, in analyse
    return FreeEnergy.analyse(work_dir, simulation_type)
  File "/export/users/jscheen/biosimspace.app/lib/python3.7/site-packages/BioSimSpace-2020.1.0+481.g6416dc6-py3.7.egg/BioSimSpace/FreeEnergy/_free_energy.py", line 404, in analyse
    return FreeEnergy._analyse_gromacs(work_dir, dir0, dir1, is_dual)
  File "/export/users/jscheen/biosimspace.app/lib/python3.7/site-packages/BioSimSpace-2020.1.0+481.g6416dc6-py3.7.egg/BioSimSpace/FreeEnergy/_free_energy.py", line 474, in _analyse_gromacs
    raise _AnalysisError("GROMACS free-energy analysis failed!")
BioSimSpace._Exceptions._exceptions.AnalysisError: GROMACS free-energy analysis failed!
```
in this case `path_to_dir = ./outputs/GROMACS/jmc_27~jmc_28/`. It seems that somehow `_analyse_gromacs()` is handling `work_dir` wrong: when I cd into `path_to_dir` there is a file called `bar_leg0.xvg` which contains:
```
# This file was created Tue Jul 13 11:27:53 2021
# Created by:
#                       :-) GROMACS - gmx bar, 2020.4 (-:
# 
# Executable:   /export/users/common/Gromacs20.4/bin/gmx
# Data prefix:  /export/users/common/Gromacs20.4
# Working dir:  /export/users/jscheen/projects/BSS_TUT/SCREENS/single_edge/gmx_execution_model
# Command line:
#   gmx bar -f ./outputs/GROMACS/jmc_27~jmc_28/bound/lambda_0.0000/gromacs.xvg ./outputs/GROMACS/jmc_27~jmc_28/bound/lambda_0.1667/gromacs.xvg ./outputs/GROMACS/jmc_27~jmc_28/bound/lambda_0.3333/gromacs.xvg ./outputs/GROMACS/jmc_27~jmc_28/bound/lambda_0.5000/gromacs.xvg ./outputs/GROMACS/jmc_27~jmc_28/bound/lambda_0.6667/gromacs.xvg ./outputs/GROMACS/jmc_27~jmc_28/bound/lambda_0.8333/gromacs.xvg ./outputs/GROMACS/jmc_27~jmc_28/bound/lambda_1.0000/gromacs.xvg -o ./outputs/GROMACS/jmc_27~jmc_28/bar_leg0.xvg
# gmx bar is part of G R O M A C S:
#
# Gyas ROwers Mature At Cryogenic Speed
#
@    title "Free energy differences"
@    xaxis  label "\xl\f{}"
@    yaxis  label "\xD\f{}G (kT)"
@TYPE xydy
 0.500  2.32  0.06
 1.500  1.58  0.02
 2.500  1.42  0.02
 3.500  1.29  0.01
 4.500  1.19  0.01
 5.500  1.08  0.01
```
you can see that if `gmx bar` is indeed called in this place the actual paths should be `gmx bar -f ./bound/lambda_0.0000/gromacs.xvg`, etc. Indeed, when I run that command I get the expected output (i.e. freenrg values), and when I cd back to `/execution_model/` and run the original command (i.e. `gmx bar -f ./outputs/GROMACS/jmc_27~jmc_28/bound/lambda_0.0000/gromacs.xvg `) I also get the expected output.

I'm not entirely sure where this behaviour comes from, but my guess is that the way we feed paths into [the gmx command](https://github.com/michellab/BioSimSpace/blob/devel/python/BioSimSpace/FreeEnergy/_free_energy.py#L513-L514) has to be changed?

**Comment by lohedges** [comment]
I imagine the directory naming is wrong for leg1 in this case. The fact that you have a `bar0.xvg` file suggests the path is correct for the first leg. I'll take a look after lunch.

**Comment by lohedges** [comment]
Since it's failing for the free leg, not the bound one, could you try manually re-running your command using the free directories instead to see what the error is. Perhaps something went wrong with one of the windows so that particular command is failing.

**Comment by JenkeScheen** [comment]
ah, yes. Looks like all the free legs failed. Thanks, will reopen if I get the same behaviour once I've managed to get proper `.xvg` files.

**Comment by lohedges** [comment]
I've tested here for existing GROMACS solvation and binding free-energy data and it works for me, so it should be fine assuming that you have enough output data for `gmx bar` to do its thing.
