### ISSUE TITLE
Ring size change detection

### ISSUE THREAD

**Issue by kexul** [michellab/BioSimSpace#228]
Hi guys, I'm merging two macrocyclic molecules, which have different lengths in the linker part. It seems like BioSimSpace cannot correctly detect the size change of the linker. 

# Failure Information
```
BioSimSpace._Exceptions._exceptions.IncompatibleError: The merge has changed the molecular connectivity 
but a ring didn't open/close or change size. Check your atom mapping.
```

## Steps to Reproduce
Here is the code and input files I used: 
```python
import BioSimSpace as BSS
ligand1 = BSS.IO.readMolecules(['ref.inpcrd', 
                    'ref.prmtop']).getMolecules()[0]

ligand2 = BSS.IO.readMolecules([
                        'target.inpcrd',
                        'target.prmtop'
                        ]).getMolecules()[0]

mcs={15: 0, 14: 1, 13: 2, 18: 3, 17: 4, 16: 5, 2: 13, 1: 14, 0: 15, 5: 16, 4: 17, 3: 18, 6: 19, 7: 20, 8: 21, 37:28,
        9: 22, 10: 23, 11: 24, 12: 25, 36:29,35:26,34:27,33:46,32:45, 31:44, 30:42, 29:43, 27:41, 28:40, 19:6, 20:7,
        40:30, 39:31, 21:8, 42:32, 41:33, 22:9, 44:34, 43:35, 23:10, 46:36, 45:37, 24:11, 48:38, 47:39, 25:12}

merged = BSS.Align.merge(ligand1, ligand2, mapping=mcs, allow_ring_breaking=True, allow_ring_size_change=True)
```
[ref.zip](https://github.com/michellab/BioSimSpace/files/7058749/ref.zip)

**Comment by kexul** [comment]
Ok, I've just finished 3 repeats with the latest version of sire, the results still seem quite unstable. Maybe I should avoid this kind of perturbation for now. Thanks for your help, always appreciated!🤗

  | MBAR (kcal/mol)
-- | --
B->A | -5.727557
B->A | -2.79651
B->A | -1.212892
  |  
A->B | 0.695082
A->B | 2.881661
A->B | 2.586839

**Comment by jmichel80** [comment]
Thanks for posting an update. If you have the resources, you could try setting shift delta = 1.0 in the somd config file and repeat the above calculations to see if that helps get more consistent results.

**Comment by kexul** [comment]
> etting shift delta = 1.0

I'll try it now, thank you~

**Comment by kexul** [comment]
Hi @jmichel80 , here is what I got when setting shift delta=1.0. 

  | MBAR (kcal/mol)
-- | --
B->A | -3.333392
B->A | -2.174374
B->A | -3.656418
  |  
A->B | 4.171455
A->B | 0.480716
A->B | 4.689266

It becomes more consistent 😄, and I think we could safely conclude that A is preferred from all the results above.

**Comment by jmichel80** [comment]
Ok, i would still be careful with those transformations in the absence of experimental data to validate accuracy

**Comment by kexul** [comment]
> Ok, i would still be careful with those transformations in the absence of experimental data to validate accuracy

Thanks, I'll keep that in mind.

**Comment by kexul** [comment]
Hi @jmichel80 , recently I and my colleague are trying to implement the soft bond potential suggested by this [paper](https://pubs.acs.org/doi/abs/10.1021/acs.jctc.6b00991) in Sire framework, Do you think it's necessary? since you have suggested adjust the shift-delta value. 

Furthermore, we are trying to implement some charge correction methods at the same time. Hopefully, we could make some PRs after we validate the result and clean the code.
