### ISSUE TITLE
BSS allows to parameterise a ligand without any hydrogens

### ISSUE THREAD

**Issue by AdeleLip** [michellab/BioSimSpace#230]
I've recently come across this when I mistakenly put in a ligand that didn't have hydrogens added to it yet (the file is 
[here](https://github.com/michellab/BioSimSpace/files/7143241/1t48.zip).

The code to recreate this is:
```python
import BioSimSpace as BSS
system = BSS.IO.readMolecules('1t48.pdb')
ligand = system.getMolecule(1)
ligand_parameterised = BSS.Parameters.gaff(ligand, net_charge=-1).getMolecule()
```

obviously it is up to the user to make sure the ligand structure is correct, but @jmichel80 thought it would be a good idea to bring it up.

**Comment by jmichel80** [comment]
More specifically, I would expect a lack of hydrogen to trip up a sqm calculation run by antechamber. It would be good to check what happens internally. Are hydrogen added, and then deleted ? Why is it possible to parameterise without error a molecule that has a completely unrealistic connectivity ?

**Comment by lohedges** [comment]
Hi there, that's interesting. I've normally found that AmberTools will sometimes _add_ missing hydrogens, so you get an error at the stage where BioSimSpace attempts to make the parameterised molecule compatible with the original, i.e. there will be more atoms in the new molecule.

I'll check this molecule to see what the AmberTools suite  is doing behind the scenes in case we are missing something.

**Comment by lohedges** [comment]
[Here](https://github.com/michellab/BioSimSpace/files/7143308/gaff.tar.gz) is an archive containing all of the intermediate files. (See the `README.txt` to see what commands were run.) There are 28 atoms throughout and no errors in any logs.

**Comment by lohedges** [comment]
Same result with AmberTools18 or 20. (Although sqm takes longer to converge with AmberTools20.) The only thing I see is a warning in the Antechamber output:

```
Warning: The assigned bond types may be wrong, please :
(1) double check the structure (the connectivity) and/or
(2) adjust atom valence penalty parameters in APS.DAT, and/or
(3) increase PSCUTOFF in define.h and recompile bondtype.c
    (be cautious, using a large value of PSCUTOFF (>100) will
    significantly increase the computation time).
```

(This is present with both versions of Antechamber.)

I don't know if this message _could_ be present for a valid molecule. If not, then I could check for it and report a warning to the user. It would also be easy to check for hydrogens before parameterising, too.

**Comment by jmichel80** [comment]
Hum weird. So maybe the molecule without any Hs and the specified net charge ends up with an even number of electrons so that doesn't stop sqm ? Of course there could be legit molecules without H that one wishes to parameterise (O2 ?). It's a good idea to issue a warning as we would normally expect hydrogen atoms to be present. Ultimately we are back to the user having to know what they wish to simulate (no offence meant @AdeleLip !)

**Comment by lohedges** [comment]
Yes, I agree. I've just added a warning when no hydrogens are present, which will hopefully catch cases where someone just downloads something from the PDB and tries to use it directly.

**Comment by lohedges** [comment]
Closing for now since I've implemented a proposed solution, i.e. warning when no hydrogen atoms are present. Feel free to re-open if you come across any other peculiarities related to this issue.
