### ISSUE TITLE
How to solvate two merged molecules?

### ISSUE THREAD

**Issue by kexul** [michellab/BioSimSpace#231]
Dear BioSimSpace developers, I'm trying to solvate two merged molecules by the following code:
```
import BioSimSpace as BSS
from pathlib import Path
from rdkit import Chem 
from rdkit.Chem import AllChem

mols = []
for ligand in ['C1=CC=CC=C1',  'CC1=CC=CC=C1']:
    # make pdb by rdkit
    ligand_rdkit = Chem.MolFromSmiles(ligand)
    ligand_rdkit = Chem.AddHs(ligand_rdkit)
    AllChem.EmbedMolecule(ligand_rdkit)
    Chem.MolToPDBFile(ligand_rdkit, 'ligand.pdb')

    # read pdb and parametrise by biosimspace
    ligand_bss = BSS.IO.readPDB('ligand.pdb').getMolecules()[0]
    process = BSS.Parameters.gaff(ligand_bss)
    parametrised_molecule = process.getMolecule()
    mols.append(parametrised_molecule)

mapping = BSS.Align.matchAtoms(mols[0], mols[1])
mols[0] = BSS.Align.rmsdAlign(mols[0], mols[1], mapping)
merged = BSS.Align.merge(mols[0], mols[1], mapping)


merged2 = merged.copy()
merged2.translate([3*BSS.Units.Length.nanometer, 0, 0])
sys2 =  merged + merged2


solvated_system = BSS.Solvent.tip3p(sys2,box=3*[8*BSS.Units.Length.nanometer], work_dir='solvation')
```

But an error occurred: 

```
Traceback (most recent call last):
  File "/root/group_ceph/FEP/prepare/test_case/git/test.py", line 35, in <module>
    solvated_system = BSS.Solvent.tip3p(sys2,box=3*[8*BSS.Units.Length.nanometer], work_dir='solvation')
  File "/root/group_ceph/FEP/prepare/BioSimSpace/Solvent/_solvent.py", line 284, in tip3p
    _validate_input("tip3p", molecule, box, angles, shell, ion_conc, is_neutral, work_dir, property_map)
  File "/root/group_ceph/FEP/prepare/BioSimSpace/Solvent/_solvent.py", line 460, in _validate_input
    _molecule = molecule.toSystem()
  File "/root/group_ceph/FEP/prepare/BioSimSpace/_SireWrappers/_molecules.py", line 239, in toSystem
    return _System(self)
  File "/root/group_ceph/FEP/prepare/BioSimSpace/_SireWrappers/_system.py", line 94, in __init__
    self.addMolecules(system)
  File "/root/group_ceph/FEP/prepare/BioSimSpace/_SireWrappers/_system.py", line 424, in addMolecules
    self._reset_mappings()
  File "/root/group_ceph/FEP/prepare/BioSimSpace/_SireWrappers/_system.py", line 1542, in _reset_mappings
    self._molecule_index[self._sire_object[_SireMol.MolIdx(idx)].number()] = idx
AttributeError: 'list' object has no attribute 'number'
```

### Context

Recently I found an interesting [trick ](https://pubs.acs.org/doi/10.1021/acs.jctc.1c00214) to deal with the charge changing perturbation, I thought it would be quite easy to implement it by BioSimSpace since we could merge two systems simply by adding them up. 
![image](https://user-images.githubusercontent.com/5920217/133428199-c19c36e4-9425-4fca-af2e-f354b2a5534b.png)

**Comment by lohedges** [comment]
I think something funny is going on since the two merged molecules have the same `MolNum`, so `sys2` is just a single molecule. (It essentially creates a system with the first molecule, then replaces the molecule with the second.) The system object has some internal data structures to keep track of atom / residue indices as you add or remove molecules, so I imagine that this is wrong.

I'll try to debug further. I imagine that it could be solved by creating a new `MolNum` on copy, although I'd need to make sure that this doesn't break any other functionality behind the scenes.

**Comment by lohedges** [comment]
Just to note that BioSimSpace can directly parameterise a SMILES string, e.g.:

```python
mol = BSS.Parameters.gaff("'C1=CC=CC=C1").getMolecule()
```

**Comment by kexul** [comment]
> 
> 
> Just to note that BioSimSpace can directly parameterise a SMILES string, e.g.:
> 
> ```python
> mol = BSS.Parameters.gaff("'C1=CC=CC=C1").getMolecule()
> ```

Wow! That's good to know! I'm following the examples [here](https://biosimspace.org/api/index_Parameters.html), which always use `pdb` as inputs, so I thought only `pdb` is allowed.

**Comment by lohedges** [comment]
Yes, it's a fairly recent addition that came in when we added support for OpenFF. You've reminded me that i should add a few examples to the docs to complement the API documentation (which has been updated).

**Comment by lohedges** [comment]
This is a bit of a pain to fix in general. Sire has the concept of molecule _numbers_ and _views_. For example, you could create a view of a molecule by translating its coordinates. Internally, BioSimSpace has a lot of data structures that are based on _unique_ molecule numbers. This allows for efficient was to extract absolute and relative indices of objects, e.g. atoms, within a molecule, and also all of the Pythonic convenience functions, such as molecule addition, subtraction, etc., which make sure to preserve molecular ordering.

For now, I've enforced that the BioSimSpace wappers for `Sire.System.System` and `Sire.Mol.MoleculeGroup` only allow unique molecule numbers. To create a molecule with a new number, you can use the `.copy` method, as you are doing in your script above. As such, the same script should now work.

In the long term I might need to think of whether we need to support views. If so, I'll probably need to re-index things internally by `MolNum` _and_ version, but this quickly gets messy.

**Comment by kexul** [comment]
Thank you so much, it worked like a charm! 🎉🎉🎉

**Comment by lohedges** [comment]
The paper you link to looks interesting. This approach won't work in the current setup since BioSimSpace can only handle systems with a _single_ perturbable molecule. In practice there shouldn't be any difficulty in handling more molecules, I just don't if/how SOMD implements this.  The C++ code _looks_ like it can perturb more than one molecule, but there is an option in the Python wrapper that implies that the perturbation applies to a single molecule.

```
perturbed residue number = 1
The residue number of the molecule to morph.
```

If this is something that would be easy to implement then I'd be happy to put it on my TODO list.

**Comment by kexul** [comment]
> This approach won't work in the current setup since BioSimSpace can only handle systems with a single perturbable molecule.

Wow, thanks for the clarification. I'll run some tests to verify that.

**Comment by jmichel80** [comment]
@lohedges is correct, there are certain limitations in SOMD that make the simultaneous perturbation of different molecules difficult to implement without hacking your way around. A solution is to setup different inputs and carry separate free energy calculations. For instance we have done use cases were two water molecules in a binding site are decoupled serially.

**Comment by kexul** [comment]
Hi @jmichel80, would it be a problem when using Gromacs as the back-end?

**Comment by lohedges** [comment]
I think GROMACS would work. (The topology parser can certainly handle an arbitrary number of perturbable molecules.) However, BioSimSpace still enforces that there is a single molecule since we need to be consistent across engines. You could try to remove the check and see what happens. (I can send you the line when I'm back in front of the computer.)

**Comment by lohedges** [comment]
You could try commenting out the conditionals starting [here](https://github.com/michellab/BioSimSpace/blob/3e3b25d331be41d7b40db1ac2000dfcb1b4ab4fb/python/BioSimSpace/FreeEnergy/_relative.py#L138) and [here](https://github.com/michellab/BioSimSpace/blob/3e3b25d331be41d7b40db1ac2000dfcb1b4ab4fb/python/BioSimSpace/Process/_gromacs.py#L168). This will certainly break things for SOMD, but should let you try out a dual perturbable molecule system with GROMACS.

**Comment by kexul** [comment]
> 
> 
> You could try commenting out the conditionals starting [here](https://github.com/michellab/BioSimSpace/blob/3e3b25d331be41d7b40db1ac2000dfcb1b4ab4fb/python/BioSimSpace/FreeEnergy/_relative.py#L138) and [here](https://github.com/michellab/BioSimSpace/blob/3e3b25d331be41d7b40db1ac2000dfcb1b4ab4fb/python/BioSimSpace/Process/_gromacs.py#L168). This will certainly break things for SOMD, but should let you try out a dual perturbable molecule system with GROMACS.

Thank you 🙏, I'll try it soon!

**Comment by kexul** [comment]
Yes, Gromacs worked! I tried the systems generated above, the energy value of two molecules system is `-7.121`, for one molecule system, it's `-3.559`.

**Comment by lohedges** [comment]
Great, thanks for the update. With the updated `FreeEnergy.Relative` I should be able to remove the single perturbable molecule restriction when the engine is GROMACS. I'll look into doing this soon.

**Comment by kexul** [comment]
> 
> 
> Great, thanks for the update. With the updated `FreeEnergy.Relative` I should be able to remove the single perturbable molecule restriction when the engine is GROMACS. I'll look into doing this soon.

Thanks, it could be quite useful!
