### ISSUE TITLE
Running free energy calculations using SOMD via BSS on GPUs

### ISSUE THREAD

**Issue by annamherz** [michellab/BioSimSpace#232]
Hello! I am running the BSS-dev conda version (version=2020.1.0  build=py37h9bf148f_586  channel=michellab/label/dev) in jupyter notebooks on ubuntu. I am trying to run the BSS.FreeEnergy using the following input (ligand1 is benzene and ligand2 is o-xylene, from the SOMD Free Energy of Binding Tutorial (https://siremol.org/tutorials/somd/Binding_free_energy/FESetup.html)):
`ligand_1 = BSS.IO.readMolecules("ligand1.mol2")[0]
ligand_2 = BSS.IO.readMolecules("ligand2.mol2")[0]
ligand_1 = BSS.Parameters.gaff2(ligand_1).getMolecule()
ligand_2 = BSS.Parameters.gaff2(ligand_2).getMolecule()

mappings, scores = BSS.Align.matchAtoms(ligand_1, ligand_2, matches=5, return_scores=True)
ligand_1 = BSS.Align.rmsdAlign(ligand_1, ligand_2, mappings[0])
merged = BSS.Align.merge(ligand_1, ligand_2, mappings[0])

solvated = BSS.Solvent.tip3p(molecule=merged, box=3*[10*BSS.Units.Length.nanometer])

protocol = BSS.Protocol.FreeEnergy()
fep_solvated = BSS.FreeEnergy.Relative(solvated, protocol, engine="somd", work_dir="bss/solvated")
fep_solvated.run()`

however it automatically runs on the CPU:
`ps -ef | grep somd
anna      271803  145023 99 10:47 ?        01:13:10 /home/anna/anaconda3/envs/biosimspace-dev/bin/somd-freenrg -c somd.rst7 -t somd.prm7 -m somd.pert -C somd.cfg -p CPU`

I checked optimise-openmm and got:
`The CUDA platform is successfully recognised by openMM! Nothing needs to be done and you can use SOMD
['Reference', 'CPU', 'CUDA', 'OpenCL']`

and when starting the run in the folder:
`somd-freenrg -c somd.rst7 -t somd.prm7 -m somd.pert -C somd.cfg -p CUDA`
it runs on the GPU without a problem:
`ps -ef | grep somd
anna      274418  135945 99 11:09 pts/2    00:02:06 /home/anna/anaconda3/envs/biosimspace-dev/bin/somd-freenrg -c somd.rst7 -t somd.prm7 -m somd.pert -C somd.cfg -p CUDA`

I am unsure why BSS isn't running it on the GPUs?

**Comment by lohedges** [comment]
Hi there,

SOMD relies on the `CUDA_VISIBLE_DEVICES` environment variable being set in order to set the GPU  ID. This is usually done for you when running on HPC resources. If you're running locally on a workstation or laptop then you'll need to set it yourself. For example, if you've got a single GPU then do something like `export CUDA_VISIBLE_DEVICES=0` before using BioSimSpace.

**Comment by annamherz** [comment]
Great, thank you!
