### ISSUE TITLE
Gromacs topology parser

### ISSUE THREAD

**Issue by kexul** [michellab/BioSimSpace#234]
Dear @lohedges, recently I'm working on recovering the merged molecule from the Gromacs topology file. I tried splitting the Groamcs topology file to state0 and state1, converting them to amber file format, then recovering the merged molecule by `BSS.IO.readPerturbableSystem`. I believe I'm about to succeed, except for one thing: After converting to amber file format and reading the perturbable system, the Gromacs improper dihedral information was lost, I think it's related to BioSimSpace's implementation under the hood, would you mind spot where the problem is? Thanks! 🤗

Here is the code I've written: 
```python
from pathlib import Path
import BioSimSpace as BSS

def toList(row):
    """a helper function to split one line to list

    Parameters
    ----------
    row : str
        one row of gromacs top file

    Returns
    -------
    list
        list of str
    """
    new_row = []
    for item in row.split(' '):
        if item:
            new_row.append(item)
    return new_row

class TopParser:
    def __init__(self) -> None:
        self._state0 = []
        self._state1 = []
        self._directives = ['[ atoms ]', '[ bonds ]', '[ angles ]', '[ dihedrals ]']
        self._typical_len = [8, 5, 6, 8]
        self._replace_pos = [[1, -2, -1], [-2, -1], [-2, -1], [-3, -2, -1]]

    def getTypicalLen(self, directive):
        return self._typical_len[self._directives.index(directive)]

    def getReplacePos(self, directive):
        return self._replace_pos[self._directives.index(directive)]
    
    def getDirectives(self):
        return self._directives.copy()

    def setLine(self, line0, line1=None):
        if line1 is not None:
            self._state0.append(line0)
            self._state1.append(line1)
        else:
            self._state0.append(line0)
            self._state1.append(line0)

    def write(self, file_path0, file_path1):
        Path(file_path0).write_text('\n'.join(self._state0))
        Path(file_path1).write_text('\n'.join(self._state1))



def directiveHandler(directive, line, parser):
    """handler for directives

    Parameters
    ----------
    directive : str
        top file directive
    line : str
        one row of the top file
    parser : TopParser
        top file parser

    Returns
    -------
    str
        directive, updated
    """
    if not line:
        parser.setLine(line)
        return False 
    else:
        row_list = toList(line)
        typical_len = parser.getTypicalLen(directive)
        replace_pos = parser.getReplacePos(directive)
        if len(row_list) > typical_len:
            line0 = row_list[:typical_len]
            line1_temp = row_list[typical_len:]
            line1 = line0.copy()
            for idx, item in enumerate(line1_temp):
                line1[replace_pos[idx]] = item
            line0 = '\t'.join(line0)
            line1 = '\t'.join(line1)
            parser.setLine(line0, line1)
        else:
            parser.setLine(line) 
    return directive


def splitTop(top_file_path, out1, out2):
    """split the gromacs top file to state0 and state1

    Parameters
    ----------
    top_file_path : str
        gromacs top file path
    out1 : str
        state0 top file path
    out2 : str
        state1 top file path
    """
    content = Path(top_file_path).read_text()
    parser = TopParser()

    directive = False
    for line in content.split('\n'):
        if line.startswith(';'):
            parser.setLine(line)
            continue

        if directive:
            directive = directiveHandler(directive, line, parser) 
        else:
            parser.setLine(line)

        for key in parser.getDirectives():
            if key in line:
                directive = key
                break
        
    parser.write(out1, out2)


def get_energy(system, work_dir, lambda1):
    # Create a minimisation protocol with a single step.
    protocol = BSS.Protocol.Minimisation(steps=1)

    # Create a process to run this with GROMACS.
    if lambda1:
        gmx_process = BSS.Process.Gromacs(system, protocol, work_dir=work_dir, property_map={'is_lambda1': True})
    else:
        gmx_process = BSS.Process.Gromacs(system, protocol, work_dir=work_dir)

    # To get a better comparison, set the number of steps to zero for GROMACS. We don't support this
    # in the Protocol by default, since most engines don't allow zero steps.
    config = gmx_process.getConfig()
    config[1] = "nsteps = 0"
    gmx_process.setConfig(config)

    # Now run the minimisations.
    gmx_process.start()
    gmx_process.wait()

    # Now print out the energy terms that you want to check. Note that different engines
    # output different information for different protocols, so you might not be able to compare
    # directly through BioSimSpace. Also, GROMACS splits dihedral enegies into proper and
    # impropers, whereas AMBER doesn't. I would suggest reading the values from
    # amb_test/amber.nrg and gmx_test/gromacs.log and comparing manually.
    print(gmx_process.getPotentialEnergy().kcal_per_mol())


if __name__ == '__main__':
    mols = []
    for ligand in ['C1=CC=CC=C1',  'CC1=CC=CC=C1']:
        process = BSS.Parameters.gaff(ligand)
        parametrised_molecule = process.getMolecule()
        mols.append(parametrised_molecule)

    mapping = BSS.Align.matchAtoms(mols[0], mols[1])
    mols[0] = BSS.Align.rmsdAlign(mols[0], mols[1], mapping)
    merged = BSS.Align.merge(mols[0], mols[1], mapping)

    solvated_system = BSS.Solvent.tip3p(merged, box=3*[3*BSS.Units.Length.nanometer], work_dir='solvation')
    BSS.IO.saveMolecules('morph', solvated_system, ['gro87', 'grotop'])

    splitTop('morph.top', 'state0.top', 'state1.top')

    state0 = BSS.IO.readMolecules(['morph.gro', 'state0.top']) 
    BSS.IO.saveMolecules('state0', state0, fileformat=['prm7', 'rst7'])
    state1 = BSS.IO.readMolecules(['morph.gro', 'state1.top']) 
    BSS.IO.saveMolecules('state1', state1, fileformat=['prm7', 'rst7'])
    recoverd_system = BSS.IO.readPerturbableSystem('state0.prm7', 'state0.rst7', 'state1.prm7', 'state1.rst7')

    for lambda1 in [False, True]:
        print(f'lamba1: {lambda1}')
        get_energy(solvated_system, 'ori', lambda1)
        get_energy(recoverd_system, 'rec', lambda1)
```

Here is the output: 
```
lamba1: False
6.6153e+05 kcal/mol
6.6152e+05 kcal/mol
lamba1: True
9.6526e+06 kcal/mol
7.0648e+05 kcal/mol
```

> Gromacs improper dihedral information was lost

If we run the above script and check the `gromacs.top` under the folder `rec`, you will find that all `funct` parameters become `1`, but the `gromacs.top` in `ori` folder got some `4`s.

**Comment by lohedges** [comment]
Hi there,

I won't have a proper chance to look at this until next week. Just to say that, depending on the conversion, proper and improper dihedrals might be combined when changing format. As such, the total energy will be the same, but the value for individual terms will differ.

I was just wondering the need for recovering the merged system from a perturbable GROMACS topology? I guess this would let you read existing GROMACS files prepared outside of BioSimSpace. For any new simulation, you could just use the existing read/write functionality that goes via AMBER intermediates, which also store additional information that is required for SOMD. (This would be lost going to AMBER.) Ideally I'd like to add support for reading perturbable GROMACS topologies in the `Sire.IO.GroTop` parser, but this won't be done for a while.

**Comment by kexul** [comment]
> I guess this would let you read existing GROMACS files prepared outside of BioSimSpace. 

Yes! Exactly what I want. I'm reading some topology files generate by this [program](https://github.com/deGrootLab/pmx). Though not as versatile as BioSimsSpace, it has a nice function to mutate the protein, which is useful for me at the moment.

**Comment by lohedges** [comment]
Thanks for the clarification. I'll try to take a look at some point next week. I hacked together a script a while ago to do something similar for debugging purposes so I'll try to find that.

**Comment by kexul** [comment]
When comparing the `prm7` file generated by `savePerturbableSystem` and my way (i.e. save to `GroTop` and read, then save to `Prm7`), I found that most  of the content was identical, except the `%FLAG DIHEDRALS_INC_HYDROGEN` and `%FLAG DIHEDRALS_WITHOUT_HYDROGEN`.  

Then I checked the non-perturbable molecule and found the same behavior, is this in line with expectation? 

Here is the code I've used: 
```python 
ligand = 'C1=CC=CC=C1'
process = BSS.Parameters.gaff(ligand)
mol = process.getMolecule()
BSS.IO.saveMolecules('mol_ori', mol, ['prm7', 'rst7'])

BSS.IO.saveMolecules('mol_ori', mol, ['gro87', 'grotop'])
mol0 = BSS.IO.readMolecules(['mol_ori.gro', 'mol_ori.top'])
BSS.IO.saveMolecules('mol_rec', mol0, ['prm7', 'rst7'])
```

Here is the difference: 
![企业微信截图_16325761064641](https://user-images.githubusercontent.com/5920217/134773068-193036a2-32d8-44e0-ab41-20aff18b8f97.png)

**Comment by lohedges** [comment]
Try a single point calculation in vacuum for both molecules and check that the total energy is the same. The issue is that when parsing the files were convert the potential terms, e.g. dihedrals, to computer algebra expressions to store internally. This can involve factorisation, simplification, etc, so although mathematically equivalent, the terms might be different when converted back to another format. There are also differences in the way multi-dihedral terms are handled between formats, so again you might end up with a different representation of the same information. If you do a round trip conversion, e.g. AMBER -> GROMACS-> AMBER you won't necessarily end up with the same topology file, although the information should be consistent and give the same energy.

**Comment by kexul** [comment]
Hi @lohedges , Thanks for your quick reply! 

> Try a single point calculation in vacuum for both molecules and check that the total energy is the same.

Here is the energy I got (using Gromacs to compute energy): 

Before conversion: 
```
          Bond          Angle    Proper Dih.  Improper Dih.          LJ-14
    5.88593e+00    4.03305e+00    7.06042e-04    9.68365e-05    1.86545e+01
     Coulomb-14        LJ (SR)   Coulomb (SR)      Potential Pressure (bar)
   -6.88961e-01   -7.21528e-01    1.06558e+01    3.78196e+01    5.21813e-06
```
After conversion: 
```
 Energies (kJ/mol)
           Bond          Angle    Proper Dih.          LJ-14     Coulomb-14
    7.46047e+00    4.16110e+00    3.43157e-02    1.89928e+01   -6.88242e-01
        LJ (SR)   Coulomb (SR)      Potential Pressure (bar)
   -7.22161e-01    1.06351e+01    3.98734e+01    5.28176e-06
```

Is this within the tolerance? 

Here is the code I used: 
```python

def get_energy(system, work_dir, lambda1):
    # Create a minimisation protocol with a single step.
    protocol = BSS.Protocol.Minimisation(steps=1)

    # Create a process to run this with GROMACS.
    if lambda1:
        gmx_process = BSS.Process.Gromacs(system, protocol, work_dir=work_dir, property_map={'is_lambda1': True})
    else:
        gmx_process = BSS.Process.Gromacs(system, protocol, work_dir=work_dir)

    # To get a better comparison, set the number of steps to zero for GROMACS. We don't support this
    # in the Protocol by default, since most engines don't allow zero steps.
    config = gmx_process.getConfig()
    config[1] = "nsteps = 0"
    gmx_process.setConfig(config)

    # Now run the minimisations.
    gmx_process.start()
    gmx_process.wait()


ligand = 'C1=CC=CC=C1'
process = BSS.Parameters.gaff(ligand)
mol = process.getMolecule()

solvated_system = BSS.Solvent.tip3p(mol, box=3*[3*BSS.Units.Length.nanometer], work_dir='solvation')
solvated_system.removeWaterMolecules()

get_energy(solvated_system, 'test1', False)

BSS.IO.saveMolecules('mol_ori', mol, ['prm7', 'rst7'])
BSS.IO.saveMolecules('mol_ori', mol, ['gro87', 'grotop'])
mol0 = BSS.IO.readMolecules(['mol_ori.gro', 'mol_ori.top'])
BSS.IO.saveMolecules('mol_rec', mol0, ['prm7', 'rst7'])
mol_rec = BSS.IO.readMolecules(['mol_rec.prm7', 'mol_rec.rst7'])

solvated_system = BSS.Solvent.tip3p(mol_rec, box=3*[3*BSS.Units.Length.nanometer], work_dir='solvation')
solvated_system.removeWaterMolecules()
get_energy(solvated_system, 'test2', False)



```

**Comment by kexul** [comment]
After some digging, I found that the difference in a round trip conversion is a precision issue when saving files to Gromacs `gro` file type.  Related to this issue https://github.com/michellab/BioSimSpace/issues/225. 
When setting `property_map={"precision" : wrap(6)}` in `saveMolecules`, the results could match perfectly. 

Before conversion:
```
 Energies (kJ/mol)
           Bond          Angle    Proper Dih.  Improper Dih.          LJ-14
    5.88593e+00    4.03305e+00    7.06042e-04    9.68365e-05    1.86545e+01
     Coulomb-14        LJ (SR)   Coulomb (SR)      Potential Pressure (bar)
   -6.88961e-01   -7.21528e-01    1.06558e+01    3.78196e+01    5.21813e-06
```

After conversion: 
```
 Energies (kJ/mol)
           Bond          Angle    Proper Dih.          LJ-14     Coulomb-14
    5.88593e+00    4.03305e+00    8.02879e-04    1.86545e+01   -6.88961e-01
        LJ (SR)   Coulomb (SR)      Potential Pressure (bar)
   -7.21528e-01    1.06558e+01    3.78196e+01    5.21813e-06
```

Here is the code I've used: 
```python 
ligand = 'C1=CC=CC=C1'
process = BSS.Parameters.gaff(ligand)
mol = process.getMolecule()

solvated_system = BSS.Solvent.tip3p(mol, box=3*[3*BSS.Units.Length.nanometer], work_dir='solvation')
solvated_system.removeWaterMolecules()

get_energy(solvated_system, 'test1', False)

BSS.IO.saveMolecules('mol_ori', mol, ['prm7', 'rst7'])
BSS.IO.saveMolecules('mol_ori', mol, ['gro87', 'grotop'], property_map={"precision" : wrap(6)})
mol0 = BSS.IO.readMolecules(['mol_ori.gro', 'mol_ori.top'])
BSS.IO.saveMolecules('mol_rec', mol0, ['prm7', 'rst7'])
mol_rec = BSS.IO.readMolecules(['mol_rec.prm7', 'mol_rec.rst7'])

solvated_system = BSS.Solvent.tip3p(mol_rec, box=3*[3*BSS.Units.Length.nanometer], work_dir='solvation')
solvated_system.removeWaterMolecules()
get_energy(solvated_system, 'test2', False)
```

**Comment by kexul** [comment]
The energy difference in the merged molecule at `lambda1`  was caused by the coordinate file, not the topology file, that is: If we use the coordinate file at lambda1 generated by `savePerrubableSystem()` (i.e. the `morph1.rst7`, `morph0.rst7` won't work), combined with the topology file generate by my way, the energy would match perfectly. 

Here is the output: 
```
lamba1: False
6.6153e+05 kcal/mol
6.6153e+05 kcal/mol
lamba1: True
9.6526e+06 kcal/mol
9.6526e+06 kcal/mol
```

Code I used: 
```python 
mols = []
for ligand in ['C1=CC=CC=C1',  'CC1=CC=CC=C1']:
    process = BSS.Parameters.gaff(ligand)
    parametrised_molecule = process.getMolecule()
    mols.append(parametrised_molecule)

mapping = BSS.Align.matchAtoms(mols[0], mols[1])
mols[0] = BSS.Align.rmsdAlign(mols[0], mols[1], mapping)
merged = BSS.Align.merge(mols[0], mols[1], mapping)

solvated_system = BSS.Solvent.tip3p(merged, box=3*[3*BSS.Units.Length.nanometer], work_dir='solvation')
BSS.IO.saveMolecules('morph', solvated_system, ['gro87', 'grotop'], property_map={'precision': wrap(6)})
BSS.IO.savePerturbableSystem('morph', solvated_system)

splitTop('morph.top', 'state0.top', 'state1.top')

state0 = BSS.IO.readMolecules(['morph.gro', 'state0.top']) 
BSS.IO.saveMolecules('state0', state0, fileformat=['prm7', 'rst7'])
state1 = BSS.IO.readMolecules(['morph.gro', 'state1.top']) 
BSS.IO.saveMolecules('state1', state1, fileformat=['prm7', 'rst7'])
# recoverd_system = BSS.IO.readPerturbableSystem('state0.prm7', 'state0.rst7', 'state1.prm7', 'state1.rst7')
recoverd_system = BSS.IO.readPerturbableSystem('state0.prm7', 'state0.rst7', 'state1.prm7', 'morph1.rst7')

for lambda1 in [False, True]:
    print(f'lamba1: {lambda1}')
    get_energy(solvated_system, 'ori', lambda1)
    get_energy(recoverd_system, 'rec', lambda1)
```

I've checked the difference in the coordinate file, it seems like another issue caused by **PBC**. Here are the differences between `morph0.rst7` and `morph1.rst7` generated by `savePerturbableSystem()`. The `state0.rst7` and `state1.rst7` generated by my way are identical and are the same as `morph0.rst7`. 

![企业微信截图_16326294952494](https://user-images.githubusercontent.com/5920217/134793370-50e53000-9846-47d2-8b05-b7041e4bc1d8.png)

**Comment by lohedges** [comment]
I've not worked through all of this yet, but just to comment that the coordinates of `morph0.rst7` and `morph1.rst7` generated by `savePerturbableSystem` will be different, since the come from the coordinates of the original ligands (following alignment). With the GROMACS system, the simulation input only uses the lambda = 0 coordinates so you lose the lambda = 1 information. When recovering the perturbable system you are simply duplicating the lambda = 0 coordinates, so they are identical.

Both SOMD and GROMACS only use the lambda = 0 coordinates as the staring point for FEP, and use their own internal functionality to generate the initial state for a lambda > 0 simulation. As such, you probably only need to preserve the lambda = 0 coordinates to recover the system. This is what I did initially with `savePerturbableSystem`, but realised that it was trivial to save the lambda = 1 coordinates too, which allowed for a full recovery of the state. This allows the user to simulate the lambda = 1 state, e.g. equilibrate, if desired, or to generate a lambda intermediate themselves.

**Comment by kexul** [comment]
Thanks, learned a lot from your words! 

I just visualized the coordinate of  `morph0.rst7` and `morph1.rst7` generated by `savePerturbableSystem()`, one is at the edge of the PBC box, one is at the centre of the PBC box. Does this match expectations?

![企业微信截图_16327349104683](https://user-images.githubusercontent.com/5920217/134882555-1641055a-6faa-45df-bb51-306e51125f62.png)

**Comment by lohedges** [comment]
No, assuming that the ligands were aligned before the merge the coordinates should be close together, although not exact.

**Comment by lohedges** [comment]
Changing your original code to the following:

```python
...

if __name__ == '__main__':
    mols = []
    for ligand in ['C1=CC=CC=C1',  'CC1=CC=CC=C1']:
        process = BSS.Parameters.gaff(ligand)
        parametrised_molecule = process.getMolecule()
        mols.append(parametrised_molecule)

    mapping = BSS.Align.matchAtoms(mols[0], mols[1])
    mols[0] = BSS.Align.rmsdAlign(mols[0], mols[1], mapping)
    merged = BSS.Align.merge(mols[0], mols[1], mapping)

    solvated_system = BSS.Solvent.tip3p(merged, box=3*[3*BSS.Units.Length.nanometer], work_dir='solvation')
    # Save the original perturbable system.
    BSS.IO.savePerturbableSystem('morph', solvated_system)
    BSS.IO.saveMolecules('morph', solvated_system, ['gro87', 'grotop'])

    splitTop('morph.top', 'state0.top', 'state1.top')

    # Read the recovered topology files using the original coordinates.
    state0 = BSS.IO.readMolecules(['morph0.rst7', 'state0.top'])
    BSS.IO.saveMolecules('state0', state0, fileformat=['prm7', 'rst7'])
    state1 = BSS.IO.readMolecules(['morph1.rst7', 'state1.top'])
    BSS.IO.saveMolecules('state1', state1, fileformat=['prm7', 'rst7'])
    recoverd_system = BSS.IO.readPerturbableSystem('state0.prm7', 'state0.rst7', 'state1.prm7', 'state1.rst7')

    for lambda1 in [False, True]:
        print(f'lamba1: {lambda1}')
        get_energy(solvated_system, 'ori', lambda1)
        get_energy(recoverd_system, 'rec', lambda1)
```

...gives (for this realisation of the solvent):

```
-232.3975 kcal/mol
-232.3965 kcal/mol
lamba1: True
1.4697e+04 kcal/mol
1.4697e+04 kcal/mol
```

The lambda = 1 energies now agree since we are using the _same_ coordinates as the original perturbable system, rather than using the lambda = 0 coordinates for both end states. Note that I use `savePerturbableSystem` to write the original lamba = 0/1 coordinates, then combine those with your recovered `state0.top` and `state1.top` on read. It's perfectly fine to combine file formats on read, as long as the information in those files is self-consistent, e.g. here we have mixed AMBER and GROMACS format files.

**Comment by lohedges** [comment]
I'm not sure what's going on with your VMD visualisation of the two ligands using the AMBER files. The following works for me:

```python
BSS.IO.savePerturbableSystem('morph', solvated_system)
```

```
vmd -f -parm7 morph0.prm7 -rst7 morph0.rst7 -f -parm7 morph1.prm7 -rst7 morph1.rst7
```

(For simplicity you could also just save `merged`.)

Also, if you extract the two end states, then combine them and save to a PDB then everything looks fine.

```python
BSS.IO.saveMolecules("test", (merged._toRegularMolecule() + 
merged._toRegularMolecule(is_lambda1=True).copy()).toSystem(), "pdb")
```

I've checked in coordinates of the PDB file and they are _exactly_ the same as the two coordinate end states from `savePerturbableSystem`. This also agrees with the original coordinates after alignment and using the mapping.

**Comment by kexul** [comment]
> Also, if you extract the two end states, then combine them and save to a PDB then everything looks fine.

Yes, the pdb file here looks fine too. 
![企业微信截图_16328288849261](https://user-images.githubusercontent.com/5920217/135079244-6358c7fc-be33-46b0-b6c6-8e6830e97e87.png)

But the `morph0.rst7` and `morph1.rst7` saved by `savePerturbableSystem()` becomes: 
![企业微信截图_16328290201008](https://user-images.githubusercontent.com/5920217/135079530-8d9c3630-4bec-48d9-9e9f-43af7140ff07.png)

**Comment by kexul** [comment]
> The lambda = 1 energies now agree since we are using the same coordinates as the original perturbable system, rather than using the lambda = 0 coordinates for both end states. Note that I use savePerturbableSystem to write the original lamba = 0/1 coordinates, then combine those with your recovered state0.top and state1.top on read. It's perfectly fine to combine file formats on read, as long as the information in those files is self-consistent, e.g. here we have mixed AMBER and GROMACS format files.

Yes, I think I can safely read the topology file generated by other software now. It's amazing that BioSimSpace can read mixed file formats. Great work! 🎉🎉🎉

**Comment by lohedges** [comment]
That's not what I see. Here I'm saving the `merged` molecule only:

`morph0.rst7`
```
BioSimSpace System
   15
   0.0188384  -1.1835937  -0.0923442  -1.3595317  -1.1774019  -0.0201050
  -2.0203978   0.0192808   0.1005663  -1.3120769   1.2067951   0.1480968
   0.0557614   1.1753839   0.0756132   0.7534911   0.0001471  -0.0454480
   0.4937057  -2.1540418  -0.1867979  -1.9026280  -2.1279916  -0.0603854
  -3.0953219   0.0223811   0.1569004  -1.8555963   2.1373419   0.2438797
   0.5622273   2.1456118   0.1180273   1.8265286  -0.0159128  -0.1030032
   2.5680000   0.0160000  -1.1540000   2.6500000  -0.9150000   0.3530000
   2.6160000   0.8520000   0.4690000
```

`morph1.rst7`
```
BioSimSpace System
   15
  -0.0090000  -1.1710000  -0.0900000  -1.3880000  -1.1670000  -0.0180000
  -2.1010000   0.0100000   0.1040000  -1.3660000   1.1770000   0.1490000
   0.0110000   1.1760000   0.0770000   0.7230000  -0.0010000  -0.0440000
   0.5130000  -2.1020000  -0.1840000  -1.9730000  -2.0810000  -0.0530000
  -3.1830000  -0.0090000   0.1590000  -1.8700000   2.1240000   0.2440000
   0.5930000   2.1060000   0.1140000   2.2150000  -0.0140000  -0.1230000
   2.5680000   0.0160000  -1.1540000   2.6500000  -0.9150000   0.3530000
   2.6160000   0.8520000   0.4690000
```
which is the same as the PDB file.

Hmmm, just checked the solvated system and something funky is going on.  (Same coordinates you are seeing.) Will try to debug further.

**Comment by lohedges** [comment]
I know what the issue is. Since we found that we needed to translate the molecule to the centre of the GROMACS solvent box (due to the PBC issues), I need to make sure to do this for _both_ end states when the molecule is perturbable! Should be an easy fix.

**Comment by kexul** [comment]
Great! The updated code works very well!🎉🎉🎉
