### ISSUE TITLE
Custom force constant in restraint 

### ISSUE THREAD

**Issue by kexul** [michellab/BioSimSpace#235]
**Is your feature request related to a problem? Please describe.**
Thanks to BioSimSpace's implementation of restraints, we could select different groups of atoms to be restrained, as discussed in this [thread](https://github.com/michellab/BioSimSpace/issues/203). But it seems like we could not set a custom force constant in the restraints. Current setting in `posre_***.itp` is 1000. 

I've searched through the documentation of BioSimSpace, only find a `setForceConstant`  function in `Metadynamics.Restraint`, I'm not sure if it can be used in a normal simulation. 

**Describe the solution you'd like**
It could be nice if we have some parameters to set custom force constant in restraint, thanks! 

**Additional context**
Recently the pharmaceutical chemists in my group watched my simulation trajectory and complained that the ligand moved too far from the reference position (ligand position in cocrystal) during the `Minimization -> NVT Equilibration -> NPT Equilibration` procedure. So I would like to add some fine-grained position restraints during the equilibration, as this [paper](https://aip.scitation.org/doi/10.1063/5.0013849) recommended. In the equilibration steps described in the paper, it used different force constants to control the strength of restraint (e.g. 5.0 kcal/mol Å, 2.0 kcal/mol Å, 0.1 kcal/mol Å).

**Comment by lohedges** [comment]
This is a good suggestion, and should be easy to do. I just need to check that it can be set in all engines that we can support. Otherwise, I could always increase the default value of the current one is too small.

**Comment by kexul** [comment]
Would you mind adding the capability to apply restraints during `Minimization`?

**Comment by lohedges** [comment]
Assuming this is possible with all MD engines, I don't see why not. I'll take a look when I get time.

**Comment by lohedges** [comment]
It doesn't look like all engines allow you to fix the force constant for the restraint. (Perhaps they implement them in different ways.) Since I'd rather not add  a non-interoperable option, does it make sense to increase the default force constant of 1000 kJ/mol/nm^2 for GROMACS, which isn't actually that large.

**Comment by kexul** [comment]
> a non-interoperable option

OK, that's a reasonable tradeoff when trying to support different engines: we might lose some flexibility.  Thanks for the information.  

> does it make sense to increase the default force constant of 1000 kJ/mol/nm^2 for GROMACS

Sorry, I have no idea what the default value should be.

**Comment by lohedges** [comment]
Sorry, this was a general question. From reading around it sounds like the GROMACS default (1000) isn't that stiff and others have experienced issues too. I was just wondering what a more sensible value might be that doesn't cause other unintended consequences.
