### ISSUE TITLE
expose perturbed atoms for a given FEP setup

### ISSUE THREAD

**Issue by JenkeScheen** [michellab/BioSimSpace#249]
I have a use case where I'm trying to 'match' perturbations to each other, i.e. I have one perturbation as a reference, and n other perturbations and I'm trying to find the perturbation that matches the reference - related to https://github.com/michellab/BioSimSpace/issues/218. It turns out to actually be quite complex and one way I imagine could work is by finding out what atoms are perturbed between lambda 0 and 1. 

I think what would really help in this case (and potentially for other users too) is to be able to expose the morph information contained in Sire that is normally written to somd.pert. This data looks like this:
```
...
    atom
        name           Cl17
        initial_type   cl
        final_type     c3
        initial_LJ     3.46595 0.26380
        final_LJ       3.39771 0.10780
        initial_charge -0.10343
        final_charge   0.70019
    endatom
    atom
        name           DU01
        initial_type   du
        final_type     c3
        initial_LJ     0.00000 0.00000
        final_LJ       3.39771 0.10780
        initial_charge -0.00000
        final_charge   -0.06981
    endatom
...
```
in this case the relevant information could be returned as a list, e.g. [..., [cl, c3], [du, c3], ...]. This would allow the user to easily extract some valuable information on the perturbation being set up, such as 
- the number of atom type changes
- for each atom type change, the change in atom properties (size, weight, etc)
- match perturbation patterns by finding corresponding/similar lists (my use case)

Would it be possible to get this information before the `BSS.FreeEnergy.Relative()` or even the `BSS.Protocol.FreeEnergy()` step? I think if not then potentially it would be simpler for me to just write a quick `somd.pert` parser.

**Comment by lohedges** [comment]
Do you think it would be more flexible to just return a list of the indices of the perturbed atoms so the user could then extract whatever properties for the atoms in the lambda=0 and lambda=1 states? Alternatively, we could return a list of dict objects, where the dict for each perturbed atom contains the properties listed in the SOMD pert file. This would be a little more specific, so I guess it could be expose _secrectly_ to begin with, e.g. with a `molecule._getPerturbation()` or `molecule._getPerturbedAtoms()` method.

**Comment by lohedges** [comment]
You could also just extract the two end states using `merged._toRegularMolecule(is_lambda1=False/True)`, then compare the molecules directly. I guess I worry about adding some functionality that is _too_ specific to a use case, where there is already the flexibility to do everything with a bit of work.

**Comment by JenkeScheen** [comment]
hey @lohedges, you might be right in that this functionality could be a bit too specific. With the current setup would it be possible to get the perturbed atom information (indices, e.g.) from `merged._toRegularMolecule(is_lambda1=False/True)`?

I agree that either returning indices or returning a list of dicts would be a better idea. I do think there could be cases where getting an idea of the LJ/Coulomb changes for a perturbation can be valuable information, but it might be a bit too low-level for regular FEP practicioners.

**Comment by lohedges** [comment]
I just extracted the part of the SOMD pert writer that works out the perturbation indices and added it as a private method of `Molecule`. You can now do `molecule._getPerturbationIndices()` to get the indices, then use those indices to work out what's changed for each atom (if you want more detail).

**Comment by JenkeScheen** [comment]
great, thanks for picking this up so quickly! I'll see if I can complete my use case with this, will post results here.

**Comment by lohedges** [comment]
No problem. Thankfully it simply involved copying four lines of existing code into a separate function. To get additional information you could do something like:

```python
# Get indices of perturbed atoms.
idxs = merged._getPerturbationIndices()

# Work out which of the indices correspond to a change in atom type (ambertype).
atom_type_changed = [merged.getAtoms()[idx]._sire_object.property("ambertype0") ==  \
                     merged.getAtoms()[idx]._sire_object.property("ambertype1") \
                     for idx in idxs]

# How many types changed? (Result will be unique to your perturbation, obviously.)
print(atom_type_change.count(True))
3
```

**Comment by JenkeScheen** [comment]
Hi @lohedges, this has allowed me to finally solve my use case (after ~2 months of failed attempts..), thanks loads! Is there any chance that you could push the current devel to conda so that I can use it in my workflow? (it uses a conda install of BSS as there are a few painful libraries I have to deal with such as tensorflow)

**Comment by lohedges** [comment]
That's great to hear. Glad it was of use, especially since it was such a simple addition. Yes, I'll re-run the CI now. I hadn't realised that it didn't build. For some reason Azure thought that the CI should be skipped, even though `***NO_CI***` wasn't included in the commit message?

Cheers.

**Comment by lohedges** [comment]
I'm not sure, I guess it depends on what information is available in the input files that you load. At present, the way in which we are specifying perturbed atoms comes from SOMD, so requires AMBER specific properties to be present, i.e. the ligands need to have been parametrised with an AMBER style force field. Starting from a bare PDB or Mol2 file, I'm not sure we'd have enough information. (We might be able to tell if the element or charge change, but I'm not sure if this would be 100% reliable.)

**Comment by JenkeScheen** [comment]
Thanks, I'll keep that in mind. If at any point in the future we need to speed up our algorithm this should be good option.

**Comment by JenkeScheen** [comment]
hey @lohedges, the `mapping` only contains atom indices of MCS atoms, right? I'd tried this approach before but failed to get atom-type information on non-MCS parts of the ligand pair. So your example would only produce matches where atoms are substituted within the MCS I think.

**Comment by lohedges** [comment]
Yes, that's right, it's only the MCS atoms. But you could also loop over the atom indices that aren't in the mapping to figure out what else changes, e.g. to see what dummy atoms are in each end state.

**Comment by JenkeScheen** [comment]
But then if I'm looping over non-MCS atom indices how can I make sure that the atom pairs I see are atoms that are actually matched in the perturbation? Apologies, I don't seem to be very good at understanding this kind of syntax..

So, for example for a given perturbation I have (by parameterising and using `merged._getPerturbationIndices()`) these atom type changes:
```[['ca', 'nh'], ['ca', 'cx'], ['ha', 'du'], ['ha', 'du'], ['ha', 'du'], ['ha', 'du'], ['ha', 'du'], ['ha', 'du'], ['du', 'cx'], ['du', 'cx'], ['du', 'ca'], ['du', 'ca'], ['du', 'ha'], ['du', 'ha'], ['du', 'ha'], ['du', 'hn'], ['du', 'h1'], ['du', 'hc'], ['du', 'hc'], ['du', 'hc'], ['du', 'hc'], ['du', 'ha'], ['du', 'ha']]```, so 23 atoms are changing type.

Using the `mapping` approach I only get one atom type change, presumably within the MCS:
`[['Carbon (C, 6)', 'Nitrogen (N, 7)']]` 

mol0 atoms:
```[<BioSimSpace.Atom: name='C1', molecule=65 index=0>, <BioSimSpace.Atom: name='C2', molecule=65 index=1>, <BioSimSpace.Atom: name='C3', molecule=65 index=2>, <BioSimSpace.Atom: name='C4', molecule=65 index=3>, <BioSimSpace.Atom: name='C5', molecule=65 index=4>, <BioSimSpace.Atom: name='C6', molecule=65 index=5>, <BioSimSpace.Atom: name='H1', molecule=65 index=6>, <BioSimSpace.Atom: name='H2', molecule=65 index=7>, <BioSimSpace.Atom: name='H3', molecule=65 index=8>, <BioSimSpace.Atom: name='H4', molecule=65 index=9>, <BioSimSpace.Atom: name='H5', molecule=65 index=10>, <BioSimSpace.Atom: name='H6', molecule=65 index=11>]```

mol1 atoms:
```[<BioSimSpace.Atom: name='C1', molecule=67 index=0>, <BioSimSpace.Atom: name='C2', molecule=67 index=1>, <BioSimSpace.Atom: name='C3', molecule=67 index=2>, <BioSimSpace.Atom: name='C4', molecule=67 index=3>, <BioSimSpace.Atom: name='N1', molecule=67 index=4>, <BioSimSpace.Atom: name='C5', molecule=67 index=5>, <BioSimSpace.Atom: name='C6', molecule=67 index=6>, <BioSimSpace.Atom: name='C7', molecule=67 index=7>, <BioSimSpace.Atom: name='C8', molecule=67 index=8>, <BioSimSpace.Atom: name='C9', molecule=67 index=9>, <BioSimSpace.Atom: name='H1', molecule=67 index=10>, <BioSimSpace.Atom: name='H2', molecule=67 index=11>, <BioSimSpace.Atom: name='H3', molecule=67 index=12>, <BioSimSpace.Atom: name='H4', molecule=67 index=13>, <BioSimSpace.Atom: name='H5', molecule=67 index=14>, <BioSimSpace.Atom: name='H6', molecule=67 index=15>, <BioSimSpace.Atom: name='H7', molecule=67 index=16>, <BioSimSpace.Atom: name='H8', molecule=67 index=17>, <BioSimSpace.Atom: name='H9', molecule=67 index=18>, <BioSimSpace.Atom: name='H10', molecule=67 index=19>, <BioSimSpace.Atom: name='H11', molecule=67 index=20>]```

Would I have to loop over `mol0` and `mol1` indices, and then for indices that are not in `mapping` (i.e. non-MCS) find matching ones? The non-MCS atom matching information isn't available before `BSS.Align.merge()` AFAIK? And that function only accepts parameterised ligands.

**Comment by lohedges** [comment]
In the above atom changes, anything where you see a change to a dummy means that an atom from molecule0 _isn't_ mapped to anything in molecule1 in the MCS. Similarly, when you see `du` as the first entry, it means that the atom in molecule0 doesn't map to anything in molecule0. The ordering of dummy atoms in the end state are the same as in the original molecules, since they are _unmapped_.

If you want to explore dummy atoms using that mapping alone, you could do something like the following:

```python
# Explore the to dummy perturbations.
for idx, atom in enumerate(molecule0.getAtoms()):
    if idx not in mapping.keys():
        print(f"{atom} changes to dummy")

# Now do the same for molecule1 to find the from dummy perturbations.
for idx, atom in enumerate(molecule1.getAtoms()):
    if idx not in mapping.values():
        print(f"{atom} changes from dummy")
```

From your output you can see that you miss atom type changes for carbon atoms when the molecule isn't parameterised, i.e. you've only captured the `ca` to `nh` ambetype change, not the change from `ca` to `cx`. This would be another limitation of examining the unparameterised perturbation.

**Comment by JenkeScheen** [comment]
Thanks @lohedges, I'll have to find alternatives for our workflow as I do need to find a way get the complete atom-type-changing information from  a perturbation (i.e. the info returned from `merged._getPerturbationIndices()`) without parameterising the input ligands first.
