### ISSUE TITLE
Crystal waters and solvation

### ISSUE THREAD

**Issue by dlukauskis** [michellab/BioSimSpace#252]
Hey Lester, I have a question/need help with solvating a protein-ligand system while including crystal waters. I have no problem actually including them in the system, but I don't like the extra waters that gromacs adds around the ligand. I think they would really mess with my simulations, while I'm really confident in those xtal waters. 

Is there any way to remove the GMX solvent around a ligand. while maintaining the crystal water? I'm including [a ZIP](https://github.com/michellab/BioSimSpace/files/7617427/bss_solv.zip) with all the files and a pymol session to illustrate what I mean. Thanks a bunch.

**Comment by dlukauskis** [comment]
This is a sufficient fix, I preserve the ligand resname, so knowing the ligand resname is not an issue. I can't seem to make the search function find the waters around the ligand, though.

```
unwanted_waters = solvated.search("water within 7 angstrom of resname UNK") 
```

Just gives me 

```
ValueError: 'Invalid search query: 'water within 7 angstrom of resname UNK'
```

**Comment by lohedges** [comment]
Sorry, I've just edited the query above. I had included a duplicate word. Yes, for some reason the direct water distance search doesn't work, but you can search for waters, then do a distance search within that result, e.g.:

```python
unwanted_waters = solvated.search("water and mols within 7 angstrom of resname UNK")
``` 
You could probably just do the following too:

```
unwanted_waters = solvated.search( mols within 7 angstrom of resname UNK")
```

However, this would pick up ions too, although I doubt they would be present in the region in which you are searching.

**Comment by dlukauskis** [comment]
That does the job of removing the GMX waters around the ligand, but the xtal waters are now in the wrong place because the protein's coordinates are reset after solvation... I'll hack it, I can close this thread. Thanks for the help, Lester!

**Comment by lohedges** [comment]
No problem. Unfortunately we now need to shift the original coordinates to get things to work properly across the MD engines that we support. Originally we had translated to solvate, then translated back again afterwards, but this caused issues with periodic boundary conditions.

Just to note that the position of the xtal waters _should_ be preserved in the solvated system if you include them during solvation. This means that, assuming you store their indices, you can extract them from the solvated system before removing any unwanted waters added by GROMACS. That way they'll be in the correct position when you re-add them.

Cheers.

**Comment by dlukauskis** [comment]
Hmmm, solvation doesn't preserve the molecule numbers...

```
for molecule in xtal_waters:
    molecule_number = molecule.getResidues()[0].moleculeNumber()
    print(molecule_number)
```
I get 
```
195408
195413
195415
195438
195423
195421
195426
195428
195429
195412
195417
195410
195416
195437
195432
195411
195418
195422
195427
195420
195425
195430
195435
195409
195414
195419
195424
195431
195434
195433
195436
```
While 
```
for mol in solvated[:40]:
    molecule_number = mol.getResidues()[0].moleculeNumber()
    print(molecule_number)
```
Gives
```
195406
195407
195441
195442
195443
195444
195445
195446
195447
195448
195449
195450
195451
195452
195453
195454
195455
195456
195457
195458
195459
195460
195461
195462
195463
195464
195465
195466
195467
195468
195469
195470
195471
208475
208476
208477
208478
208479
208480
208481
```
The first two mols are the protein and ligand, while the next dozen or so mols are the xtal waters, but with different numbers. Is there a way of setting indices to the xtal waters before adding them to the system so I can filter them out during the removal? I can see that `index` for all of the molecules in the solvated system are set to 0.

**Comment by lohedges** [comment]
Sorry, the underlying numbers will be different since we create a new system with unique numbers. However, the order in the system should be preserved, so if you extract the molecules with the same _python_ index from the solvated system, it should match the one from the original system. Let me know if this isn't the case.

**Comment by dlukauskis** [comment]
Ah, yes, that worked. Thanks again.
