### ISSUE TITLE
FEP error calculation

### ISSUE THREAD

**Issue by annamherz** [michellab/BioSimSpace#257]
Hello! I was wondering why in the _relative.py the error for a transformation is calculated using:
```
        # Measure.
        error0 = _math.sqrt((pmf[-1][2].magnitude() * pmf[-1][2].magnitude()) +
                            (pmf[ 0][2].magnitude() * pmf[ 0][2].magnitude()))

        # Reference.
        error1 = _math.sqrt((pmf_ref[-1][2].magnitude() * pmf_ref[-1][2].magnitude()) +
                            (pmf_ref[ 0][2].magnitude() * pmf_ref[ 0][2].magnitude()))

        # Error for free-energy difference.
        error = _math.sqrt((error0 * error0) + (error1 * error1)) * _Units.Energy.kcal_per_mol

```
where the `pmf[ 0][2].magnitude()` and `pmf_ref[ 0][2].magnitude()` are 0 as its the standard error for lambda 0.0 from the values returned using analyse_engine. Effectively it ends up with `error0 =pmf[-1][2].magnitude()` and ` error1 =pmf_ref[-1][2].magnitude()` so the error from the final lambda window from the values returned. I was just wondering if there is a particular reason  `pmf[ 0][2].magnitude()` and `pmf_ref[ 0][2].magnitude()` are included?
The same is for:
` free_energy = (pmf[-1][1] - pmf[0][1]) - (pmf_ref[-1][1] - pmf_ref[0][1])`
where ` pmf[0][1]` and `pmf_ref[0][1]` are also 0 as its the PMF at lambda 0.
In both cases, are these included just incase the PMF and error for lambda 0.0 are non zero?

**Comment by lohedges** [comment]
Thanks for the question. Yes, it's just a generalised function that works with arbitrary input, not just the _expected_ output of the analysis routines within BioSimSpace, which (as you say) will have zero values for the lambda = 0 windows. I wasn't sure if this was true of _all_ analysis engines (if we were to add support for more) and also wanted the user to be able to pass in their own data and get back a meaningful result, i.e. not just use our own internal analysis functions as a pre-requisite.

**Comment by annamherz** [comment]
Okay, thank you!
