### ISSUE TITLE
Linux build keeps timing out

### ISSUE THREAD

**Issue by lohedges** [michellab/BioSimSpace#264]
As of the most recent commit, the Azure Linux build keeps timing out. See [here](https://dev.azure.com/michellab/BioSimSpace/_build/results?buildId=1608&view=logs&j=07371142-1dc2-5cab-83eb-30ac1c997b87) for an example.

This is largely due to a _huge_ amount of time being taken during the _build_ stage. This should be quick, since it simply a Docker pull, then installing BioSimSpace into the Miniconda within the container, then pushing back to Docker Hub. I wonder if there is some throttling going on somewhere? If so, we might need to rethink the pipeline. The macOS build doesn't have this problem since the build takes place outside of Docker.

**Comment by chryswoods** [comment]
I guess that there may be some throttling. Docker could be throttling pulls from Azure or other clouds in a similar way that anaconda throttled conda...

**Comment by lohedges** [comment]
Here's the Dockerfile for this stage of the build:

```
# This image is used to build the latest version of the devel
# branch of BioSimSpace.

FROM siremol/sire-devel:latest

WORKDIR $HOME

USER $FN_USER

# Disable Sire analytics.
ENV SIRE_DONT_PHONEHOME=1 \
    SIRE_SILENT_PHONEHOME=1

# Update to the latest version
RUN git clone https://github.com/michellab/BioSimSpace

RUN cd BioSimSpace && git checkout devel && git pull

RUN cd BioSimSpace/python && \
    $HOME/sire.app/bin/python setup.py install

# Clean up so that the Docker image size is minimised
RUN $HOME/sire.app/bin/conda clean -tipy

ENTRYPOINT [bash]
```

It gets to the last part (the Conda clean) after about 3 minutes, then takes some time between 2 and 3 hours to complete. I can't understand why the clean would take that long (or why it has started taking so long). At first I thought it was a push being slow, but we don't push the updated image back up until later in the pipeline.

**Comment by lohedges** [comment]
Actually, it might be Anaconda throttling during the installation stage, since we installing the conda dependencies as a post setup "finally" step. Any throttling on top of the ridiculous time it takes to resolves dependencies would likely cause the problem. Bah!

**Comment by lohedges** [comment]
Closing since we've now moved to GitHub actions for CI.
