### ISSUE TITLE
There is no perturbations template for the molecule with name WAT available templates are [ LIG ].

### ISSUE THREAD

**Issue by kexul** [michellab/BioSimSpace#267]
## Steps to Reproduce
Input files: 
[temp.zip](https://github.com/michellab/Sire/files/7863171/temp.zip)

Code: 
1. Build the system by BioSimSpace: 
```python 
p0 = str(list(Path(work_dir).glob(f'*0.prm7'))[0])
p1 = str(list(Path(work_dir).glob(f'*1.prm7'))[0])
r0 = str(list(Path(work_dir).glob(f'*0.rst7'))[0])
r1 = str(list(Path(work_dir).glob(f'*1.rst7'))[0])

morph = BSS.IO.readPerturbableSystem(p0, r0, p1, r1)

sys = BSS.Solvent.tip3p(morph, [3*BSS.Units.Length.nanometer]*3, ion_conc=0.154, work_dir=f'{work_dir}/Solvation')
protocol = BSS.Protocol.FreeEnergy(num_lam=3)
BSS.FreeEnergy.Relative(sys, protocol=protocol, work_dir=f'{work_dir}/test', engine='somd', setup_only=True)
```

2. Run `somd-freenrg -C somd.cfg -t somd.prm7 -c somd.rst7 -m somd.pert -p CUDA` in the lambda_* folder, output: 
```
Exception 'SireError::invalid_key' thrown by the thread 'master:main'.
There is no perturbations template for the molecule with name WAT available templates are [ LIG ].
Thrown from FILE: /home/sireuser/Sire/corelib/src/libs/SireIO/perturbationslibrary.cpp, LINE: 1171, FUNCTION: SireMol::Molecule SireIO::PerturbationsLibrary::applyTemplate(const SireMol::Molecule&) const
```
Files generated in lambda_0.0000: [temp (2).zip](https://github.com/michellab/Sire/files/7863176/temp.2.zip). 

I've seen similar failure information in this issue https://github.com/michellab/Sire/issues/353 , but I didn't find any clue yet. 
The ligand is at the end of the topology, which does not match the `perturbed residue number = 1` in the config file.

**Comment by lohedges** [comment]
Note that I'll also need to apply the fix in the C++ layer, since it will be far too slow for large systems in in Python.

**Comment by kexul** [comment]
Awesome! I'll test it immediately.

**Comment by kexul** [comment]
Great, worked like a charm! 🎉 🎉 🎉

**Comment by kexul** [comment]
Not sure if it's related, I'm getting another error during MD: 
```
###====================somd-freenrg run=======================###                                                                       
Starting somd-freenrg run...                                                                                                            
200000 moves 10 cycles, 4000 ps simulation time                                                                                         
                                                                                                                                        
Cycle =  1                                                                                                                              
                                                                                                                                        
Traceback (most recent call last):                                                                                                      
  File "/data/miniconda3/envs/uii/share/Sire/scripts/somd-freenrg.py", line 146, in <module>                                            
    OpenMMMD.runFreeNrg(params)                                                                                                         
  File "/data/miniconda3/envs/uii/lib/python3.7/site-packages/Sire/Tools/__init__.py", line 176, in inner                               
    retval = func()                                                                                                                     
  File "/data/miniconda3/envs/uii/lib/python3.7/site-packages/Sire/Tools/OpenMMMD.py", line 1701, in runFreeNrg                         
    system = moves.move(system, nmoves.val, True)                                                                                       
UserWarning: Exception 'SireError::invalid_cast' thrown by the thread 'master:main'.                                                    
Cannot cast from an object of class "SireVol::Cartesian" to an object of class "SireVol::PeriodicBox".                                  
Thrown from FILE: /home/sireuser/Sire/corelib/src/libs/SireBase/property.cpp, LINE: 202, FUNCTION: void SireBase::Property::throwInvalid
Cast(const char*) const   
```

**Comment by kexul** [comment]
I just copied the latest commit to my local _devel_ branch, maybe I should switch to your feature branch completely?

**Comment by lohedges** [comment]
Yes, I forgot to copy across the existing properties from the system. Just add the following within the except block:

```python
for prop in self._sire_object.propertyKeys():
    system.setProperty(prop, self._sire_object.property(prop))
```

Without this, there is no box information so the simulation defaults to an infinite Cartesian space.

**Comment by kexul** [comment]
> for prop in self._sire_object.propertyKeys():
    system.setProperty(prop, self._sire_object.property(prop))

Thanks, it works! I'll switch to your feature branch tomorrow~:hugs:

**Comment by lohedges** [comment]
You won't be able to use the feature branch since it relies on some new Site functionality that hasn't been pushed yet. Hopefully everything will be available some time next week.

Cheers.

**Comment by kexul** [comment]
```python
for prop in self._sire_object.propertyKeys():
    system.setProperty(prop, self._sire_object.property(prop))
```

Hi @lohedges , the code works for solvation leg, but failed when I construct the complex system by `protein+morph`. It runs fine under `morph+protein`. 

Just like the behavior I've encountered here: https://github.com/michellab/BioSimSpace/issues/32#issuecomment-872264779

**Comment by lohedges** [comment]
Thanks, I'll take a look next week. Just to confirm, is the problem present with the example system in the other thread? Is it an issue with the presence of crystal waters again? (Just want to make sure that I have a system to test.)

**Comment by kexul** [comment]
> is the problem present with the example system in the other thread?  Is it an issue with the presence of crystal waters again? 

Nope, water placement is fine 😄 . The error was triggered by the position of the perturbable molecule. 

I've attached the files I used to test, you may use the following code to reproduce: 
[temp (3).zip](https://github.com/michellab/BioSimSpace/files/7868741/temp.3.zip)

```python
p0 = str(list(Path(work_dir).glob(f'*0.prm7'))[0])
p1 = str(list(Path(work_dir).glob(f'*1.prm7'))[0])
r0 = str(list(Path(work_dir).glob(f'*0.rst7'))[0])
r1 = str(list(Path(work_dir).glob(f'*1.rst7'))[0])

morph = BSS.IO.readPerturbableSystem(p0, r0, p1, r1)

sys = BSS.Solvent.tip3p(morph, [3*BSS.Units.Length.nanometer]*3, ion_conc=0.154, work_dir=f'{work_dir}/Solvation')
complex_template = BSS.IO.readMolecules([f'{work_dir}/complex_template.gro', f'{work_dir}/complex_template.top'])
protocol = BSS.Protocol.FreeEnergy(num_lam=3)

# sys + complex_template, which would fail when running somd-freenrg
BSS.FreeEnergy.Relative(sys + complex_template, protocol=protocol, work_dir=f'{work_dir}/test1', engine='somd', setup_only=True)

# complex_template+sys, which runs fine
BSS.FreeEnergy.Relative(complex_template+sys, protocol=protocol, work_dir=f'{work_dir}/test2', engine='somd', setup_only=True)

```

**Comment by kexul** [comment]
> I've just tested using my feature branch and it's working for me. In the SOMD config file I see: 
perturbed residue number = 808

Glad to hear that! With the _devel_ branch, the residue number is always 1 here. 

> Apologies for this. It's been a pain dealing with some of SOMD's quirks whilst still striving for decent performance, i.e . needing to ensure that molecule ordering is always consistent following every molecular manipulation, and that constituent names are unique when combining molecules / systems.

Thank you for maintenance and continual improvement on this project, much appreciated!  I'm sorry for your pain, but it does make my life much easier! 😂 Thanks again!
