### ISSUE TITLE
Bad alignment of ligands in different conformational states

### ISSUE THREAD

**Issue by msuruzhon** [michellab/BioSimSpace#269]
Hi,

Recently I have had to work with merged molecules, where the two endstates are not necessarily nicely input in the same conformation, but are instead taken from equilibrated structures which may or may not be in the same conformation. When this is not the case, however, `rmsdAlign()` produces (somewhat expectedly) very distorted structures (input files attached [here](https://github.com/michellab/BioSimSpace/files/7906271/test.zip)):

<img width="519" alt="image" src="https://user-images.githubusercontent.com/36005076/150365178-abd9ac63-8d71-49e9-a6aa-79a691d558cb.png">

For reference, the nitrogen at the bottom is bonded to the carbon at the top to form a nitrile. Unfortunately, in this case an initial MD minimisation is not sufficient to completely remove this distortion when AMBER is used, so the subsequent simulations crash.

I just wanted to make sure this is expected behaviour? @jmichel80 we have been talking about aligning structures after equilibration and I was wondering whether you were running into similar issues in your protocols? I would personally expect a rigid RMSD-based algorithm to fail when the conformers are significantly different but there might be something I am missing.

Cheers.

**Comment by lohedges** [comment]
Have you tried using the  [flexAlign](https://biosimspace.org/api/generated/BioSimSpace.Align.flexAlign.html#BioSimSpace.Align.flexAlign) function? (You can also use this during `matchAtoms` when scoring the mappings.) This often produces better alignment when the conformations aren't well matched.

**Comment by msuruzhon** [comment]
Thanks @lohedges . I didn't get the chance to try `flexAlign` becase we don't have a license for FKCOMBU and I'll have to check if we can get one. I am currently using [a simple routine I wrote some time ago](https://github.com/protocaller/ProtoCaller/blob/master/ProtoCaller/Wrappers/rdkitwrapper.py#L633) using `RDKit`, which basically constrains the mobile MCS atoms to have the same coordinates as the reference MCS and force field minimises the rest of the atoms before restoring all dummy dihedrals to their initial values before alignment. This procedure has so far served me well during my alchemical runs. @jmichel80 do you use `flexAlign` instead of `rmsdAlign` in your runs?

**Comment by lohedges** [comment]
FKCOMBU is BSD licensed and is bundled with the conda install of BioSimSpace. Let me know if the commands aren't working for some reason and I'll look into it for you.

**Comment by jmichel80** [comment]
Hi @msuruzhon I think generally we tend to use rmsdAlign, and fall back to flexAlign if that doesn't work. We haven't benchmarked yet on a scale that would allow us to recommend an automated approach.

**Comment by msuruzhon** [comment]
Thanks @lohedges I didn't know that, I will let you know if I have any issues.

@jmichel80 as we have opted for the other alignment algorithm I described above, I have uploaded the generated aligned and merged serialised `BioSimSpace` objects to the [RBFE repo](https://github.com/Exscientia/RBFEBenchmark/tree/main/Data/Tyk2/Input). Please let me know if you have any issues.
