### ISSUE TITLE
Parametrization fail for CathS ligands in seperate PDBs

### ISSUE THREAD

**Issue by JenkeScheen** [michellab/BioSimSpace#27]
We tried to naively parametrise 8 CatS ligands in separate pdb files. FESetup successfully parametrises them and if needed I can add the output as well, or make a test case on BioSimSpace examples. 

The code used for the parametrisation attempt was:
```python
import BioSimSpace as BSS
import os
import glob
ligs = ['108', '52', '67', '72', '71', '73', '20', '63']
for l in ligs:
    lig = BSS.IO.readMolecules('/home/jscheen/projects/D3R/data/FESetup/poses/'+l+'/ligand.pdb')
    mol_lig = lig.getMolecules()[0]
    lig_param = BSS.Parameters.parameterise(mol_lig, 'gaff2' ).getMolecule()
    failed = glob.glob('*.zip')
    if failed is not None:
        os.rename(failed[0], 'failed/'+l+'.zip')

```
The output generated was the essentially that every parametrisation failed. The failed zip files are attached as a whole zip archive and each ligand can be identified individually. 

Let me know if you need any more information, or you also require the FESetup output. 

BSS version is:
'2018.1.1+346.gdb8dc06'

[failed.zip](https://github.com/michellab/BioSimSpace/files/2405084/failed.zip)

**Comment by lohedges** [comment]
Could you try again using the latest version of the `devel` branch, or `feature-align`. Your version number (+346) is massively out of date (latest is +385) so doesn't contain any of the bug fixes and additional features that were added during my last visit to Edinburgh. Note that you'll also need to use the `feature-mapping` branch of Sire for all functionality to work properly.

If you run into the same problems, let me know and I'll look into things then. The latest version of BioSimSpace should give more detailed insight on the parameterisation failures.

Cheers.

**Comment by JenkeScheen** [comment]
I'm on the right branch now, but there seems to be an issue with loading Sire which prevents importing BSS. Will get back to you after that has been resolved.
