### ISSUE TITLE
Failed to run fep with somd: "no perturbations template"

### ISSUE THREAD

**Issue by ryankzhu** [michellab/BioSimSpace#275]
Hi. I've been running into an issue when running an fep with the following script: 

``` ruby
import BioSimSpace as BSS

ligand0 = BSS.Parameters.gaff2(BSS.IO.readMolecules('./input/' + 'CVD-0007756.pdb')[0], work_dir = "./reflig_par").getMolecule()
ligand1 = BSS.Parameters.gaff2(BSS.IO.readMolecules('./input/ligands/' + 'CVD-0012808.pdb')[0], work_dir = './lig_par').getMolecule()
protein= BSS.Parameters.ff14SB(BSS.IO.readMolecules(['./protein_par/leap.crd','./protein_par/leap.top'])[0], work_dir = "./protein_par_1").getMolecule()

mapping = BSS.Align.matchAtoms(ligand1, ligand0)
ligand1 = BSS.Align.rmsdAlign(ligand1, ligand0, mapping)
merged = BSS.Align.merge(ligand1, ligand0, mapping)
complx = merged + protein 

complex_sol = BSS.Solvent.tip3p(molecule = complx, box = 3*[80*BSS.Units.Length.angstrom])
merged_sol = BSS.Solvent.tip3p(molecule = merged, box = 3*[40*BSS.Units.Length.angstrom])

prot_bound = BSS.Protocol.FreeEnergy(timestep = 2*BSS.Units.Time.femtosecond,
                                     runtime = 100*BSS.Units.Time.picosecond,
                                     num_lam = 10)
fep_bound = BSS.FreeEnergy.Relative(complex_sol,
                                    prot_bound,
                                    engine = "somd",
                                    work_dir = "./somd/bound")

fep_bound.run()
fep_bound.wait()
```

A failure occurs when running the fep_bound but I'm not sure what does this mean: 
```
Exception 'SireError::invalid_key' thrown by the thread 'master:main'.
There is no perturbations template for the molecule with name WAT available templates are [ LIG ].
Thrown from FILE: /home/sireuser/Sire/corelib/src/libs/SireIO/perturbationslibrary.cpp, LINE: 1171, FUNCTION: SireMol::Molecule SireIO::PerturbationsLibrary::applyTemplate(const SireMol::Molecule&) const
```
The whole somd.out can be found here [somd.txt](https://github.com/michellab/BioSimSpace/files/7954056/somd.txt).

Many thanks.

**Comment by kexul** [comment]
It's the same issue that I've encountered here: https://github.com/michellab/BioSimSpace/issues/267, 
### solution 1: 
you may follow the quick fix that @lohedges has provided: https://github.com/michellab/BioSimSpace/commit/cbfb867f07d1405edfcf062caf9fbc3de6b6decb , remember to add these lines too:  
```python
for prop in self._sire_object.propertyKeys():
    system.setProperty(prop, self._sire_object.property(prop))
``` 
I've tested it, works perfectly. 

### solution 2: 
Switch to the [feature branch](https://github.com/michellab/BioSimSpace/tree/feature_python_tweaks), you may need to upgrade Sire to the latest version too.

### solution 3: 
Wait for the [feature branch](https://github.com/michellab/BioSimSpace/tree/feature_python_tweaks) to be merged and upgrade to the latest version of BioSimSpace and Sire. You may see the progress here: https://github.com/michellab/BioSimSpace/pull/273 

Good luck! 😉

**Comment by lohedges** [comment]
Thanks @kexul, that is indeed the correct process. Apologies for not yet merging these fixes into devel but I wanted to wait until the updated CI was working. Hopefully this will be done soon.

Cheers.

**Comment by ryankzhu** [comment]
Great it works perfectly! Thank you @kexul @lohedges for your help.
