### ISSUE TITLE
Advice on RBFE with different mapping for the water and the protein legs

### ISSUE THREAD

**Issue by bieniekmateusz** [michellab/BioSimSpace#278]
We're using a RBFE protocol ([link](https://github.com/cole-group/QUBE-SOMD-paper)) which I think is based on [your files here](https://github.com/michellab/BioSimSpace/tree/devel/nodes/playground).

In this protocol the `prepareFEP.py` script is run twice, once for the ligA-ligB in water, and once for the same perturbation in the protein pocket. We've noticed that there are subtle differences in the mapping occasionally between the two legs. I assume it's mostly different hydrogens. Could the relative binding free energy be skewed here by using a different mapping? I imagine this might be mostly fine when the groups can rotate, but we wonder if this is always the case. Or more specifically, whether sampling a slightly different alchemical path could skew the energies.

In our small sample of 18 perturbations, 10 had some differences. For these 10 cases, we rerun them this time using the same mapping across the two legs. 

The average forward-(-backward) was 0.47 (0.25) with the original data, when applying the same mapping it dropped to 0.29 (0.19) in the case of the protein leg. For the water leg the value increased by 0.03 (I interpret it to be the same). Although we're vary of the data sampling / spread here.

**Comment by lohedges** [comment]
Hi there, thanks for the question. Are you able to provide an example file where the mapping changes from run-to-run of the `matchAtoms` function. I imagine that there are two mappings (or more) with identical scores, so the _best_ mapping that is being returned is potentially dependent on the order that the mappings are returned by RDKit. If this is the case, then I should be able to add an additional sorting step following the scoring to ensure that the returned MCS is reproducible.

In general I would assume that you want to use an _identical_ mapping for both legs, unless there is some kind of molecular symmetry that makes the MCS degenerate. (Even then, there might be specifics of the molecular conformation within the binding pocket that makes one transformation different, although this _should_ be sorted out by appropriate sampling.)

**Comment by jmichel80** [comment]
Hi @bieniekmateusz  are the mappings not actually equivalent ? I don't think the differences in hysteresis you see are necessarily significant.   
When you run prepareFEP.py twice, is it on the same inputs (coordinates), or with ligA, ligB equilibrated separately every time ? There could be variability due to the RMSD scoring metric. If the coordinates are identiical between the two repeats I would expect the mappings to be identicals.

**Comment by bieniekmateusz** [comment]
@jmichel80 Indeed we have equilibration taking place before running the `prepareFEP.py` therefore the coordinates might be slightly different, which could create this issue in the mapping. I will attempt to change the order and then see if I can reproduce this issue. 

Here is one case where the hydrogens have a slightly different mapping:
https://pastebin.com/r8qDufSF
https://pastebin.com/Jsueg3yF
And here is one where a slightly different carbon is matched to a hydrogen:
https://pastebin.com/6pKKgaKA

Will follow up next week. Thanks

**Comment by bieniekmateusz** [comment]
Hi @jmichel80 , indeed having the equilibration in the protocol preceding the mapping appears to have caused the discrepancy based on the two cases I just checked with both approaches. Thanks.
