### ISSUE TITLE
GAFF2 cannot parametrise a properly formatted ligand file with specific atom types

### ISSUE THREAD

**Issue by mattaq31** [michellab/BioSimSpace#282]
Hi,

I have been having difficulties parametrizing a ligand file containing atoms such as Cl or F using the GAFF2 forcefield, where I would consistently get the following error:

`ValueError: The molecule contains the following ions: F. Please choose a 'water_model' for the ion parameters.`

I have also obtained a pre-parametrized ligand (attached), read this into BSS and re-saved it to file in PDB format.  Reading this file and attempting to parametrise using GAFF2 will also cause the same error to happen:

```python
import BioSimSpace as BSS

ligand_system = BSS.IO.readMolecules(['lig_1a.parm7', 'lig_1a.rst7'])  # reading in initial parametrized ligand

BSS.IO.saveMolecules("ligand_resaved", ligand_system, ["pdb"]) # saving back to file as a PDB

ligand_recon = BSS.IO.readMolecules('ligand_resaved.pdb') # re-reading

lig_recon = BSS.Parameters.gaff2(ligand_recon[0]).getMolecule()  # errors out here

```

Is the GAFF2 forcefield supposed to have these issues with these atoms?  I cannot specify a water model to the function as the input is not available in this particular forcefield function.  Thanks for your help!

Ligand_1a files: [lig_1a.zip](https://github.com/michellab/BioSimSpace/files/8104757/lig_1a.zip)

### Context

Operating System: macOS 12.2.1
Hardware: Macbook; Intel CPU and AMD GPU
BioSimSpace Installation method: conda, version 2022.1.0
GROMACS version: 2021.5
Ambertools version: 21.11, installed via conda
Python: 3.8

**Comment by lohedges** [comment]
Hi there,

Thanks for reporting. For protein force fields,  ion parameters are tied to a specific water model, hence the request to specify one when ions are present. I'm not sure of what is required for ligands (e.g. GAFF/GAFF2) but it looks like we are still applying the ion check regardless.

I'll be able to test this tomorrow and update the code accordingly, either removing the check when calling the GAFF/GAFF2 functions, or adding additional `water_model` options.

Cheers.

**Comment by lohedges** [comment]
I just did a quick check and can confirm that ion parameters are part of the GAFF/GAFF2 forcefields, so there is no need to include any additional files.I'll remove the ion check when GAFF/GAFF2 are called tomorrow and will let you now when an updated package is available.

**Comment by mattaq31** [comment]
Great, thanks!

**Comment by lohedges** [comment]
This is now fixed. An updated conda package should be available in half an hour or so.
