### ISSUE TITLE
Time taken for solvation is too long. Can I tweak any settings?

### ISSUE THREAD

**Issue by aniketsh** [michellab/BioSimSpace#290]
system=bss.IO.readMolecules(['system.top','system.gro'])[0]
box, angles = bss.Box.truncatedOctahedron(10 * bss.Units.Length.nanometer)
%time bss.Solvent.tip3p(system,ion_conc=0.1,box=box,angles=angles)

CPU times: user 23min 52s, sys: 12.3 s, total: 24min 4s
Wall time: 22min 43s

<BioSimSpace.System: nMolecules=23795>

**Comment by lohedges** [comment]
I've just tried this here using a random molecule and it does seem to take a surprisingly long time, even at the solvation stage, i.e. before ions have been added. I'll try with an older version of GROMACS. I'll also if something has changed in the way we recombine the solvated system on load, since we've needed to add some hacks to ensure unique residue and atom numbering for consistency with other simulations. (This is slow in Python, but should be done in the C++ layer.)

**Comment by lohedges** [comment]
Yes, it looks like the slow part is recombining the loaded system, not the actual solvation / ion generation part. I'll see what I can do to speed this up.

Thanks for reporting. This was problematic before, but I thought I had replaced all of the slow code with C++ calls.

Cheers.

**Comment by lohedges** [comment]
Okay, this should now be fixed. This was slow due to a check for unique molecule numbers when combining systems. An updated conda package should be available from our dev channel within the hour.

```
conda update -c conda-forge -c michellab/label/dev biosimspace
```

Thanks again for reporting.

**Comment by jmichel80** [comment]
Once again brilliant job, thanks !

**Comment by lohedges** [comment]
The CI borked so I'll need to re-run tomorrow. Also noticed a slight issue with the duplicate molecule number check, depending on what is used to construct a system, e.g. a list of molecules, etc. Will fix this too.

**Comment by aniketsh** [comment]
It is much faster for cubic box now but "truncatedOctahedron" doesnt work anymore.

%time solvated = bss.Solvent.tip3p(molecule=system,box=3*[7*bss.Units.Length.nanometer],ion_conc=0.1)
CPU times: user 59.9 s, sys: 2.25 s, total: 1min 2s
Wall time: 37.2 s

**Comment by lohedges** [comment]
Thanks for the update. This will be fixed tomorrow. There have been some minor internal changes that clearly haven't been updated in all places.

I'll post an updated once it's resolved.

**Comment by lohedges** [comment]
This should now be fixed. Let me know if you run into any further issues.

Cheers.
