### ISSUE TITLE
Parameterising SMILES using OpenFF gives molecule with no ligand name 

### ISSUE THREAD

**Issue by lohedges** [michellab/BioSimSpace#299]
With AmberTools we get a single residue with name `UNL` (unlabeled):

```python
import BioSimSpace as BSS

toluene = BSS.Parameters.gaff("Cc1ccccc1").getMolecule()
toluene.getResidues()
[<BioSimSpace.Residue: name='UNL', molecule=4, index=0, nAtoms=15>]
```

With OpenFF, the residue is unnamed:

```python
toluene = BSS.Parameters.openff_unconstrained_2_0_0("Cc1ccccc1").getMolecule()
toluene.getResidues()
[<BioSimSpace.Residue: name='', molecule=2, index=0, nAtoms=15>]
```

This causes problems when writing to GROMACS topology files, since there is an empty string in the `[ moleculetype ]` record, e.g.:

```
[ moleculetype ]
; name  nrexcl
  3
```

This gives the following when parsed by `grommp`:

```
ERROR 1 [file solvated.top, line 47]:
  Expected a molecule type name and nrexcl
```

I'll update the code so it adds a default residue name, e.g. `LIG`. I'm not sure if we'd need a way to ensure unique names if the user parametrised multiple ligands, then combined them.

**Comment by chryswoods** [comment]
It is worth looking at what I am doing assigning molecule names in ``feat_web``. In the new load function I am setting default names if a molecule doesn't have a name. This is either set from the name of the residue, if the molecule only has one residue, or the base name of the file (calling the second and subsequent such molecules as basename_2, basename_3 etc). So loading a PDB code will name the protein molecule after the code, while naming the waters "WAT". Loading aladip.top/crd names the alanine dipeptide as aladip and the waters as WAT.

My thoughts for loading from a smiles string is that the molecule name should be the smiles string itself.

**Comment by lohedges** [comment]
Great, that makes sense. I'll follow that convention here too.

**Comment by chryswoods** [comment]
Take a look at the indexing molecules page in the tutorial for how to select molecules from a system / SelectorMol. This provides some suggestions for how to find ligands.
