### ISSUE TITLE
Use pandas.DataFrame in BSS.Protocol.FreeEnergy

### ISSUE THREAD

**Issue by xiki-tempula** [michellab/BioSimSpace#302]
**Is your feature request related to a problem? Please describe.**
I'm interested in using BSS to implement Gromacs absolute binding free energy calculations.
So it would be nice if I could set the bonded-lambda, coul-lambda and vdw-lambda at the same time in BSS.Protocol.FreeEnergy._lambda_vals.

However, currently the lambda values are stored as a list, which means we cannot have more than one lambda value.

**Describe the solution you'd like**
I'm interested in changing the BSS.Protocol.FreeEnergy._lambda_vals to a pandas dataframe. So one could have a different columns for bonded-lambda, coul-lambda and vdw-lambda. If nothing is specified, it will just be a dataframe with a single column of fep

I wonder what is your thought on this and the potential impact on other modules.

**Comment by xiki-tempula** [comment]
I haven't used SOMD but I guess if we have this as pandas.DataFrame all these

**Comment by xiki-tempula** [comment]
@lohedges 
So for this DataFrame, I was thinking of having column names as fep, coul, vdw, bonded, (restraint, mass, temperature, if needed) https://manual.gromacs.org/documentation/current/user-guide/mdp-options.html#mdp-fep-lambdas.

> for RBFE can we just continue to use the same setup procedure for GROMACS if we choose to support these additional options, or do we need to tweak other settings, or even the perturbed topology?

For Gromacs then this will map directly to the corresponding XXX-lambdas, if the default list is being given, they will just be mapped to fep-lambdas. So for Gromacs this won't be a problem.

> Also, how do things work with, say, AMBER? Do the same options translate?
To be honest, I don't know but I know that you could support splitting the coul and vdw.

I guess, we could make it that if a list is given, it will just be mapped to column `fep`, then the current input and output could be preserved.

**Comment by jmichel80** [comment]
The ways the lambda schedule is split is fairly engine specific. For SOMD you do that by setting up separate pert files. 
I think you could have a high level config option 'split' or 'concerted' and then map decisions to specific engine specific protocols. That is not offering the ability to implement the same lambda schedule across different engines (which would be meaningless due to other engine specific settings), but offering the ability to decide on a type of simulation methodology to use with a given engine. 
Provided the default protocols are sensibly chosen by an expert in a given code, and that power users have the ability to override defaults that should be ok.

**Comment by xiki-tempula** [comment]
@lohedges I have implemented the new class based on the BSS.Protocol.FreeEnergy() and I'm interested in testing it. I wonder if do you mind help me to find where is the unit test for the BSS.Protocol? I cannot seems to find it in the test. Thank you.

**Comment by xiki-tempula** [comment]
@lohedges Yes, this is the plan. Thank you for the explanation.

**Comment by xiki-tempula** [comment]
@lohedges Thanks. I wonder if the Sandpit is ready to be working on now? I think this concept was mentioned the day before yesterday and I was told to hold off until it is ready.

**Comment by lohedges** [comment]
Ah yes, probably hold off until the PR is merged. It should be easy enough for you to copy your working files into the sandpit once it is ready.

**Comment by xiki-tempula** [comment]
@lohedges Thanks. Do you mind pin me when it is ready? Thank you.

**Comment by lohedges** [comment]
Yes, will do.

**Comment by lohedges** [comment]
The sandpit has now been merged. Once @msuruzhon has set up your fork you will be able to work within the sandpit space. (Either from your own development branch, or separate feature branches as appropriate.)

**Comment by xiki-tempula** [comment]
@lohedges Thanks.

**Comment by xiki-tempula** [comment]
@fjclark I think it might be better to take the discussion here as it is really difficult to follow long discussions in the google docs.

Yes I do agree that concatenating the BSS.Protocol.FreeEnergy is a good approach if one were to do the transformations in stages.
```
bonded-lambda = 0.0 0.5 1.0 1.0 1.0 1.0 1.0
coul-lambda   = 0.0 0.0 0.0 0.5 1.0 1.0 1.0
vdw-lambda    = 0.0 0.0 0.0 0.0 0.0 0.5 1.0
```
However, it could not cope with the case of 
```
bonded-lambda = 0.0 0.1 0.3 0.5 1.0 1.0 1.0
coul-lambda   = 0.0 0.0 0.0 0.5 1.0 1.0 1.0
vdw-lambda    = 0.0 0.0 0.0 0.0 0.0 0.5 1.0
```
where we wish to have some overlap to have save some windows. But this might be something that is engine specific.

I was thinking of having BSS.Protocol.FreeEnergy._lambda_vals as pandas DataFrame, then all of the lambda information could be stored and the current BSS.Protocol.FreeEnergy will be a special case where the pandas DataFrame only has one column.

**Comment by fjclark** [comment]
@xiki-tempula definitely. Thanks for clarifying - I hadn't seen this issue.
