### ISSUE TITLE
Allow Gromacs tests to be run on a single rank

### ISSUE THREAD

**Issue by xiki-tempula** [michellab/BioSimSpace#305]
# Prerequisites
So it might be good to specify `-ntmpi 1` for gromacs test runs as some gromacs runs might fail on machine with more cores.

Please answer the following questions for yourself before submitting an issue.

**YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version (devel branch, or dev Conda package).
- [x] I checked the documentation and found no answer.
- [x] I checked to make sure that this issue has not already been filed.

# Expected Behavior

`pytest -v test`
will work.

# Current Behavior

On my machine with 10 cores. The test

```
test_gromacs
  test_equilibrate
  test_heat
  test_production
```

will fail giving the error

```
-------------------------------------------------------
Program:     gmx mdrun, version 2022
Source file: src/gromacs/domdec/domdec.cpp (line 2232)
MPI rank:    0 (out of 10)

Fatal error:
There is no domain decomposition for 10 ranks that is compatible with the
given box and a minimum cell size of 0.8525 nm
Change the number of ranks or mdrun option -rdd or -dds
Look in the log file for details on the domain decomposition

For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors
-------------------------------------------------------
```
The easiest solution would be: When runing these tests, add the flag `-ntmpi 1` to the `gmx mdrun`

**Comment by lohedges** [comment]
Thanks for this. My local build of GROMACS is compiled without MPI support so I don't experience this issue. I'll add this when I get a chance since it would be good to allow tests to run against different builds.

Cheers.

**Comment by xiki-tempula** [comment]
@lohedges Thanks. I could verify that now the unit tests are passing.
