### ISSUE TITLE
Allow the BSS.Protocol.FreeEnergy to have the method getLambdaIndex

### ISSUE THREAD

**Issue by xiki-tempula** [michellab/BioSimSpace#309]
**Is your feature request related to a problem? Please describe.**
So usually, one need Lambda, LambdaValues and LambdaIndex to run free energy calculations.
Currently there isn't a getLambdaIndex method and this is done via LambdaValues.index(Lambda) https://github.com/michellab/BioSimSpace/blob/devel/python/BioSimSpace/Process/_gromacs.py#L565

Supporting this method would mean that we could change something within the BSS.Protocol.FreeEnergy (like use pandas.DataFrame for the exs stuff) without changing the public API.

**Describe the solution you'd like**
Allow BSS.Protocol.FreeEnergy to have the method getLambdaIndex().

**Comment by lohedges** [comment]
Yes, this sounds like a good idea. When it was written, the index was only ever needed for GROMACS, i.e. SOMD explicitly states the lambda value in the configuration file. This is why the index was only ever extracted within `Process.Gromacs`.

**Comment by xiki-tempula** [comment]
@lohedges Thanks.

**Comment by lohedges** [comment]
One of the reasons for this was that we didn't have an easy way to save perturbable systems, so any FEP simulation tests would need to reproduce the whole setup process, which is tested elsewhere. No we have pickling support this isn't an issue, so it would be good to add tests for running very short FEP simulations with the supported engines to check that things have been setup correctly. I'll put this on my TODO list.

Cheers.

**Comment by xiki-tempula** [comment]
@lohedges Excellent, Thank you.
