### ISSUE TITLE
About setting the Sire property

### ISSUE THREAD

**Issue by xiki-tempula** [michellab/BioSimSpace#316]
I think this might be that I don't fully understand how to modify the Sire mol so I wonder if I could get some help.
Lets say I have a BSS.mol object and I set certain property to True, it will not be the same as True.

```
mol = BSS.Parameters.openff_unconstrained_2_0_0(
    "c1ccccc1").getMolecule()
mol_edit = mol._sire_object.edit()
mol_edit.setProperty("test", True)
mol._sire_object = mol_edit.commit()
assert mol._sire_object.property("test") == True
```
However, this assertion will give False

**Comment by lohedges** [comment]
This is because the property is of type `Sire.Base._Base.BooleanProperty`, not `bool`, so the assertion fails when making an equality comparison between the two. When making the assertion you'll need to call the `.value()` method on the property to get the underlying value, in this case as a `bool` type.

```python
assert mol._sire_object.property("test").value() == True
```

**Comment by xiki-tempula** [comment]
@lohedges Thanks. When looking at the code, I see that `mol_edit.setProperty("test", Sire.Base.wrap(True))`, I wonder if this is the recommended practice or just `mol_edit.setProperty("test", True)` is enough?

**Comment by lohedges** [comment]
Currently we need to use the `wrap` function to correctly convert Python types to their Sire equivalent. Soon this will be unnecessary, as @chryswoods has added functionality to do the conversion for you implicitly within `wrap` itself. (There will also be far greater flexibility in what can actually be stored as a molecular property.)

**Comment by xiki-tempula** [comment]
@lohedges It seems that on my computer that `mol_edit.setProperty("test", True)` works. 
So your suggestion is that I should do `mol_edit.setProperty("test", Sire.Base.wrap(True))` to avoid any unexpected outcome.

**Comment by lohedges** [comment]
Perhaps @chryswoods' changes came in on a more recent merge, I can't quite remember. For now I'd use `wrap` for consistency with the existing code. I plan on updating things like this bit-by-bit over a period of time.

Cheers.

**Comment by lohedges** [comment]
Yes, a general search by molecular properties would be really useful :+1:
