### ISSUE TITLE
About the property of the decoupled molecule

### ISSUE THREAD

**Issue by xiki-tempula** [michellab/BioSimSpace#317]
**Is your feature request related to a problem? Please describe.**
I'm interested in implementing a method that would mark a molecule to be decoupled for annihilated in the ABFE calculations.

The end result would be that 

- when writing the Gromacs topology, the Gromacs topology is the same as the case when the ligand is not decoupled/annihilated.
- When writing the Gromacs mdp file, I will need to know whether the `molecule name of the ligand` and whether the `charge` and `LJ` are present in the start or the end stage and whether the intra-molecular force should be retained.

**Describe the solution you'd like**
I was thinking of an general interface as

```
decoupled_ligand = BSS.align.decouple(ligand, kargs)
solvated = BSS.Solvent.tip3p(molecule=decoupled_ligand, box=3*[10*BSS.Units.Length.nanometer])
protocol = BSS.Protocol.FreeEnergy()
freenrg_free = BSS.FreeEnergy.Absolute(solvated, protocol, work_dir="output")
```

Where the decoupled_ligand has such property

```
decoupled_ligand._sire_object.property('charge0') == True
decoupled_ligand._sire_object.property('charge1') == False
decoupled_ligand._sire_object.property('LJ0') == True
decoupled_ligand._sire_object.property('LJ1') == False
decoupled_ligand._sire_object.property('intramol') == False
decoupled_ligand.isPerturbable() == True
```

I wonder if I could get some advice of whether this interface is reasonable.

**Comment by lohedges** [comment]
You can check that a molecule has a particular property by using, e.g. `mol._sire_object.hasProperty("property")`. Your `decouple` function could delete the property (using `.removeProperty` on an editable version of the molecule, then committing the changes) the you could check for the existing of, e.g. `charge1`, later on. If you just need to flag that the molecule has been decoupled, then you could add this as an extra property, e.g.:

```python
edit_mol.setProperty("is_decoupled", Sire.Base.wrap(True))
```

(I guess you might need some other attribute that says to which end state it applies, so you could have 0 or 1, or leave the property unset if it's not decoupled.)

**Comment by xiki-tempula** [comment]
@lohedges Thanks for the advice. I wonder if would you suggest that I flag it with `is_decoupled` or just use the `is_perturbable`? I noticed that `is_perturbable` is used and checked widely so I wonder if I shall just piggyback on this.

**Comment by xiki-tempula** [comment]
@lohedges So I'm trying to mimic the 
https://github.com/michellab/BioSimSpace/blob/devel/python/BioSimSpace/_SireWrappers/_system.py#L704
by doing `mol._sire_object.search("decoupled")`

But doing this a molecule with `mol._sire_object.property('is_decoupled').value() == True` would just give me cryptic error so I think using the `is_perturbable` might be easier than setting up the new `is_decoupled`.

**Comment by xiki-tempula** [comment]
@lohedges Thanks. I think is_perturbable is a bit complicated as one always expect `molecule0` and `molecule1`. 
I'm currently trying the decoupled approach. I wonder what are the things that I need to look for?
Currently, I think the flag `is_decoupled` is not preserved when using toSystem().

```
mol._is_decoupled = True
system = mol.toSystem()
for mol in system:
    assert mol._is_decoupled == True
```
Will fail. You could see my current implementation here https://github.com/Exscientia/BioSimSpace/pull/5.

**Comment by chryswoods** [comment]
As I commented in #316 I think I can add this functionality as part of the improvements to search via the `feat_web` branch. It will be relative easy to add something like;

```
mols = system["property is_decoupled == True"]
```

and then for a user token to be added to create a nicer interface, e.g.

```
sire.search.add_user_token("is_decoupled", "property is_decoupled == True")
```

The user token could be added by BSS, and then in your code you will be able to write

```
mols = system["is_perturbable"]
```

Does this look like the right type of API? If so, I will see what I can do over the next week or so.

**Comment by xiki-tempula** [comment]
@chryswoods Thank you. Sorry, I'm a bit confused as to what is at the BSS level and what is at the Sire level?

`mols = system["property is_decoupled == True"]`

I would imagine that this goes through a system and return a list of molecules where `is_decoupled == True`

`sire.search.set_token("is_decoupled", "property is_decoupled == True")`

Is this the same as the current
`edit_mol.setProperty("is_decoupled", Sire.Base.wrap(True))`

Or the above two commands are all at Sire level and at BSS level, doing mols = system["is_decoupled"] would give me a list of molecules where `is_decoupled == True`?

**Comment by chryswoods** [comment]
Sorry - I am talking about the Sire level. BSS is built on top of Sire. Lester pulls some of the functionality from Sire up to BSS. Our plan is to (eventually) pull the new search functionality from Sire up into BSS so that you will be able to eventually achieve what you have written. The aim would be that you could use `setProperty` on a molecule, e.g. `edit_mol.setProperty("is_decoupled", True)`, and then search for this molecule with `system["property is_decoupled == True"]` from the BSS layer or Sire layer.

(note that another change we are making is simplifying the naming of some functions, with `edit_mol.setProperty` simplifying to `edit_mol.set("is_decoupled", True)`. This is part of a whole raft of changes that are taking place in Sire that we will be slowly rolling out in BioSimSpace. For now, continue to use the existing BSS API. I am just letting you know about this in this issue so that we remember this when we come to update BSS to the new API)
