### ISSUE TITLE
Help with running a minimisation

### ISSUE THREAD

**Issue by xiki-tempula** [michellab/BioSimSpace#323]
# Prerequisites

I tried to run an energy minimisation with the dev branch and gmx 2022.1 but I got the issue of 
`Killing job  /Users/zwu/build/gromacs/2022.1/bin/gmx mdrun -v -deffnm gromacs`

If I go to the work_dir, I could excute the command  `/Users/zwu/build/gromacs/2022.1/bin/gmx mdrun -v -deffnm gromacs` and the energy minimisation would finish normally.

## Steps to Reproduce

```python
import BioSimSpace as BSS
from BioSimSpace.Protocol import Minimisation
from BioSimSpace import Process
m = BSS.Parameters.openff_unconstrained_2_0_0("c1ccccc1").getMolecule()
solvated = BSS.Solvent.tip3p(molecule=m,
                             box=3 * [3 * BSS.Units.Length.nanometer])
protocol = Minimisation()
process = Process.Gromacs(solvated, protocol)
process.run()
```

## Failure logs

[param_eror.zip.zip](https://github.com/michellab/BioSimSpace/files/8755701/param_eror.zip.zip)

## Context

* Operating System: macOS.
* Installation method: source

**Comment by lohedges** [comment]
You've not added `process.wait()` after `process.run()`. If you don't have this in your script, then it will just exit the script and terminate the process, hence the error that you are seeing. You need to add `.wait()` when you aren't working interactively. If you are in a notebook, it is fine to just use `.run()`, after which you can monitor the progress of the process.

Cheers.

**Comment by xiki-tempula** [comment]
@lohedges It would still fail with the same erro if I have process.wait() at the end.

**Comment by lohedges** [comment]
Sorry, also realised that you need to use `process.start()`, not `process.run()`. If you look at the docs, e.g. [here](https://biosimspace.org/api/generated/BioSimSpace.Process.Gromacs.html#BioSimSpace.Process.Gromacs.run), you'll see that `process.run()` is a convenience function to create an run a _new_ process, i.e. you can use it to re-run an existing process, or pass in a completely new system and protocol. Importantly, it returns a _new_ process object, so you would need to capture this object, which you are not doing. (This exists for consistency with the `BioSimSpace.MD.run` interface, i.e. an engine specific version of the engine agnostic MD interface.)

Replacing `process.run()` with `process.start()` and adding `process.wait()` works for me.

**Comment by xiki-tempula** [comment]
@lohedges Thank you.
