### ISSUE TITLE
__contain__ cannot handle protein

### ISSUE THREAD

**Issue by xiki-tempula** [michellab/BioSimSpace#333]
If one combine protein with ligand, the __contain__ will fail.

```
import BioSimSpace.Sandpit.Exscientia as BSS
>>> ligand = BSS.IO.readMolecules(BSS.IO.glob("test/input/ligands/ligand01*")).getMolecule(0)
>>> protein = BSS.IO.readMolecules(['test/input/molecules/1jr5.crd', 'test/input/molecules/1jr5.top']).getMolecule(0)
>>>print(ligand in (protein+ligand).toSystem()
False
```

**Comment by lohedges** [comment]
This is because it creates a _new_ system, with new and unique molecule numbers, so the original ligand ID doesn't match the one in the new system. You can test whether an object is contained by a system from which it was extracted, not a system that it has become part of.

**Comment by xiki-tempula** [comment]
@lohedges I'm not quite sure if I agree with this logic. But further testing shows that 

`print(ligand in (protein+ligand).toSystem())` gives `False`
`print(ligand in (ligand+protein).toSystem())` gives `True`

**Comment by lohedges** [comment]
Hmm, that's strange. I'll try to see what's gone wrong during the `toSystem()` conversion.

**Comment by lohedges** [comment]
Still don't understand why it doesn't work, but have fixed things by bypassing Sire.

**Comment by xiki-tempula** [comment]
@lohedges I think there might still be some issue with the internal logical
Say we have ligand and protein and combine them to form a system

```
>>> system = (protein+ligand).toSystem()
>>> print(system._sire_object.getMoleculeNumbers())
[MolNum(637), MolNum(636)]
>>> print(protein in system)
True
>>> print(ligand in system)
False
>>> print(ligand._sire_object.number())
MolNum(636)
>>> ligand_new = system[1]
>>> print(ligand_new in system)
True
>>> print(ligand_new._sire_object.number())
MolNum(636)
```

So it seems that even though MolNum is the same you can see different results.

**Comment by lohedges** [comment]
Hmmm, this is very srange. The added unit test check for _exactly_ this behaviour, i.e. creating two systems that combine molecules in opposite orders, then check that both molecules are contained in each system. However, I see the same behaviour for your example, and the molecule numbers are present in the list of `mol_nums`.

I'll debug further and get back to you when I have an update.

**Comment by xiki-tempula** [comment]
@lohedges Sorry the previous message is my fault.
Do you mind do the same thing to the molecule as well, please? It seems that the same thing would occur at molecule level as well.

**Comment by lohedges** [comment]
Could you try removing all your `__pycache__` files and trying again. It's now working properly for me at this end. Add I did was add a print statement to the `__contains__` method of `BioSimSpace._SireWrappers.System` to check that the numbers were indeed as expected. On doing this the code worked as expected and it continues to do so after removing the print statement.

Very strange.

**Comment by lohedges** [comment]
Oh, sorry, I realise that you were experiencing the same thing :man_facepalming:  I'll look into the atom issue.

**Comment by xiki-tempula** [comment]
@lohedges I have cleaned and the code to reproduce the behaviour is

```
In [1]: import BioSimSpace.Sandpit.Exscientia as BSS

In [2]: ligand = BSS.IO.readMolecules(BSS.IO.glob("test/input/ligands/ligand01*")).getMolecule(0)

In [3]: protein = BSS.IO.readMolecules(['test/input/molecules/1jr5.crd', 'test/input/molecules/1jr5.top']).getMolecule(0)

In [4]: system = (protein+ligand).toSystem()

In [5]: ligand.getAtoms()[0] in system.getMolecule(1)
Out[5]: False

In [6]: ligand.getAtoms()[0]._sire_object.molecule().number() == system.getMolecule(1)._sire_object.number()
Out[6]: True
```

**Comment by lohedges** [comment]
Okay, I think I've fixed it. In the molecule `__contains__` the comparison was at the `Molecule` level, not by number. I'll push another PR and you can test at your end.

Cheers.

**Comment by xiki-tempula** [comment]
@lohedges Thanks
