### ISSUE TITLE
Inconsistencies in name of GROMACS executable

### ISSUE THREAD

**Issue by lohedges** [michellab/BioSimSpace#34]
Typically, this is called `gmx` and is what is searched for by BioSimSpace. However, it looks like people often rename this depending on their cluster environment, e.g. `gmx_mpi`. Perhaps we should provide an option to allow this to be set (you can already for with `Process.Gromacs`) while being careful to preserve interoperability. We don't want people hard coding this in their nodes, so perhaps a command-line option or environment variable would be best.

**Comment by oliverdutton** [comment]
I've hit this issue, BioSimSpace finds Amber perfectly, but not GROMACs as it's under GMXRC I think. I have tried putting it into process as 

process = BSS.Process.Gromacs(system, protocol, exe = "/cm/shared/apps/Gromacs-4.6.5/intel/bin/GMXRC")

but it still fails 
![Screen Shot 2019-06-06 at 12 56 15 PM (2)](https://user-images.githubusercontent.com/44170519/59031039-83222d00-885a-11e9-9a48-656ff4f88118.png)


(I do have the module loaded, I've checked and this does link to the correct folder version the module fits to)

**Comment by oliverdutton** [comment]
(Sorry, I know the tutorials were meant to be run on the BioSimSpace notebook server and I'm forcibly trying to run them independently leading to specific problems (one of the reasons you set up the server to begin with) but the server was shut down after the workshops)

**Comment by lohedges** [comment]
No problem. The notebook server is actually still active, but we've had issues with it being overloaded since the workshop week. (It was scaled down to handle less users.) We are currently working on a way of making it more robust.

I think that your problem is that `GMXRC` is not the GROMACS binary, rather a shell RC file that is used to set the right paths to GROMACS within your current shell environment. (Normally this would be sourced in `$HOME/.bashrc` or whatever.) I would have thought that this file would be done when you load the GROMACS module but perhaps this isn't the case on BC3 (It is on BC4 but I've not tried on BC3).

Could you try doing this manually before launching Jupyter, i.e.:

```sh
source /cm/shared/apps/Gromacs-4.6.5/intel/bin/GMXRC
```

After this, you can look at the result of:

```sh
echo $PATH
```

You should see that the GROMACS bin directory is listed somewhere in the output. This means that BioSimSpace will now be able to find the `gmx` (or `gmx_mpi`) executable when it searches for GROMACS.

Otherwise, you could try passing `exe = "/cm/shared/apps/Gromacs-4.6.5/intel/bin/gmx"` (or `gmx_mpi`) when creating the process instead.

**Comment by oliverdutton** [comment]
Your fix worked perfectly. The source line 'source /cm/shared/apps/Gromacs-4.6.5/intel/bin/GMXRC' fixes it (double checked). (Though echo $PATH returns nothing)

Yes, I'm on BC3. 

Thanks,
Oliver
