### ISSUE TITLE
Align.viewMapping bug?

### ISSUE THREAD

**Issue by ZCLIU-2022** [michellab/BioSimSpace#364]
Seems that there is a bug in the Functions of BioSimSpace.Align.viewMapping, 

In the line 1410 of  BioSimSpace/python/BioSimSpace/Align/_align.py, as below:

1410    view.addModel(_Chem.MolToMolBlock(**rdmol0**), "mol1", viewer=viewer1)

may  rewrite as view.addModel(_Chem.MolToMolBlock(**rdmol1**), "mol1", viewer=viewer1) ,  so the viewer0 can display ligand1 and viewer1 display ligand2.

Is that so ?

**Comment by lohedges** [comment]
Thanks for catching this. I'm not sure how this occurred, since there were no issues with an earlier version of the viewer, e.g.:

![py3Dmol_mcs](https://user-images.githubusercontent.com/648557/180151475-fc6e3830-ae55-4389-a169-6a5ee9a6a69d.png)

I'll fix this now.
