### ISSUE TITLE
Exposing mapping from merged molecule to parent molecules

### ISSUE THREAD

**Issue by kexul** [michellab/BioSimSpace#375]
**Is your feature request related to a problem? Please describe.**
In my daily practice of doing free energy perturbation, the most cumbersome part is checking the atoms' mapping. Though BioSimSpace's `matchAtoms` works great for most of my molecules, I still need to check the mappings manually sometimes. 

**Describe the solution you'd like**
With the knowledge of the mapping between the merged molecule to parent molecules, we could use the merged molecule alone to tune the mapping, instead of checking mol1 and mol2 together.  Below is a merged molecule and its parents. If I want to merge atom `7` and atom `58`, we could look up the mapping dictionary with simple python scripting,  find the corresponding atom index of their parents ( `6` and `36` in this case), then update the MCS. 
Pseudocode: 
```python
mcs = matchAtoms(mol1, mol2)
# we want to add atom `7` and atom `58` into mcs
mol1_idx = merged2parents[7][0]
mol2_idx = merged2parents[58][1]
mcs.update({mol1_idx: mol2_idx})
```
<details>
  <summary>mapping dictionary</summary>
Format: {atom index of merged molecule: [ atom index of molecule1, atom index of molecule2]}

```
{1: [0, 0],
 2: [1, 1],
 3: [2, 21],
 4: [3, 22],
 5: [4, 20],
 6: [5, None],
 7: [6, None],
 8: [7, None],
 9: [8, None],
 10: [9, 9],
 11: [10, 10],
 12: [11, 11],
 13: [12, 12],
 14: [13, 13],
 15: [14, 14],
 16: [15, 19],
 17: [16, 18],
 18: [17, 3],
 19: [18, 2],
 20: [19, 23],
 21: [20, 24],
 22: [21, 25],
 23: [22, 26],
 24: [23, 28],
 25: [24, 51],
 26: [25, 29],
 27: [26, 30],
 28: [27, 31],
 29: [28, 32],
 30: [29, 33],
 31: [30, 34],
 56: [None, 7],
 57: [None, 8],
 58: [None, 36],
 59: [None, 38],
 60: [None, 39],
 61: [None, 40],
 62: [None, 41]}
```

</details>

![企业微信截图_1662384084948](https://user-images.githubusercontent.com/5920217/188459883-3b32a31b-f03b-40bb-b4cc-d3a9f15e5e82.png)

![image](https://user-images.githubusercontent.com/5920217/188460662-c07e435f-f0dd-435a-bf00-6475b3d4cacf.png)

**Describe alternatives you've considered**
We could use the `viewMapping` function, but it did not show the atom index that is not in the MCS. And we still need to drag the parent molecules together to find the atom mapping, it's easy to get lost 😵 . 
![企业微信截图_1662385802331](https://user-images.githubusercontent.com/5920217/188464706-d1d84efc-fb06-4e5f-b754-c394d99f2852.png)

**Comment by lohedges** [comment]
Hi there. Apologies for not getting to this before closing. Have you come up with a satisfactory solution for your needs? Perhaps you've just implemented the `merged2parents` functionality in your own fork.

Cheers.

**Comment by kexul** [comment]
Hi @lohedges , yes, I've implemented it in my own fork. 😄 I think it might be too user-specific so I closed it as completed, thanks for your attention.
