### ISSUE TITLE
Forward and backward mapping not symmetric

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#38]
Taking two compounds then the number of matched atoms should be the same going forwards and backwards. 

Example to reproduce this:
```python
import BioSimSpace as BSS
mol1 = BSS.IO.readMolecules('CatS_79.pdb').getMolecules()[0]
mol2 = BSS.IO.readMolecules('CatS_195.pdb').getMolecules()[0]
mapping = BSS.Align.matchAtoms(mol1, mol2)
print (len(mapping))
mapping_back = BSS.Align.matchAtoms(mol2, mol1)
print (len(mapping_back))
```

Output:
```
32
61
```
Files needed are attached. 

[mapping.zip](https://github.com/michellab/BioSimSpace/files/2514839/mapping.zip)

**Comment by lohedges** [comment]
I've tried all other pairs of the CatS ligands and this is the only one that is non-symmetric. There appears to be nothing particularly special about the ligands. Strange.

**Comment by lohedges** [comment]
This is now fixed following the addition of the RDKit prematch. I'll close for now, but it would still be good to understand the reason for the problem in the underlying Sire MCS code.
