### ISSUE TITLE
The correct way of setting up the env for BSS for CI

### ISSUE THREAD

**Issue by xiki-tempula** [michellab/BioSimSpace#383]
# Prerequisites

So I was trying to run a CI (https://github.com/Exscientia/BioSimSpace/blob/devel/.github/workflows/Sandpit_exs.yml) to install the BSS env and then run the unit tests, which used to work well.

```
          mamba install -c conda-forge -c michellab/label/dev biosimspace python=3.7 --only-deps
          mamba install -c conda-forge ambertools alchemlyb gromacs

          cd python
          python setup.py develop
          cd ..
```

However, I'm getting https://github.com/Exscientia/BioSimSpace/actions/runs/3054389815/jobs/4926223442

```
Traceback:
test/Sandpit/Exscientia/Align/test_align.py:4: in <module>
    import BioSimSpace.Sandpit.Exscientia as BSS
python/BioSimSpace/__init__.py:200: in <module>
    from . import Align
python/BioSimSpace/Align/__init__.py:43: in <module>
    from ._align import *
python/BioSimSpace/Align/_align.py:78: in <module>
    from .._SireWrappers import Molecule as _Molecule
python/BioSimSpace/_SireWrappers/__init__.py:39: in <module>
    from ._atom import *
python/BioSimSpace/_SireWrappers/_atom.py:[18](https://github.com/Exscientia/BioSimSpace/actions/runs/3054685142/jobs/4926880747#step:6:19)7: in <module>
    from ._molecule import Molecule as _Molecule
python/BioSimSpace/_SireWrappers/_molecule.py:38: in <module>
    from Sire import IO as _SireIO
../../../miniconda3/envs/bss_build/lib/python3.7/site-packages/Sire/IO/__init__.py:16: in <module>
    from Sire.IO._IO import *
E   ImportError: dlopen(/Users/runner/miniconda3/envs/bss_build/lib/python3.7/site-packages/Sire/IO/_IO.so, 2): Library not loaded: @rpath/libcrypto.1.1.dylib
E     Referenced from: /Users/runner/miniconda3/envs/bss_build/lib/libhdf5.[20](https://github.com/Exscientia/BioSimSpace/actions/runs/3054685142/jobs/4926880747#step:6:21)0.dylib
E     Reason: image not found
------------------------------- Captured stdout --------------------------------
```

I wonder what is the right way of setting up the env for BSS? Thanks.

**Comment by lohedges** [comment]
That's strange. Do you get the same `libcripyto` error, i.e. `Library not loaded: @rpath/libcrypto.1.1.dylib`, if you install BioSimSpace as normal, i.e. not just doing `--only-deps` and doing a manual install into the environment afterwards.

We don't depend directly on the `cryptography` package, so I can only assume that one of our dependencies has been built against a different version without updating their version number, or the SONAME of `libcrypto` has changed without the version changing, e.g. perhaps they have changed build system. (This is one of the annoying problems with conda, i.e. you can correctly specify your own dependencies, but you are at the mercy of the maintainers of those packages doing the same.)

I'll try to dig out a macBook later to see if I can reproduce the issue locally.

Cheers.

**Comment by xiki-tempula** [comment]
@lohedges Thanks. I will have a try.
BTW, it seems that the test after test/Sandpit/Exscientia/Gateway/test_string.py::test_invalid_allowed[ipsum] PASSED [ 58%] seems to stuck indefinitely (timeout after 6 hours) https://github.com/Exscientia/BioSimSpace/actions/runs/3054684983/jobs/4926880215, I wonder if you have encountered similar issue with the CI?

**Comment by lohedges** [comment]
Does it repeatedly hang on the same test? I've experienced plenty of random CI hangs and failures before, but these have largely been resolved by re-running the job.

**Comment by lohedges** [comment]
I've just tested a clean install on an intel macBook and I don't see the same error:

```
mamba create -n biosimspace-dev -c conda-forge -c michellab/label/dev python=3.7 biosimspace
conda activate biosimspace-dev
mamba install -c conda-forge ambertools alchemlyb gromacs
```

I end up with the following version of `libcrypto`, which doesn't appear to cause any issues.

```
(biosimspace-dev) ~/Downloads ❯❯❯ ls -l ~/opt/miniconda3/envs/biosimspace-dev/lib/libcrypto.*
-rwxrwxr-x  1 lester  staff  3955064 15 Sep 10:05 /Users/lester/opt/miniconda3/envs/biosimspace-dev/lib/libcrypto.3.dylib
lrwxr-xr-x  1 lester  staff       17 15 Sep 10:05 /Users/lester/opt/miniconda3/envs/biosimspace-dev/lib/libcrypto.dylib -> libcrypto.3.dylib
```

Out of interest, I see you are doing a `conda install` of the BioSimSpace dependencies into an existing environment, rather than resolving them at the point a new environment is _created_. This might end up with a different set of dependencies to the ones that I am seeing, e.g. if there are existing packages in the environment that require different versions of the same dependency.

One other thing to note is that the installation of the additional dependencies, `gromacs` etc., on the second line could break the environment by downgrading/upgrading one of the libraries that Sire or its dependencies are built against. It would be better to do everything in a _single_ install command so that everything can be resolved at once.

If you still experience issues, could you try replacing doing a regular install, then just re-install your development version of BioSimSpace over the top of the existing package, i.e.:

```
mamba create -n biosimspace-exs -c conda-forge -c michellab/label/dev python=3.7 biosimspace ambertools alchemlyb gromacs
conda activate biosimspace-exs

cd python
python setup.py develop
cd ..
```

**Comment by xiki-tempula** [comment]
I have tried 
```
mamba create -n biosimspace-exs -c conda-forge -c michellab/label/dev python=3.7 biosimspace ambertools alchemlyb gromacs
conda activate biosimspace-exs

cd python
python setup.py develop
cd ..
```
However, it seems that the conda biosimspace is being picked up instead of the newly installed one.
https://github.com/Exscientia/BioSimSpace/actions/runs/3059268430/jobs/4936445067

**Comment by lohedges** [comment]
Ah, that's annoying. Perhaps try uninstalling the `biosimspace` package before doing the manual install, or simply deleting the package from the environment.

**Comment by xiki-tempula** [comment]
@lohedges I did this in https://github.com/Exscientia/BioSimSpace/pull/25
But it seems that all of them stuck at the the test after test/Sandpit/Exscientia/Gateway/test_string.py::test_invalid_allowed[ipsum] PASSED [ 58%]

**Comment by lohedges** [comment]
Okay, that's strange as it's a pretty basic test. I'll try to reproduce locally. For reference, I have also been seeing hangs for other (unrelated) tests as described in my comment [here](https://github.com/michellab/BioSimSpace/pull/356#issuecomment-1234003607). Again, there is no reason why this test should hang and the same test works fine on a different branch.

**Comment by lohedges** [comment]
Everything works fine for me locally on Linux. I checked the memory usage while the tests were running and at maximum it went up by 1.5GB over my baseline, so I don't think that would cause any hangs during the CI. (I think memory is currently limited to 7GB on Linux based images.)

**Comment by xiki-tempula** [comment]
Not relevant but I found one reason that my tests failed. For some reason conda gromacs will install double precision (gmx_d) by default (this was not the default behaviour previously). BSS will not recognise the gmx_d binary and it might be good to add this to the list of gmx binaries.

**Comment by xiki-tempula** [comment]
Ok the gromacs 2022.3 on conda-forge doesn't have the single precision build for OSX yet as it was uploaded yesterday.

**Comment by xiki-tempula** [comment]
Ok, it seems that 
test/Sandpit/Exscientia/IO/test_openff_gromacs.py::test_molecule_combine PASSED [ 57%]
will hang on ubuntu with py3.8

I wonder if you could reproduce this issue on the CI?

**Comment by lohedges** [comment]
This is the same test that I refer to in the link above. This fails for me locally using the `feature-web` branch, which is built against Sire 2023.0. The _same_ test passes when using `devel` and Sire 2022.2.0. I'll re-run the CI against the `feature-web` PR to see if the failure occurs.

**Comment by xiki-tempula** [comment]
I'm using the sire=2022.3.0 but it seems that it would still hang, I guess I will disable this test for now.

**Comment by lohedges** [comment]
Ah, didn't see that you only see the failure on Python 3.8, so perhaps it's unrelated to the Sire version. For the 2023.0 build I'm using my local development version of Sire, which is built using Python 3.9, so perhaps it _will_ work locally if I rebuild against Python 3.7. Will play around to see what's going on.

(I think the CI will have passed in the PR since GROMACS isn't installed on the runner, so the test is skipped.)

**Comment by xiki-tempula** [comment]
Great, test/Sandpit/Exscientia/IO/test_openff_gromacs.py::test_molecule_combine hangs locally for me on my Mac as well with Sire sire-2022.3.0-py38h01edc0c_10

**Comment by lohedges** [comment]
Thanks, presumably that's for Python 3.8+ too? I've now tested on Linux using clean Python 3.7, 3.8, and 3.9 environments, and the test only passes for Python 3.7. The others hang and CTRL-C'ing out gives the traceback reported in the PR thread, i.e.:

```
  Traceback (most recent call last):
    File "/home/lester/.conda/envs/biosimspace-dev/lib/python3.9/site-packages/openff/utilities/utilities.py", line 69, in wrapper
      importlib.import_module(package_name)
    File "/home/lester/.conda/envs/biosimspace-dev/lib/python3.9/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
  ModuleNotFoundError: No module named 'openff.interchange'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/lester/.conda/envs/biosimspace-dev/lib/python3.9/threading.py", line 980, in _bootstrap_inner
      self.run()
    File "/home/lester/.conda/envs/biosimspace-dev/lib/python3.9/threading.py", line 917, in run
      self._target(*self._args, **self._kwargs)
    File "/home/lester/.conda/envs/biosimspace-dev/lib/python3.9/site-packages/BioSimSpace/Parameters/_process.py", line 79, in _wrap_protocol
      protocol_function(process._molecule,
    File "/home/lester/.conda/envs/biosimspace-dev/lib/python3.9/site-packages/BioSimSpace/Parameters/Protocol/_openforcefield.py", line 283, in run
      omm_system = forcefield.create_openmm_system(off_topology)
    File "/home/lester/.conda/envs/biosimspace-dev/lib/python3.9/site-packages/openff/utilities/utilities.py", line 75, in wrapper
      return function(*args, **kwargs)
    File "/home/lester/.conda/envs/biosimspace-dev/lib/python3.9/site-packages/openff/toolkit/typing/engines/smirnoff/forcefield.py", line 1119, in create_openmm_system
      interchange = self.create_interchange(
    File "/home/lester/.conda/envs/biosimspace-dev/lib/python3.9/site-packages/openff/utilities/utilities.py", line 71, in wrapper
      raise MissingOptionalDependencyError(library_name=package_name)
  openff.utilities.exceptions.MissingOptionalDependencyError: The required openff.interchange module could not be imported. Try installing the package by running `conda install -c conda-forge openff-interchange`

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))
```

I'll try to figure out exactly where the hang occurs. For now, skipping the test is probably a good idea. Other OpenFF related functionality does appear to work in my Python 3.9 environment, so I'm not sure the traceback is helpful.

Cheers.

**Comment by xiki-tempula** [comment]
> Thanks, presumably that's for Python 3.8+ too?

Yes. And py3.7 works for me as well.

**Comment by lohedges** [comment]
Okay, the error message was helpful and the test now passes after installing `openff-interchange` into the environment, i.e.:

```
conda install -c conda-forge openff-interchange
```

I can only assume that they've split some required functionality out into a separate package, so we'll now need to add the interchage as an extra dependency alongside `openff-toolkit-base`. (I'm not sure when this changed happened since the test used to pass locally without issue.)

**Comment by xiki-tempula** [comment]
Yes, I have encountered the same issue some days ago in another repo.
Do you mind ping me when this dependency has been added to the conda release? So when one do `mamba install -c conda-forge -c michellab/label/dev biosimspace`, it is insatlled automatically.

**Comment by xiki-tempula** [comment]
Great. Thanks. I think py3.7 is fine as it uses an old version of openff.

**Comment by lohedges** [comment]
Conda packages are rolling out now. I'll need to re-trigger a few of the runs later due to some spurious failures. Hopefully everything should be completed by tomorrow.

**Comment by lohedges** [comment]
Only macOS Python 3.8 is repeatedly failing, this time with the following warning/errors:

```
Verifying transaction: ...working... done
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/osx-64::xorg-xproto-7.0.31-h35c211d_1007, conda-forge/osx-64::tk-8.6.12-h5dbffcc_0
  path: 'include/X11/DECkeysym.h'
...
```

(Same incompatibility warning for many other packages too.)

It looks like a conda issue to me. The build doesn't actually error, just times out after reporting many warnings along the lines of those above. Will see if I can find out what's going wrong.

**Comment by xiki-tempula** [comment]
I can verify that interchange is no longer needed as dependency.
