### ISSUE TITLE
Correction for funnel metadynamics

### ISSUE THREAD

**Issue by guidsari** [michellab/biosimspace#392]
Good morning,
I and a colleague were tinkering with your code for funnel metadynamics on BioSimSpace.
Specifically, we have already a free energy surface which needs to be corrected for the funnel shape and we were trying to understand your function for the energy correction.
We kept all the default values except for the length of the funnel, which we imposed to be 2.5 nm.
We understood the code computes the volumes of "square" slices of the funnel between the -1 and the +1 slices and then averages the two results (*0.5).
We then saw the correction with pi which brings back the slices to cone trunks (circular slices).
We don't understand however the 1660 conversion factor and what is the unit used for kt if nothing is declared.
We have a modified version of the script, we can send it to you in case you want to have a look.

    def getCorrection(self, proj_min=None, proj_max=None, delta=_Length(0.01, "nanometers")):
        """Get the funnel correction term. This is the correction factor for
           free-energy estimates that takes into account the reduction in
           entropy caused by the funnel restraint.
           Parameters
           ----------
           proj_min : :class:`Length <BioSimSpace.Types.Length>`
               The minimum coordinate along the projection axis of the funnel.
           proj_max : :class:`Length <BioSimSpace.Types.Length>`
               The maximum coordinate along the projection axis of the funnel.
           delta : :class:`Length <BioSimSpace.Types.Length>`
               The delta for integrating the volume.
           Returns
           -------
           correction : :class:`Energy <BioSimSpace.Types.Energy>`
               The funnel correction.
        """

        if proj_min is None:
            if proj_max is None:
                proj_max = self._upper_bound.getValue()
            else:
                if not isinstance(proj_max, _Length):
                    raise TypeError("'proj_max' must be of type 'BioSimSpace.Types.Length'.")

            # Default to the last 5 nanometers.
            proj_min = proj_max - _Length(5, "nanometers")

        else:
            if not isinstance(proj_min, _Length):
                raise TypeError("'proj_min' must be of type 'BioSimSpace.Types.Length'.")

        if proj_max is None:
            # Default to the upper bound.
            proj_max = self._upper_bound.getValue()

        else:
            if not isinstance(proj_max, _Length):
                raise TypeError("'proj_max' must be of type 'BioSimSpace.Types.Length'.")

        if proj_min >= proj_max:
            raise ValueError("'proj_min' must be less than 'proj_max'.")

        if not isinstance(delta, _Length):
            raise TypeError("'delta' must be of type 'BioSimSpace.Types.Length'.")

        if delta >= (proj_max - proj_min):
            raise ValueError("'delta' must be larger than 'proj_max' - 'proj_min'.")

        import numpy as _np

        # Create an array of 0.01 nm spaced points between the lower and upper bounds.
        coords = _np.arange(proj_min.nanometers().value(),
                            proj_max.nanometers().value(),
                            delta.nanometers().value()).tolist()

        # Get the extent values.
        funnel = [self.getExtent(_Length(x, "nanometers")).nanometers().value() for x in coords]

        # Now integrate the data.
        result = 0
        delta = delta.nanometers().value()
        for x, y in zip(funnel[:-1], funnel[1:]):
            result += (x**2 + y**2) * delta * 0.5

        # Work out the volume of the unbound area.
        volume = _Volume(_math.pi*result, "nanometers cubed")

        # Estimate the average area of the restraint (in Angstrom squared).
        area = (volume / proj_max).angstroms2()

        # Compute the correction.
        correction = _Energy(_math.log((area / 1660).value()), "kt")

        return correction

Thanks and best regards,
Guido Frisari
PhD Student
EPFL - 1015 Lausanne (CH)
SB - ISIC - LCBC (Computational Chemistry and Biochemistry Laboratory)
[guido.frisari@epfl.ch]

**Comment by lohedges** [comment]
Many thanks for your question and interest in BioSimSpace. I believe the 1/1660 is a scale factor for the standard concentration. For example, see equation 2 [here](https://www.pnas.org/doi/10.1073/pnas.1303186110). I've now added a comment to the code to explain this. I'll tag in @dlukauskis in case I'm missing anything.

The funnel correction is a free energy and is returned in units of kT by default. (Which can be converted within BioSimSpace to other compatible units.)

Cheers.

**Comment by guidsari** [comment]
Thanks for your answers.
Does the funnel correction apply to all the energies in the funnel (i.e. everything has to be N*kT less deep), or is it a correction in a difference of free energies between the deepest point and the shallowest point in the funnel? Or is it some other way?

**Comment by jmichel80** [comment]
The latter, to bring the unbound state to standard state concentration.
