### ISSUE TITLE
Storage quota exceeded on the Anaconda cloud

### ISSUE THREAD

**Issue by lohedges** [michellab/biosimspace#395]
As of around two weeks ago, packages (Sire and BIoSimSpace) are no longer uploading to the Anaconda cloud during our CI since we have exceeded our free storage quota. Annoyingly this reports an error message in the logs, but doesn't return an error code, so the CI reports as passing.

```
Error:  ('Storage requirements exceeded (3221225472 bytes). Payment is required to add a file. Please go to https://anaconda.org/binstar.settings/billing to update your plan', 402)
```

With the move to OpenBioSim, perhaps we want to set up a paid account for the `openbiosim` organisation? (I can always delete the organisation if we need to transfer ownership.) For now I'll try to prune some old packages so that we drop back below the free limit.

**Comment by jmichel80** [comment]
> With the move to OpenBioSim, perhaps we want to set up a paid account for the openbiosim organisation?

makes sense
