### ISSUE TITLE
Ligand charge differs between BioSimSpace and FESetup

### ISSUE THREAD

**Issue by lohedges** [michellab/BioSimSpace#40]
Using the data from the [D3R2018](https://github.com/michellab/D3R2018) repository, all of the ligands parameterised by FESetup have a charge of +2 |e|, e.g.

```python
import BioSimSpace as BSS

s = BSS.IO.readMolecules(BSS.IO.glob("CatS/BSS/FESetup/_ligands/CatS_155/vacuum.*"))
print(s.charge())
2.0000 |e|
```

In constrast, all ligands parameterised by BioSimSpace (also using GAFF2) have a charge of zero, e.g.

```python
import BioSimSpace as BSS

s = BSS.IO.readMolecules(BSS.IO.glob("CatS/BSS/ligands_aligned/parameterised/CatS_.*"))
print(s.charge())
3.9402e-08 |e|
```

Both FESetup and BioSimSpace are using the same PDB files as input (where the charge is zero) and both make the overall molecular charge integer valued after parameterisation by redistributing the charge between the atoms.

For the protein, which is paramterised using FF14SB, I get the same charge as FESetup, +3 |e|. Again, this is using the same input PDB file with zero molecular charge. This means that with FESetup the total charge of the complex is +5 |e|, whereas for BioSimSpace it's +3|e|. For both codes the solvated system is neutralised correctly, i.e. 5 chlorine atoms for FESetup and 3 chlorine atoms for BIoSimSpace.

Does FESetup do something else during the ligand parameterisation step that we're missing? I've had a quick look through the code but I can't see anything obvious.

**Comment by lohedges** [comment]
It looks like FESetup uses OpenBabel (along with other things) to compute the formal charge. If this isn't something that we want to support in BioSimSpace at present, then the PDB files for all of the ligands in the D3R2018 challenge set will need to be updated with the correct charge.

**Comment by lohedges** [comment]
All of the ligands in [this](https://github.com/michellab/D3R2018/tree/master/CatS/CatS_prep/Docked_ligands) directory have the correct formal charge listed in the PDB file, i.e. there are two N1+ atoms, giving an overall formal charge of +2|e|. BioSimSpace can correctly read/write this information.

It looks like the formal charge must have been lost along the way during the preparation stage, perhaps when using FKCOMBU to align them. I'll see if it's easy to re-add the missing information in the prepared input files.

**Comment by lohedges** [comment]
I've managed to edit all of the ligand PDB files by hand. I'll now re-parameterise them all with GAFF2 to correct the charges. It would be good to have write access to the [D3R2018](https://github.com/michellab/D3R2018) repo so I can update the files once I'm done.

**Comment by ppxasjsm** [comment]
I assume you realised you already had write access?

**Comment by lohedges** [comment]
Strange, when I tried pushing it said "access denied". Will try again tomorrow.

**Comment by lohedges** [comment]
Worked this time, how bizarre. Perhaps there was a network issue when I last tried.

**Comment by ppxasjsm** [comment]
Gladnit did!
