### ISSUE TITLE
Make _removeDummies() recognise dummy bonds

### ISSUE THREAD

**Issue by msuruzhon** [michellab/biosimspace#407]
Hi,

I have been testing `_removeDummies()` in the context of a ring break such as benzene to pyrrole, and it seems that the original molecule is not completely recovered and now contains an extra dummy bond which messes up the single-point energies.  I am attaching a code containing a test which demonstrates that.

```python
from typing import Dict, Optional

import BioSimSpace.Sandpit.Exscientia as BSS
import pytest
from BioSimSpace.Sandpit.Exscientia.Align._merge import _removeDummies
from BioSimSpace.Sandpit.Exscientia.Process import Gromacs
from BioSimSpace.Sandpit.Exscientia.Protocol import Production
from BioSimSpace.Sandpit.Exscientia.Units.Temperature import kelvin
from BioSimSpace.Sandpit.Exscientia.Units.Time import femtosecond
from BioSimSpace.Sandpit.Exscientia._SireWrappers import Molecule


def get_energy(
    mol: Molecule,
    coord_mol: Optional[Molecule] = None,
    coord_mol_mapping: Dict[int, int] = None,
) -> float:
    if coord_mol is not None:
        c = mol._sire_object.cursor()
        c_coord = coord_mol._sire_object.cursor()
        coordinates = c_coord["coordinates"].toVector()
        if coord_mol_mapping is not None:
            sorted_keys = sorted(coord_mol_mapping)
            coordinates = [coordinates[coord_mol_mapping[k]] for k in sorted_keys]
        for atom, coord in zip(c.atoms(), coordinates):
            atom["coordinates"] = coord
        mol = Molecule(c.commit())

    system = mol.toSystem()

    protocol = Production(
        timestep=0.1 * femtosecond,
        runtime=0.1 * femtosecond,
        temperature=0 * kelvin,
    )

    proc = Gromacs(system, protocol)
    proc.start()
    proc.wait()

    res = proc.getPotentialEnergy().value()

    return res


@pytest.fixture
def benzene():
    return BSS.Parameters.parameterise(
        "c1ccccc1", "openff_unconstrained-2.0.0"
    ).getMolecule()


@pytest.fixture
def pyrrole():
    return BSS.Parameters.parameterise(
        "C1=CNC=C1", "openff_unconstrained-2.0.0"
    ).getMolecule()


@pytest.fixture
def mapping_benzene_pyrrole(benzene, pyrrole):
    return BSS.Align.matchAtoms(benzene, pyrrole, complete_rings_only=False)


@pytest.fixture
def merged_benzene_pyrrole(benzene, pyrrole, mapping_benzene_pyrrole):
    return BSS.Align.merge(
        benzene,
        pyrrole,
        mapping=mapping_benzene_pyrrole,
        allow_ring_breaking=True,
        allow_ring_size_change=True,
    )


def test__removeDummies(benzene, pyrrole, mapping_benzene_pyrrole, merged_benzene_pyrrole):
    benzene_merged = _removeDummies(merged_benzene_pyrrole, is_lambda1=False)
    pyrrole_merged = _removeDummies(merged_benzene_pyrrole, is_lambda1=True)
    energy0_unmerged = get_energy(benzene)
    energy1_unmerged = get_energy(pyrrole)
    energy0_merged = get_energy(benzene_merged)
    energy1_merged = get_energy(
        pyrrole_merged, coord_mol=pyrrole, coord_mol_mapping=mapping_benzene_pyrrole
    )
    assert energy0_unmerged == pytest.approx(energy0_merged)
    assert energy1_unmerged == pytest.approx(energy1_merged)
```

I think we need extra code in `_removeDummies()` that detects these dummy bonds and removes them but I don't know how to do that. Do you have any ideas how to do this?

Many thanks.

**Comment by lohedges** [comment]
Your test passes for me?

**Comment by msuruzhon** [comment]
Hmm, could this be a `sire` version thing? I am using the following `macOS` build:

`sire                      2023.0.1        py38h01edc0c_13    michellab/label/dev`

**Comment by lohedges** [comment]
Can you let me know what version of Gromacs you are using, and whether you are using CPU or GPU. If I print the energies in the assertion at the end of the test I get the _exact_ same values, i.e.:

```python
    assert energy0_unmerged == pytest.approx(energy0_merged)
    assert energy1_unmerged == pytest.approx(energy1_merged)

    print(energy0_unmerged, energy0_merged)
    print(energy1_unmerged, energy1_merged)
```

Gives:

```
24.924952198852772 24.924952198852772
36.88169216061185 36.88169216061185
```

It _could_ be a Sire version issue, although I'm not sure what changes would affect this. (Perhaps the partial molecule bit.)

**Comment by lohedges** [comment]
FYI: I'm running the test using our devel, not yours, so it's possible that I'm not comparing apples to apples.

**Comment by msuruzhon** [comment]
Thanks, that's very strange because I get completely different energies (although that could be because the test might not be completely reproducible?):

```
23.024163479923516 19.628107074569787
35.420172084130016 35.420172084130016
```

My gromacs version is the following and is run on the CPU:
`gromacs                   2022.2          nompi_h1c20066_100    conda-forge`

**Comment by lohedges** [comment]
Yes, if I use your devel then I get completely different energies too. There must be some inconsistency between the code somewhere. These are the energies I get with your devel:

```
24.924952198852772 20.971367112810707
36.88169216061185 36.88169216061185
```

**Comment by msuruzhon** [comment]
Thanks, that's very strange then, I will try to see what's going on and will update here.

**Comment by lohedges** [comment]
No problem. The partial molecule extract bit should deal with sorting out all properties related to the sub molecule that you are interested in, i.e. updating all bonded terms, etc.

**Comment by msuruzhon** [comment]
Okay it seems that the region of interest code uses separate connectivities for both endstates, which results in topologies that have empty terms for some of the bonds. If the full set of bonds from both endstates is used then this is not a problem. I guess it should be okay to use the full set of bonds in any case? I will have to think about it but in any case it seems that the issue above is not related to `sire`. Apologies.

**Comment by lohedges** [comment]
No worries. We can add this as a unit test if needed. I've got some similar tests to check that the single point energies of the merged molecule end states agree with those of the original molecules, but this doesn't deal with dummy extraction.
