### ISSUE TITLE
Add support for reading perturbed topologies and pert files

### ISSUE THREAD

**Issue by msuruzhon** [michellab/BioSimSpace#41]
It seems that BioSimSpace does not open perturbed topologies correctly (it completely gets rid of the second molecule). This is obvious if we open a saved morph and save it again:

```
import BioSimSpace as _BSS

morph = _BSS.IO.readMolecules(["morph.gro87", "morph.grotop"])
_BSS.IO.saveMolecules("morph_resaved", morph, "Gro87,GroTop")
```

Input and output files:
[Morphs.zip](https://github.com/michellab/BioSimSpace/files/2548000/Morphs.zip)

**Comment by lohedges** [comment]
There is no support for reading perturbed topologies at present. Apologies if this wasn't clear.

**Comment by lohedges** [comment]
Closing since we now have partial support for this feature. Discussion has moved to #216.
