### ISSUE TITLE
BioSimSpace.Align.viewMapping: py3Dmol.view not rendering in Jupyter Notebook

### ISSUE THREAD

**Issue by lohedges** [michellab/biosimspace#412]
Currently the output of `BoiSimSpace.Align.viewMolecules` isn't rendering in a Jupyter Notebook:

![viewMapping_issue](https://user-images.githubusercontent.com/648557/213729456-23888d51-7e1b-4090-9204-5b491e2a5696.png)

(Nothing happens if you call `.show()` on the view either.)

This is on Linux, using Firefox 109. I'm not sure if this is the same on all other OSes and browsers. I'm wondering if this is related to the pinning of `ipywidgets`, which was needed to get `NGLView` to work. I'll play around to see if I can get a working environment.

This will have to be a fix for 2023.1.0, since it would likely require a rebuild of Sire too.

**Comment by chryswoods** [comment]
Very curious - I'll look to debug too. I added an exporter for sire objects to nglview in 2023.X, but I don't think that BSS would use that route?

**Comment by chryswoods** [comment]
I confirm I see this too on safari, MacOS M1. I suspect it is universal. `m0._sire_object.view()` still works, showing that nglview is rendering.

**Comment by lohedges** [comment]
Thanks for confirming. I only mentioned the possibility of a rebuild for Sire since a lot of things seem to be tied to `ipywidgets`, so if that is the culprit then quite a few dependencies might change it we adjust the version. I'll see if the problem goes away with different versions of `py3Dmol` on Monday.

**Comment by chryswoods** [comment]
Yes - there is definitely a package clash somewhere. In a vanilla mambaforge environment where I only install jupyterlab and py3dmol it works.

<img width="831" alt="image" src="https://user-images.githubusercontent.com/3694698/213788112-38709948-7cd4-4a73-ac1c-3135d3a933c3.png">

In the openbiosim environment with sire and BioSimSpace installed it doesn't...

<img width="834" alt="image" src="https://user-images.githubusercontent.com/3694698/213788220-ee6e697c-b56d-401b-ab70-5e7d36611024.png">

**Comment by chryswoods** [comment]
We can do a `2023.1.1` release of sire once we work out what the clash is... (it will also give me a chance to include the other fixes I've been doing - I want to get to a point where all the SireUnitTests tests pass on all platforms)

**Comment by lohedges** [comment]
Okay, so the issue is `py3Dmol` itself. It works with the latest version (2.0.0), but not with the version installed via BioSimSpace (1.8.1). The new version works with the pinned version of `ipywidgets` from our environment (7.7.2) and also with the latest version (8.0.4). Version 2.0.0 of `py3Dmol` is only 15 days old, so I would assume that `sire` would have been built against it (unless the dependency resolution doesn't allow it). For packages built prior to this, I think the pinning rules used by conda during the build wouldn't allow us to resolve against 2.0.0, i.e. it is a new major version.

I'll try re-building Sire locally to see what version we end up with. If it works, then a simple rebuild might fix things. I'll also check `nglview`, as it would be good to remove the `ipywidgets` pin if it is no longer necessary.

**Comment by lohedges** [comment]
Hmm, the latest Sire build did use `py3Dmol` 2.0.0, so it might just be my local development environment that's out of date. I'll refresh it and see.

**Comment by lohedges** [comment]
Nope, that's not it. It still doesn't work downloading the latest conda package, which does pull in `py3Dmol` 2.0.0.

**Comment by lohedges** [comment]
I've unpinned `ipywidgets` locally and I still see the same issue. Interestingly, just drawing a simple sphere works. (Just re-using your example.)

![viewMapping_issue2](https://user-images.githubusercontent.com/648557/214019220-87b4008d-73b8-41a8-a915-430ee412dd4f.png)

The function is pretty simple and is just using standard `py3Dmol` function calls. I'll see if I can strip parts out in order to get it to work.

Just to note that we _do_ still need to pin `ipywidgets`, since an `nglview` update hasn't been released yet. (I think they've fixed it locally, but not updated the conda package yet.) Without this pin we'd get the following error:

```
File ~/.conda/envs/sire-dev/lib/python3.9/site-packages/nglview/color.py:54, in _ColormakerRegistry._ipython_display_(self, **kwargs)
     52 if self._ready:
     53     return
---> 54 super()._ipython_display_(**kwargs)

AttributeError: 'super' object has no attribute '_ipython_display_'
```

**Comment by lohedges** [comment]
Right, fixed it. The issue was this line:

```python
# Create the view.
view = _py3Dmol.view(
    linked=False, width=width, height=height, viewergrid=viewergrid
)
```

Here both `height` or `width` _could_ be a float (since this is worked out in the function) but it is expected to be an `int`. Annoying that no error is raised, or that `py3Dmol` can't convert to an `int` for you. This definitely used to work, so I can only assume that they've changed something behind the scenes.

**Comment by chryswoods** [comment]
That's a good fix (and quite a rabbit-hole debug!)
