### ISSUE TITLE
[BUG] Cannot import BioSimSpace after installation of biosimspace 2023.1.2 using mamba  

### ISSUE THREAD

**Issue by cespos** [michellab/biosimspace#421]
**Describe the bug**
Hi,

I tried to install BioSimSpace 2023.1.2 following the instructions reported in the [biosimspace.openbiosim](
https://biosimspace.openbiosim.org/install.html) page:

```
mamba create -n openbiosim "python<3.10"
mamba install -n openbiosim -c openbiosim biosimspace
```

The installation completed successfully. However when I tried to import BSS in python I got the following error:
![image](https://user-images.githubusercontent.com/31316943/221247993-4a121d3a-93e5-4df5-8798-b2fd2bd5185f.png)

**To Reproduce**
See above

**Expected behavior**
No error when importing BSS

**Input files**
None

**(please complete the following information):**
 - Linux
 - Version of Python: 3.9.16
 - Version of BioSimSpace: 2023.1.2
 - Version of Sire: 2023.1.2
 - I confirm that I have checked this bug still exists in the latest released version of BioSimSpace: yes

**Comment by lohedges** [comment]
Please can use the development label, i.e. `-c openbiosim/label/dev`. The new convert functionality uses some functionality from Sire that isn't yet in a release. This will be fixed when the next version comes out, which should be soon.

**Comment by lohedges** [comment]
This is now reported [here](https://github.com/OpenBioSim/biosimspace/issues/11).

**Comment by cespos** [comment]
It works now, thanks!
