### ISSUE TITLE
Add descriptions to supported file extensions

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#44]
Based on talking to completely inexperienced users of MD simulations, it was suggested that the file formats should also have a brief description of what underlying software package they relate to and whether they are a topology type file or a coordinate type file.

**Comment by lohedges** [comment]
Hi Toni,

Does this specifically refer the the "conversion" notebook. If not, then this functionality already exists, as documented [here](https://github.com/michellab/BioSimSpace/tree/devel/python/BioSimSpace/IO), e.g.

```python
BSS.IO.formatInfo("PDB")
'Protein Data Bank (PDB) format files.'
```

The descriptions are just taken from the Sire format information for the appropriate parser. That information would need to be updated if we want any more detail.

Cheers.

**Comment by lohedges** [comment]
For the file conversion notebook, I could probably hack something together that prints the corresponding `formatInfo` string somewhere in the GUI whenever the format option is changed from the drop-down menu.

**Comment by ppxasjsm** [comment]
Yes it's exactly that dropdown menu that caused confusion! I guess some programs can also read multiple formats.

**Comment by lohedges** [comment]
Not a perfect solution by any means, but shows how it's possible to add information to the drop-down labels.
