### ISSUE TITLE
Adding space property to a system

### ISSUE THREAD

**Issue by jmichel80** [michellab/BioSimSpace#46]
Another question for @lohedges 

The following instruction currently adds a BioSimSpace molecule to a list of BioSimSpace molecules. and this returns a BioSimSpace system. 

```
In [31]: total = merged+remainderA
In [32]: merged.__class__
Out[32]: BioSimSpace._SireWrappers._molecule.Molecule
In [33]: remainderA.__class__
Out[33]: list
In [34]: total.__class__
Out[34]: BioSimSpace._SireWrappers._system.System
```

Q1) This is not the most logical behavior, I would expect that adding one molecule to a list of molecules would return another list of molecules
Q2) How can I set the space property of the resulting system ? This is necessary to get later 

`process = BSS.Process.Somd(system, protocol)
`

to create a somd input using a periodic box.

**Comment by lohedges** [comment]
1) Strange. Adding a molecule to a list should just extend the list. I'll look into this.

2) There's currently no way to set the space property without editing the underlying Sire molecule. A space property is automatically set if you solvate the system.

**Comment by lohedges** [comment]
1) Is now fixed. I had forgotten to immediately return the extended list of molecules and instead used it to create a new system.

**Comment by jmichel80** [comment]
Re 2. a workaround is to use .removeMolecules() and .addMolecules() to modify a system loaded in with a space property.

**Comment by lohedges** [comment]
With regards to 1.: I've now reverted to the original behaviour. In BioSimSpace, any multi molecule object (not in a container, e.g. list or tuple) is a System. If you want to insert a molecule object into an existing list of molecules, then you can use the standard Python `append` or `extend` functionality, e.g.

```python
# Here molecules0 and molecules0 are lists of molecules and molecule is a single molecule.

# Add a single molecule to a list of molecules.
molecules0.append(molecule)

# Add all of the molecules from another list, i.e. extend the original list.
molecules0.extend(molecules1)
```
