### ISSUE TITLE
BSS read/write molecules woes

### ISSUE THREAD

**Issue by jmichel80** [michellab/BioSimSpace#48]
Not getting the expected behaviour from this script

```
import BioSimSpace as BSS
input_top = "1a.parm7"
input_rst = "1a_equilibrated.rst7"
# Load system 
system = BSS.IO.readMolecules([input_top, input_rst])
print (system)
# Write system
BSS.IO.saveMolecules("testme",system, system.fileFormat())
# Read system
system2 = BSS.IO.readMolecules(["testme.prm7", "testme.rst7"])
print (system2)
```
Upon execution

```
julien@ubuntu:/mnt/vmshared/Cresset/setup-bss/test-parser$ ~/sire.app/bin/python parser.py 
/home/julien/sire.app/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/julien/sire.app/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/julien/sire.app/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

==============================================================
Sending anonymous Sire usage statistics to http://siremol.org.
For more information, see http://siremol.org/analytics
To disable, set the environment variable 'SIRE_DONT_PHONEHOME' to 1
To see the information sent, set the environment variable 
SIRE_VERBOSE_PHONEHOME equal to 1. To silence this message, set
the environment variable SIRE_SILENT_PHONEHOME to 1.
==============================================================

<BioSimSpace.System: nMolecules=1347>
Traceback (most recent call last):
  File "parser.py", line 10, in <module>
    system2 = BSS.IO.readMolecules(["testme.prm7", "testme.rst7"])
  File "/home/julien/sire.app/lib/python3.5/site-packages/BioSimSpace-2018.1.1+574.gf3d18bc-py3.5.egg/BioSimSpace/IO/__init__.py", line 226, in readMolecules
OSError: Failed to read molecules from: ['testme.prm7', 'testme.rst7']
```

Ran using 
Sire version: 2018.2.0 (9a638a5d9d106d77ee89c94faacad91b2ad615b3/Lester Hedges/2019-01-24T10:12:48+00:00 | **UNCLEAN**)

Inputs and script attached
[test-parser.tar.gz](https://github.com/michellab/BioSimSpace/files/2796879/test-parser.tar.gz)

**Comment by jmichel80** [comment]
I suspect this is related to #47 

Debugging should focus on the explaining the following differences between initial parm7 files and written parm7 files

- 
FLAG SOLTY has a 0 for each atom as mentioned in line 3006-3011
https://github.com/michellab/Sire/blob/devel/corelib/src/libs/SireIO/amberprm.cpp

However this contradicts  what is read in the original parm7 file where there are only 15 zeros. 
According to http://ambermd.org/formats.html 
SOLTY should have one entry for each atom type present in the topology 

- The pointers values differ in some cases
julien@ubuntu:/mnt/vmshared/Cresset/setup-bss/test-parser$ head testme.prm7 
%VERSION  VERSION_STAMP = V0001.000  DATE = 01/25/19  16:12:59
%FLAG TITLE
%FORMAT(20a4)
LIG
%FLAG POINTERS
%FORMAT(10I8)
    4090      14    4063      29      57      39     106      70       0       0
    5673    1347      29      39      70      16      32      32       0       0
       0       0       0       0       0       0       0       1      52       0
       0       0       0
julien@ubuntu:/mnt/vmshared/Cresset/setup-bss/test-parser$ head 1a.parm7 
%VERSION  VERSION_STAMP = V0001.000  DATE = 10/11/18  15:27:56                  
%FLAG TITLE                                                                     
%FORMAT(20a4)                                                                   
LIG                                                                             
%FLAG POINTERS                                                                  
%FORMAT(10I8)                                                                   
    4090      14    4063      29      57      39     106      72       0       0
    5673    1347      29      39      72      19      36      32      15       1
       0       0       0       0       0       0       0       1      52       0
       0

**Comment by lohedges** [comment]
Just to confirm: this is an issue with Sire which has been reported [here](https://github.com/michellab/Sire/issues/233) and has nothing to do with BioSimSpace (other than it using `Sire.IO` for its parsers).

To see, we can reproduce the above issue with only Sire objects:

```python
from Sire.IO import *

# Load the input files.
s = MoleculeParser.read(["1a_equilibrated.rst7", "1a.parm7"])

# Write back to file.
p = AmberRst7(s)
p.writeToFile("test.rst7")
p = AmberPrm(s)
p.writeToFile("test.prm7")

# Now try to re-read the files.
s = MoleculeParser.read(["test.rst7", "test.prm7"])
```

I suggest closing this issue (along with #47) and focusing discussion on the Sire issue [thread](https://github.com/michellab/Sire/issues/233).

I'll try to take look at `Sire.IO.AmberPrm` next week, although, having not written the code, I'm not too clued up on the logic. Perhaps I can discuss things with @chryswoods when he has time.

As suggested, it would be good to document the differences between the file, and suggest reasons for why this may have occurred.

**Comment by jmichel80** [comment]
Agreed, let's continue the discussion [here]((https://github.com/michellab/Sire/issues/233)) but keep this issue open until we have resolved the bug in Sire.IO.AmberPrm as this breaks functionality in BioSimSpace

**Comment by lohedges** [comment]
Great. Thanks for tracking down the differences in the `SOLTY` and `POINTERS` flags between the two files. (Your post hadn't updated before I hit enter on mine.) That's something I can look into next week.

**Comment by chryswoods** [comment]
Closing as now addressed in the Sire thread (where it should be fixed)
