### ISSUE TITLE
import BioSimSpace should not import matplotlib implicitly

### ISSUE THREAD

**Issue by chryswoods** [michellab/BioSimSpace#5]
When I run "import BioSimSpace" in a python shell I get a failure because it is importing matplotlib and falling over

```
import BioSimSpace
### stuff ###
ImportError: Matplotlib is not installed. Please install matplotlib in order to use BioSimSpace.
```

This is because matplotlib from conda is broken if libGL.so.1 is not available, e.g.

```
import matplotlib.pyplot
### stuff ###
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

The solution is to set the matplotlib backend to a null drawer before importing, e.g. see here

<https://github.com/matplotlib/matplotlib/issues/9954/>

However, I feel that we shouldn't even be pulling in matplotlib unless we are running within a notebook. Could we set a flag or similar to say that matplotlib is not importable, and hence plotting is not available? Otherwise people will export to Python for batch usage and will break because matplotlib is not available.

**Comment by chryswoods** [comment]
Thanks :-)

I've got the new images ready and will upload them tomorrow. We can "git pull ; cd python; python setup.py install" to update BioSimSpace if we need to make last-minute changes before Thursday week. I'll update everything next Thursday for a "final" version.

**Comment by lohedges** [comment]
Does the problem just occur in the python shell, or do you experience it in ipython too? (Just checking whether I want to import only inside a notebook, or only interactively.) I have no problems here, but installed matplotlib into sire.app using pip.

**Comment by chryswoods** [comment]
Both python and ipython. In both cases failure to import matplotlib should not cause BioSimSpace to fail. Instead a flag should be set so that plotting is disabled in the script. You could print a warning when someone tries to plot to give the reason why (e.g. "Plotting disabled as matplotlib failed to load. Please check your matplotlib installation.")

**Comment by chryswoods** [comment]
To add, the problem is not with the installation of matplotlib itself. Rather that matplotlib fails to import if it can't find a render backend. You will see this on the notebook server where libGL.so.1 isn't available (the import matplotlib.pyplot output above). On most linux distributions this will work, but on servers without X11 or other display libraries, it won't. Since we don't want to detect this ourselves, it is easier to catch the failed import and just set a flag disabling plotting.

It does make me wonder how pandas solves this problem...

**Comment by lohedges** [comment]
Great, that makes complete sense. Should hopefully be able to fix this some time this afternoon.

**Comment by lohedges** [comment]
Should be fixed with the latest commit. Let me know if you encounter any further issues.

**Comment by chryswoods** [comment]
Thanks :-)
