### ISSUE TITLE
BSS Gateway question

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#57]
Woudl it make sense to have a `BSS.Gateway.Path`, rather than just a string option?

**Comment by ppxasjsm** [comment]
In addition to this, can one have optional inputs to a node? Or are they all required? I don't really see a way of setting an optional input.

**Comment by lohedges** [comment]
You can use File or FileSet. Is there a reason you need a directory as an
input/output requirement?

**Comment by lohedges** [comment]
Optional inputs have default values.

**Comment by ppxasjsm** [comment]
Executable paths?

**Comment by lohedges** [comment]
But perhaps there is a more flexible way of having optional inputs, i.e.
when they may not be needed at all.

**Comment by jmichel80** [comment]
Following up on this, I have a couple of questions about the intended usage of BSS.Gateway

Let's say I have the following script to parameterise a molecule

```
# This notebook parameterises a molecule and writes a topology usable for a molecular simulation. Based on the Molecular Seup node written by Lester Hedges
import BioSimSpace as BSS
node = BSS.Gateway.Node("A node to parameterise a molecule ready for molecular simulation.")
node.addAuthor(name="Julien Michel", email="julien.michel@ed.ac.uk", affiliation="University of Edinburgh")
node.setLicense("GPLv3")
node.addInput("input", BSS.Gateway.File(help="A molecular input file, e.g. a PDB file."))
node.addInput("forcefield", BSS.Gateway.String(help="The name of the force field to use for parameterisation.",
                                               allowed=BSS.Parameters.forceFields(), default="ff14SB"))
node.addOutput("output", BSS.Gateway.FileSet(help="The parameterised and solvated molecular system in AMBER format."))
node.showControls()
system = BSS.IO.readMolecules(node.getInput("input"))
molecule = system.getMolecules()[0]
molecule = BSS.Parameters.parameterise(molecule, node.getInput("forcefield")).getMolecule()
node.setOutput("output", BSS.IO.saveMolecules("system", molecule, ["prm7", "rst7"]))
node.validate()

```

How should the node be constructed to enable this command line interface

`~/sire.app/bin/python scripts/parameterise.py --input ligands.pdb/12.pdb --forcefield gaff2 --output [12.prm7,12.rst7]`

Where I wish to specify the name of the output  from the command line directly (so I don't have to edit the script). 
It's not obvious to me how this can be done using the interface of BioSimSpace.Gateway._node.Node

Also it is a bit surprising that the output of the node is given by the argument -o and not -h

`~/sire.app/bin/python scripts/parameterise.py -o `

> This node outputs the following...
>   output: FileSet, 'The parameterised and solvated molecular system in AMBER
> format.'

`~/sire.app/bin/python scripts/parameterise.py -h `

> usage: parameterise.py [-h] [-o] [-c CONFIG] --input INPUT
>                        [--forcefield {ff03,ff14SB,ff99,ff99SB,gaff,gaff2}]
> 
> A node to parameterise a molecule ready for molecular simulation. Args that start with '--' (eg. -o) can also be set in a config file (specified via -c). The config file uses YAML syntax and must represent a YAML 'mapping' (for details, see http://learn.getgrav.org/advanced/yaml). If an arg is specified in more than one place, then commandline values override config file values which override defaults.
> 
> Required arguments:
>   --input INPUT         A molecular input file, e.g. a PDB file.
> 
> Optional arguments:
>   -h, --help            Show this help message and exit.
>   -o, --output          Show the output of this node.
>   -c CONFIG, --config CONFIG
>                         Path to configuration file.
>   --forcefield {ff03,ff14SB,ff99,ff99SB,gaff,gaff2}
>                         The name of the force field to use for parameterisation.
>                           default=ff14SB
> 

Finally I was surprised that a output.yml file was generated. It is required or should the user have control on whether or not that output will be produced?

> julien@ubuntu:/mnt/vmshared/somd/qube-somd/amber-gaff/01-setup$ cat output.yml 
> output:
> - /mnt/vmshared/somd/qube-somd/amber-gaff/01-setup/system.prm7
> - /mnt/vmshared/somd/qube-somd/amber-gaff/01-setup/system.rst7

**Comment by lohedges** [comment]
For the first part (naming outputs) you'll need to use `BioSimSpace.Gateway.String` as input requirements that can be used to name the outputs. I guess it's possible to do something like you suggest, matching the name of the provided outputs against any `File` type requirements in sequence. I'll have a think about this.

The `-o, --output` option was added quite early on when I hadn't worked out how to fully customise the `argparse` help output. I should be able to add it there now.

The YAML file functionality was added for my quick-and-dirty KNIME integration. As it functions, there was no way for the script to actually be aware that it was run from KNIME (rather than just the command-line) so the YAML file is always generated if the node isn't run interactively, i.e. not in Jupyter. The YAML file also allows nodes to be chained together by passing the output of one as the input of another.

**Comment by lohedges** [comment]
Output information is now added to the argparse help description. It was a bit of a faff to get the formatting to work correctly (so it looks like the rest of the help message) but I think it's okay.

**Comment by jmichel80** [comment]
This is what I get now when I try to set a node output 

```
node.addOutput("nodeoutput", BSS.Gateway.FileSet(help="The parameterised and solvated molecular system in AMBER format."))

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-a305bb27eba9> in <module>()
----> 1 node.addOutput("nodeoutput", BSS.Gateway.FileSet(help="The parameterised and solvated molecular system in AMBER format."))

~/sire.app/lib/python3.5/site-packages/BioSimSpace-2018.1.1+751.g07a8109-py3.5.egg/BioSimSpace/Gateway/_node.py in addOutput(self, name, output)
    721 
    722         # Update the parser description.
--> 723         self._parser.description = self._generate_description()
    724 
    725     def setOutput(self, name, value):

AttributeError: 'NoneType' object has no attribute 'description'

```

**Comment by lohedges** [comment]
This should now be fixed. In light of your suggestion, I had updated the code to dynamically update the argpare help description when outputs are added. I had forgotten to disable this when running from within a Jupyter notebook (where no parser is needed). (In this case the parser is a `NoneType`.)
