### ISSUE TITLE
Heating with Gromacs does not behave as expected

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#61]
Say I want to heat my system from 100 K to 300 K, then according to BioSimSpace I should run something like this:

```python
protocol = BSS.Protocol.Equilibration(temperature_start=100*BSS.Units.Temperature.kelvin, temperature_end=300*BSS.Units.Temperature.kelvin)
process = BSS.MD.run(min_syst, protocol, name="equilibrate")
```
The default runtime and timestep are 0.2 ns and 2 fs respectively. This would make me think that within 0.2 ns my system was heated from 100 K to 300 K. 

However if I look at the process progress it takes a long time to reach where I want to be, i.e.:
```
print(process.getTime(), process.getTemperature(), process.getTotalEnergy())
```
46.6000 ns 143.7550 K -9.5796e+04 kJ/mol

After 46 ns clearly not done...
![image](https://user-images.githubusercontent.com/3668316/53646489-38798f00-3c33-11e9-822f-584b210a590f.png)

**Comment by lohedges** [comment]
Hi Toni,

It looks to me like BioSimSpace is misconverting the internal time units used by GROMACS. When the sumulation runs to completion, what does `process.getTime()` return?

**Comment by lohedges** [comment]
I think they use picoseconds. Will fix this now.

Cheers.

**Comment by ppxasjsm** [comment]
I am reopening, as some of the printouts still have a conversion error. 

The getTime() did not get the updated version of time, so instead of running a 0.2 ns simulation it actually looks like I am running a 200 ns simulation. 

![Screenshot from 2019-03-15 10-54-38](https://user-images.githubusercontent.com/3668316/54427304-0deb0400-4712-11e9-80ff-4ceff91ba5f1.png)

**Comment by ppxasjsm** [comment]
argg. no using the older version...sorry.
