### ISSUE TITLE
bug with uploading input files in notebook

### ISSUE THREAD

**Issue by jmichel80** [michellab/BioSimSpace#67]
If two files loaded from a different path have the same filename the second uploaded file overwrites the first one

![image](https://user-images.githubusercontent.com/11722212/54390336-24557900-469a-11e9-99a2-587f01a56a2b.png)

**Comment by lohedges** [comment]
Thanks, Julien, good catch. Uploaded files are now always given a unique name (in the uploads folder). I chose to leave the original file name on the widget button and upload reporting info below the GUI. Hopefully this is okay.
