### ISSUE TITLE
binding_freenrg_gmx process does not get killed neatly or runs on gmx

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#72]
When running a binding_freenrg_gmx calculation, killing the process does not seem to work. 
After 10 minutes the terminal is still not happy:
```
~/sire.app/bin/sire_python binding_freenrg_gmx.py 255 252
Starting /home/ppxasjsm/sire.app/bin/sire_python: number of threads equals 20
^CYou're killing me!!!
Killing job  /home/ppxasjsm/sire.app/bin/somd-freenrg -c somd.rst7 -t somd.prm7 -m somd.pert -C somd.cfg -p CUDA
y...job still not dead. You may want to check it  is not still running.

^CYou're killing me!!!
^CYou're killing me!!!

```

Also note that somehow it is running SOMD and not Gromacs.

**Comment by lohedges** [comment]
For question 1: 

`BioSimSpace.Process` is built on top of `Sire.Base.Process`. This tries its very best to safely terminate running processes, including killing threads that are spawned by the process. However, this isn't fail safe, e.g. it might take a while to stop if many threads are spawned, or it might not stop at all. I'm not sure what else we can do about this (try hitting Ctrl+C on an arbitrary Linux process and seeing if it exits cleanly) and I think the error message is pretty clear.

For question 2:

Everything works fine here, so I assume that you are once again using an outdated version of BioSimSpace. Before I added GROMACS support, SOMD was the only free energy driver. As mentioned [here](https://github.com/michellab/BioSimSpace#issues), if you could post the BioSimSpace version number in your issues then it would help me to quickly see if this case.

**Comment by ppxasjsm** [comment]
Question 2 I sorted. I was using a slightly outdated Biosimspace.

I guess I can live with question one, or is just slightly concerning.
