### ISSUE TITLE
Chaining BSS nodes in python

### ISSUE THREAD

**Issue by jmichel80** [michellab/BioSimSpace#75]
@lohedges @ppxasjsm @chryswoods 

The discussion today with Simon from OpenFF made me think about how we might want to mix BSS nodes with code coming from other sources in a python framework. 

I wanted to start a thread to discuss how BSS nodes could be restructured to allow importing different nodes within a python script to build more complex nodes or workflows. 

For instance something along the lines of

```
import BSS.node.parameterise as parameterise
import BSS.node.solvate as solvate

molecule = BSS.IO.readMolecules( input )
molecule = parameterise.run(molecule)
system = solvate.run(molecule)

```
What would be the advantages and inconvenient with respect to the current approaches taken by me (lot's of mini nodes that have to be chained together for a high level workflow) or toni (fewer nodes that make use of a broader range of the library functionality) to write BSS nodes ?

**Comment by lohedges** [comment]
Something like this should be easy to implement, and I see that it could be useful. As long as we stored the nodes somewhere consistent where they could be referenced by name, then you could just have wrapper function that runs the underlying node using a subprocess. At run-time BioSimSpace could query the node directory to dynamically create a list of available nodes. The function could take a dictionary of key:value inputs for the node and internally convert these to a YAML file that can be passed to the node (like in the knime example). The return value of the function could just be another dictionary with the key:value pairs holding the output requirements.

**Comment by jmichel80** [comment]
Would your solution require the user to structure the code executed by the node differently from the current approach, or could that be automatically handled by BioSimSpace ?

**Comment by lohedges** [comment]
No, nodes could be written in exactly the same way as they are now. This would just provide a convenient way of running a node within BioSimSpace. I'm imagine something like the following:

```python
import BioSimSpace as BSS

# Print a list of the available nodes. We could also query the help of each node to generate
# a dictionary with the name and a description, or name, description, and inputs.
print(BSS.Nodes.listNodes())

# Create a dictionary of inputs for a node, e.g. minimisation.
input = {"steps" : 1000, "files" : ["amber/ala/ala.crd", "amber/ala/ala.top"]}

# Run the node and get the output as a dictionary. This function runs the named node as a
# subprocess, converting the dictionary of inputs to a YAML file to be passed on the command-line.
output = BSS.Nodes.run("minimisation")

print(output)
{"minimised" : ["minimised.rst7", "minimised.prm7"]
```

**Comment by lohedges** [comment]
I've now added functionality in the `feature-node` branch that implements the above. Let me know it's what you had in mind.

The module looks for nodes a hidden `_nodes` directory inside its own module directory. We can copy in finished nodes at install time. While developing, it might be useful for you to create a symbolic link to your playground directory, e.g.:

```bash
ln -s /home/julien/Code/BioSimSpace/nodes/playground /home/julien/Code/BioSimSpace/python/BioSimSpace/Node/_nodes
```

Then run your python scripts using a `PYTHONPATH` pointing to the latest development source code, e.g.

```bash
PYTHONPATH=/home/julien/Code/BioSimSpace/python $HOME/sire.app/bin/python script.py
```

**Comment by lohedges** [comment]
This is now merged into `devel` so you can test there. The `feature-node` branch has been deleted.
