### ISSUE TITLE
Another comparison between BSS and FESetup pert files 

### ISSUE THREAD

**Issue by jmichel80** [michellab/BioSimSpace#77]
Related to #74 

Here is a detailed comparison of the SOMD inputs for perturbing molecule 5 into molecule 16 with FESetup and with BioSimSpace

Here is a picture of the atom names and topology of the variable part in the FESetup files

![image](https://user-images.githubusercontent.com/11722212/55493989-db0d9f00-5631-11e9-910f-76e4b0d03eb8.png)

Here is the same view for the BSS files

![image](https://user-images.githubusercontent.com/11722212/55494065-fc6e8b00-5631-11e9-85dd-8b0150e33c95.png)

i.e. where the atom names differ in some instances 
DU34 - > H34, DU35 -> H35 , DU35 - > H35 , DU36 - > H36

Comparison of the pert files produced by FESetup (MORPH.onestep.pert) and by BSS (5TO16.pert) reveal the following differences:

* 7 variables bonds in FESetup, 3 variable bonds in BSS. 

--> That's ok because the 4 additional variable bonds in FESetup (O32-DU34, H33-DU35, H33-DU36, H33-DU37, involve dummy atoms and the initial and final parameters are the same (so strictly should not be considered perturbed hence the BSS behaviour is adequate *assuming* the correct forcefield parameters for the initial state have been written in 5TO16.prm7).    

* 16 variables angles in FESetup, 8 variables angles in BSS
--> Ok because 8 additional angles involve dummy atoms and have constant parameters throughout the perturbation. 

* 16 variable dihedrals in FESetup, 5 variable dihedrals in BSS

1/16
FESetup
        dihedral
                atom0   C18
                atom1   O32
                atom2   C29
                atom3   H30
                initial_form 0.383333333 3.0 0.0
                final_form 0.0 2.0 3.141594
        enddihedral
BSS
    dihedral
        atom0          C18
        atom1          O32
        atom2          C29
        atom3          H30
        initial_form   0.3833 3.0 -0.000000
        final_form     0.0000 0.0 0.000000
    enddihedral
--> Difference in final_form parameters

2/16
FESETUP
        dihedral
                atom0   O32
                atom1   C29
                atom2   H33
                atom3   DU36
                initial_form 0.0 0.0 0.0
                final_form 0.155555556 3.0 0.0
        enddihedral
BSS
Should be O32 C29 H33 H36 
--> not found. Since the option zero_dihedral_dummy=True was set this should be a variable dihedral and it should be written in the pert file. 

3/16
FESETUP
        dihedral
                atom0   H31
                atom1   C29
                atom2   H33
                atom3   DU35
                initial_form 0.0 0.0 0.0
                final_form 0.155555556 3.0 0.0
        enddihedral
BSS
Should be H31 C29 H33 H35. Same issue as 2/16 
--> not found

4/16
FESETUP
        dihedral
                atom0   C18
                atom1   O32
                atom2   C29
                atom3   H30
                initial_form 0.383333333 3.0 0.0
                final_form 0.0 2.0 3.141594
        enddihedral
BSS
    dihedral
        atom0          C18
        atom1          O32
        atom2          C29
        atom3          H30
        initial_form   0.3833 3.0 -0.000000
        final_form     0.0000 0.0 0.000000
    enddihedral
--> Not sure why the final form differs here. None of the atoms involved are dummy atoms. 

5/16
FESETUP
        dihedral
                atom0   O32
                atom1   C29
                atom2   H33
                atom3   DU37
                initial_form 0.0 0.0 0.0
                final_form 0.155555556 3.0 0.0
        enddihedral
BSS
--> Not found

6/16
FESETUP
        dihedral
                atom0   N17
                atom1   C18
                atom2   O32
                atom3   C29
                initial_form 2.7 2.0 3.141594
                final_form 2.5 2.0 3.141594
        enddihedral
BSS
    dihedral
        atom0          N17
        atom1          C18
        atom2          O32
        atom3          C29
        initial_form   2.7000 2.0 3.141594
        final_form     2.5000 2.0 3.141594
    enddihedral
--> SAME ! 

7/16
FESETUP
        dihedral
                atom0   H31
                atom1   C29
                atom2   H33
                atom3   DU36
                initial_form 0.0 0.0 0.0
                final_form 0.155555556 3.0 0.0
        enddihedral
BSS
--> Not found

8/16
FESETUP
        dihedral
                atom0   H30
                atom1   C29
                atom2   H33
                atom3   DU35
                initial_form 0.0 0.0 0.0
                final_form 0.155555556 3.0 0.0
        enddihedral
BSS
--> Not found

9/16
FESETUP
        dihedral
                atom0   N17
                atom1   C18
                atom2   O32
                atom3   DU34
                initial_form 0.0 0.0 0.0
                final_form 2.5 2.0 3.141594
        enddihedral
BSS
--> Not found

10/16
FESETUP
        dihedral
                atom0   H31
                atom1   C29
                atom2   H33
                atom3   DU37
                initial_form 0.0 0.0 0.0
                final_form 0.155555556 3.0 0.0
        enddihedral
BSS
--> Not found

11/16
FESETUP
        dihedral
                atom0   C18
                atom1   O32
                atom2   C29
                atom3   H33
                initial_form 0.383333333 3.0 0.0
                final_form 1.02 1.0 3.141594 0.17 3.0 0.0 0.1 4.0 3.141594
        enddihedral
BSS
    dihedral
        atom0          C18
        atom1          O32
        atom2          C29
        atom3          H33
        initial_form   0.3833 3.0 -0.000000
        final_form     0.1700 3.0 -0.000000 1.0200 1.0 3.141594 0.1000 4.0 3.141594
    enddihedral
--> SAME 

12/16
FESETUP
        dihedral
                atom0   H30
                atom1   C29
                atom2   H33
                atom3   DU36
                initial_form 0.0 0.0 0.0
                final_form 0.155555556 3.0 0.0
        enddihedral
BSS
--> Not found

13/16
FESETUP
        dihedral
                atom0   O19
                atom1   C18
                atom2   O32
                atom3   C29
                initial_form 1.4 1.0 3.141594 2.7 2.0 3.141594
                final_form 2.5 2.0 3.141594
        enddihedral
BSS
    dihedral
        atom0          O19
        atom1          C18
        atom2          O32
        atom3          C29
        initial_form   1.4000 1.0 3.141594 2.7000 2.0 3.141594
        final_form     2.5000 2.0 3.141594
    enddihedral
--> SAME

14/16
FESETUP
        dihedral
                atom0   O32
                atom1   C29
                atom2   H33
                atom3   DU35
                initial_form 0.0 0.0 0.0
                final_form 0.155555556 3.0 0.0
        enddihedral
BSS
--> Not found

15/16
FESETUP
        dihedral
                atom0   O19
                atom1   C18
                atom2   O32
                atom3   DU34
                initial_form 0.0 0.0 0.0
                final_form 2.0 1.0 0.0 2.5 2.0 3.141594
        enddihedral
BSS
--> Not found

16/16        
FESETUP
dihedral
                atom0   H30
                atom1   C29
                atom2   H33
                atom3   DU37
                initial_form 0.0 0.0 0.0
                final_form 0.155555556 3.0 0.0
        enddihedral
BSS
--> Not found

Then there is a BSS dihedral that doesn't have an equivalent in FESetup
    dihedral
        atom0          C18
        atom1          O32
        atom2          C29
        atom3          H31
        initial_form   0.3833 3.0 -0.000000
        final_form     0.0000 0.0 0.000000
    enddihedral

Which could be a problem with FESetup that needs investigation. 

* 2 impropers in FESetup, 2 impropers in BSS

FESETUP
        improper
                atom0   N17
                atom1   O19
                atom2   C18
                atom3   O32
                initial_form 1.1 2.0 3.141594 
                final_form 10.5 2.0 3.141594 
        endimproper
        improper
                atom0   C18
                atom1   C29
                atom2   O32
                atom3   DU34
                initial_form 0.0 0.0 0.0
                final_form 1.1 2.0 3.141594
        endimproper
BSS
    improper
        atom0          N17
        atom1          O19
        atom2          C18
        atom3          O32
        initial_form   1.1000 2.0 3.141594
        final_form     0.0 0.0 0.0
    endimproper
    improper
        atom0          N17
        atom1          O32
        atom2          C18
        atom3          O19
        initial_form   0.0 0.0 0.0
        final_form     10.5000 2.0 3.141594
    endimproper

In BSS the improper has been split in two and the one involving H34 has been missed. 

Input files attached
[issue77.zip](https://github.com/michellab/BioSimSpace/files/3040722/issue77.zip)

**Comment by lohedges** [comment]
Is it possible to move this to the other issue thread so that we can deal with all of the BSS FESetup comparisons (at least related ones) in the same place.

Cheers.

**Comment by lohedges** [comment]
I think this should now be fixed. The reasons for the differences are as follows:

__Dihedrals__: I happened to write records to file if both the start and end potential were null (all zero terms) and either end state involved a dummy atom. I now exclude these records from the pert file.

__Impropers__: After updating the code to exhaustively check for an equivalent improper in either end state, i.e. the same four atoms in both end state irrespective of the order, I forgot to check for duplicates when adding the records. I do wonder if it's possible to have an improper that contains the same four atoms types (in a different order) that has a different potential. If so, then I'll also need to check for equivalent potentials too.

When I use prepareFEP.py with the input that you've uploaded I now get identical output to FESetup.
