### ISSUE TITLE
Inconsistent free energies between reverse mappings

### ISSUE THREAD

**Issue by jmichel80** [michellab/BioSimSpace#79]
I found another bug with the pert files produced by BSS for SOMD

I have attached a few examples of simulations run in vacuum for pairs A-->B and B--A. 

[reversemaps.zip](https://github.com/michellab/BioSimSpace/files/3075520/reversemaps.zip)

The results are

```
e2m 2.74 +/- 0.08 kcal/mol-1
m2e -2.80 +/- 0.08 kcal/mol-1
5to16 -15.4 +/- 0.3 kcal/mol-1
16to5 17.3 +/- 0.3 kcal/mol-1
31to32 -5.6 +/- 0.1 kcal/mol-1
32to31 -3.6 +/- 0.2 kcal/mol-1
```
The free energies should be of opposite sign within statistical error which is only the case for ethane <--> methanol. 

The problem is [here](https://github.com/michellab/BioSimSpace/blob/devel/python/BioSimSpace/_SireWrappers/_molecule.py#L791-L792)

It looks like only the atoms that are changing ambertype are written to the pert file 'atom' section. This is incorrect since in general several atoms in a perturbation will keep their original ambertype but still change their partial charges. The safest solution is to write all atoms of the perturbed molecule to the pert file. The code for the internal degrees of freedom is not affected since the logic here correctly relies on atom types. 

@lohedges can you check if changing the code to above said behaviour fixes the inconsistency with the free energies?

**Comment by lohedges** [comment]
Thanks for catching this. What you suggest is actually what I was
originally doing, i.e. writing all atoms. I only updated to just the atoms
that changed ambertype the other week.

I'll see if adding add a check for changes in the charge fixes the problem
on Monday. If not, we can just write all atoms for safety (as you suggest).

**Comment by lohedges** [comment]
The pert file writer has now been updated. The atom section now contains any atoms for which the `ambertype`, `charge`, or `LJ` property changes between the lambda = 0 and lambda = 1 state. (These are the only keys associated with the atom record section.)

Could you test that this fixes the problem and close the issue when you are satisfied? If you don't have time, feel free to send some example input that I could run here.

As mentioned previously, for the D3R challenge I wrote everything to the pert file, e.g. like GROMACS allows you to do. (So the atom records contained things that did not change.) When doing this I ran into a few issues with buffer sizes on the GPU, so only wrote the potential records if they changed.

**Comment by jmichel80** [comment]
Hi @lohedges thanks for the bugfix. My test set now gives 

```
e2m 2.72 +/- 0.02 kcal/mol-1
m2e -2.73 +/- 0.02 kcal/mol-1
5to16 -14.36 +/- 0.07 kcal/mol-1
16to5 14.59 +/- 0.07 kcal/mol-1
31to32 -13.05 +/- 0.03 kcal/mol-1
32to31 13.03 +/- 0.03 kcal/mol-1
```
Not sure why 5to16 doesn't agree as well but that is certainly much better than a few days ago.

**Comment by lohedges** [comment]
Great, thanks for the update, that's good to hear. Does the 5to16 example give a similar error using a FESetup generated pert file too?
