### ISSUE TITLE
Remote notebook usage

### ISSUE THREAD

**Issue by oliverdutton** [michellab/BioSimSpace#90]
I'm running a jupyter notebook remotely through Chrome (tried other browsers, no difference) and the jupyter widgets don't display properly. e.g. viewMolecules() will not display the file and node.showControls() won't display a browse button to add the files.

I've run the notebook by running 
"jupyter notebook --no-browser --port=8889" on the HPC side, and linking it by 
"ssh -N -f -L localhost:8888:localhost:8889 username@bluecrystalp3.acrc.bris.ac.uk" locally and other functionality all seems to work perfectly.

Note: I'm working through some of the tutorial notebooks, that's where the images are from.

Thanks,
Oliver
<img width="1440" alt="Screenshot 2019-06-06 at 9 54 10 am" src="https://user-images.githubusercontent.com/44170519/59020129-472e9e00-8841-11e9-81ca-4ad30c60104b.png">

<img width="1440" alt="Screenshot 2019-06-06 at 9 49 50 am" src="https://user-images.githubusercontent.com/44170519/59019910-cd96b000-8840-11e9-91cc-348265a2c20c.png">

**Comment by lohedges** [comment]
Hi Oliver,

I'm not sure how you installed BioSimSpace, but it sounds like the widgets haven't been enabled and activated correctly. Could you try the following, assuming you have a Conda install of BioSimSpace, to see if it makes any difference:

```sh
jupyter-nbextension install fileupload --py --sys-prefix
jupyter-nbextension enable fileupload --py --sys-prefix
jupyter-nbextension install nglview --py --sys-prefix 
jupyter-nbextension enable nglview --py --sys-prefix
```

(If you installed into a Sire application, then you might need to use, e.g., `$HOME/sire.app/bin/jupyter-nbextension`.)

If this works, let me know how you went about installing BioSimSpace and I'll update the installation instructions accordingly.

Cheers.

**Comment by lohedges** [comment]
Note that you'll need to restart the Jupyer server for any changes to take effect.

**Comment by oliverdutton** [comment]
Running those lines has fixed it, both the showControls() and view() functionality works perfectly now.

I installed with Conda and then the extra package with pip as in the tutorial "https://biosimspace.org/install.html#conda-install" 
conda install -c rdkit -c conda-forge -c omnia -c michellab biosimspace
pip install fileupload pygtail pypdb

I looked at the errors from the widgets, should've posted them with the pictures:
 404 GET /static/nglview-js-widgets.js?v=20190606120127 (127.0.0.1) 1.93ms referer=http://localhost:8888/notebooks/BioSimSpace/Tutorials/BSS_alchemistry_2019-master/01_BSS_Setup/Exercise_01.ipynb

**Comment by lohedges** [comment]
Thanks for the update. In my local Conda install the widgets were activated automatically, but I guess we can't rely on this being the case. I'll update the installation instructions with a note regarding manual activation.

Thanks for posting. Feel free to close the issue if you are happy with the fix.

**Comment by oliverdutton** [comment]
Thank you very much, the tutorials are very useful and informative
