### ISSUE TITLE
Options for updating commandline options are not passed in parametrisation

### ISSUE THREAD

**Issue by ppxasjsm** [michellab/BioSimSpace#95]
# Expected Behavior

If I run something like this:
`
lig_param = BSS.Parameters.parameterise(lig,'gaff2',options={'-nc':1}, work_dir='test')
`
I expect the resulting readme to look like this:
```
# Antechamber was run with the following command:
/home/ppxasjsm/Software/amber18//bin/antechamber -at 2 -i antechamber.pdb -fi pdb -o antechamber.mol2 -fo mol2 -c bcc -s 2 -nc 1
```
Instead I get this:
```
# Antechamber was run with the following command:
/home/ppxasjsm/Software/amber18//bin/antechamber -at 2 -i antechamber.pdb -fi pdb -o antechamber.mol2 -fo mol2 -c bcc -s 2 -nc 0
```
This will result in an error because there are too many hydrogens. 

Somehow the options isn't passed on. Also looking at the code in the devel branch it is testing that options is a dictionary, but nothing seems to happen to the options. 

Attached is an example reproducing this
[bug.zip](https://github.com/michellab/BioSimSpace/files/3378134/bug.zip)

**Comment by lohedges** [comment]
This is your PDB file:

```
ATOM      1  N   UNK     1      18.272 -13.244  21.707  1.00  0.00
ATOM      2  C   UNK     1      18.075 -11.948  21.029  1.00  0.00
ATOM      3  C   UNK     1      17.402 -13.783  22.596  1.00  0.00
ATOM      4  O   UNK     1      16.403 -13.170  22.977  1.00  0.00
ATOM      5  C   UNK     1      16.673 -11.759  20.401  1.00  0.00
ATOM      6  O   UNK     1      16.178 -12.653  19.712  1.00  0.00
ATOM      7  C   UNK     1      19.174 -11.899  19.957  1.00  0.00
ATOM      8  C   UNK     1      17.653 -15.183  23.189  1.00  0.00
ATOM      9  N   UNK     1      16.051 -10.600  20.644  1.00  0.00
ATOM     10  C   UNK     1      20.273 -12.819  20.450  1.00  0.00
ATOM     11  N   UNK     1      16.410 -15.969  23.112  1.00  0.00
ATOM     12  C   UNK     1      18.139 -15.114  24.655  1.00  0.00
ATOM     13  C   UNK     1      14.714 -10.225  20.203  1.00  0.00
ATOM     14  C   UNK     1      19.553 -13.845  21.318  1.00  0.00
ATOM     15  C   UNK     1      19.563 -14.615  24.826  1.00  0.00
ATOM     16  C   UNK     1      13.647 -10.370  21.273  1.00  0.00
ATOM     17  C   UNK     1      20.657 -15.449  24.515  1.00  0.00
ATOM     18  C   UNK     1      12.911 -11.567  21.398  1.00  0.00
ATOM     19  C   UNK     1      21.974 -14.961  24.635  1.00  0.00
ATOM     20  C   UNK     1      11.898 -11.676  22.373  1.00  0.00
ATOM     21  C   UNK     1      22.201 -13.640  25.064  1.00  0.00
ATOM     22  C   UNK     1      11.622 -10.592  23.231  1.00  0.00
ATOM     23  C   UNK     1      21.113 -12.817  25.404  1.00  0.00
ATOM     24  C   UNK     1      12.374  -9.406  23.128  1.00  0.00
ATOM     25  C   UNK     1      19.804 -13.310  25.294  1.00  0.00
ATOM     26  C   UNK     1      13.377  -9.295  22.145  1.00  0.00
ATOM     27  H   UNK     1      18.254 -11.164  21.763  1.00  0.00
ATOM     28  H   UNK     1      18.804 -12.258  18.995  1.00  0.00
ATOM     29  H   UNK     1      19.547 -10.891  19.814  1.00  0.00
ATOM     30  H   UNK     1      18.381 -15.738  22.598  1.00  0.00
ATOM     31  H   UNK     1      16.567  -9.898  21.174  1.00  0.00
ATOM     32  H   UNK     1      20.842 -13.275  19.639  1.00  0.00
ATOM     33  H   UNK     1      20.974 -12.253  21.065  1.00  0.00
ATOM     34  H   UNK     1      16.552 -16.885  23.511  1.00  0.00
ATOM     35  H   UNK     1      15.686 -15.478  23.624  1.00  0.00
ATOM     36  H   UNK     1      16.126 -16.053  22.148  1.00  0.00
ATOM     37  H   UNK     1      17.461 -14.495  25.247  1.00  0.00
ATOM     38  H   UNK     1      18.090 -16.107  25.105  1.00  0.00
ATOM     39  H   UNK     1      14.752  -9.172  19.932  1.00  0.00
ATOM     40  H   UNK     1      14.421 -10.771  19.304  1.00  0.00
ATOM     41  H   UNK     1      20.169 -14.108  22.176  1.00  0.00
ATOM     42  H   UNK     1      19.368 -14.751  20.740  1.00  0.00
ATOM     43  H   UNK     1      20.494 -16.462  24.175  1.00  0.00
ATOM     44  H   UNK     1      13.124 -12.403  20.746  1.00  0.00
ATOM     45  H   UNK     1      22.812 -15.600  24.398  1.00  0.00
ATOM     46  H   UNK     1      11.335 -12.594  22.471  1.00  0.00
ATOM     47  H   UNK     1      23.210 -13.264  25.146  1.00  0.00
ATOM     48  H   UNK     1      21.269 -11.809  25.759  1.00  0.00
ATOM     49  I   UNK     1      12.063  -7.831  24.471  1.00  0.00
ATOM     50  H   UNK     1      18.989 -12.680  25.591  1.00  0.00
ATOM     51  H   UNK     1      13.955  -8.387  22.079  1.00  0.00
ATOM     52  H   UNK     1      10.849 -10.682  23.982  1.00  0.00
```

There is formal charge information, but it is incorrect, so BioSimSpace fails to pass the correct value for `nc` to Antechamber. As mentioned in [this](https://github.com/michellab/BioSimSpace/issues/40) issue, we could do something like FESetup and use OpenBabel to compute the formal charge if it is missing. I'd be okay with doing this, as long as we raise a warning to the user. I'm not sure what we would do if the information is there but is wrong. Perhaps we could compute it ourselves and raise an error if there is a mismatch.

To check the correct formal charge, do the following:

```python
import BioSimSpace as BSS

# Load your input PDB.
s = BSS.IO.readMolecules("input/1d.pdb")

# Save it back to PDB so we have element information.
 = BSS.IO.readMolecules("input/1d.pdb")
```

Dowload [this](https://github.com/michellab/BioSimSpace/files/3380767/formal_charge.txt) Python script (save with a `.py` extension) and run as follows after installing OpenBabel via Conda:

```sh
python formal_charge.py tmp.pdb
```

The output should be:

```
1
```

As for the options, this is hard to do in general since we don't know what the underlying parameterisation engine will be (could be AmberTools or GROMACS) so it's hard to keep things consistent across the different functions (the options are totally different). For now, I'll delete the general options dictionary and allow specific overriding of certain Antechamber options when you know that you are using a force field that it requires, e.g. `BioSimSpace.Parameters.Gaff`

**Comment by lohedges** [comment]
I've now exposed the `net_charge` option to the `BioSimSpace.Parameters.gaff` and `BioSimSpace.Parameters.gaff2` functions. You can't modify the option using the generic `BioSimSpace.Parameters.parameterise` function. There is also a new function, `BioSimSpace.Parameters.formalCharge`, that can compute the net formal charge on the molecule for you if the information in the PDB is missing or incorrect. To fix your problem:

```python
import BioSimSpace as BSS

m = BSS.IO.readMolecules("input/1d.pdb").getMolecules()[0]
m = BSS.Parameters.gaff(m, net_charge=BSS.Parameters.formalCharge(m))
```

This is pushed to `devel` but a new Conda package will take about an hour to build.

**Comment by lohedges** [comment]
Also, if you tried to do the parameterisation as you were before, i.e. with the wrong formal charges, then BioSimSpace will raise a warning and highlight the mismatch with the computed value.

**Comment by ppxasjsm** [comment]
Excellent! Thank you.

**Comment by lohedges** [comment]
No problem. Feel free to close when you're happy things are working as expected. I still need to have a think about how to support a wider range of parameterisation options generally, but at least the documentation is no longer misleading.

**Comment by dlukauskis** [comment]
Hi, the BioSimSpace.Parameters.gaff function works fine, but BioSimSpace.Parameters.gaff2 doesn't. It raises: "TypeError: __init__() got an unexpected keyword argument: 'net_charge'". Attaching a folder for replication.
[Thrombin.zip](https://github.com/michellab/BioSimSpace/files/3391485/Thrombin.zip)

**Comment by lohedges** [comment]
Thanks. This should now be fixed on the devel branch.
